web-components/src/components/inputs/ControlledTextField.tsx, web-components/src/components/inputs/FieldFormControl.tsx, web-components/src/components/section/OnBoardingSection.tsx, web-registry/src/components/organisms/MethodologySteps.tsx, web-registry/src/components/organisms/StepsSection.tsx, web-registry/src/components/templates/EditFormTemplate.tsx, web-registry/src/components/templates/OnboardingFormTemplate.tsx, web-registry/src/components/templates/index.ts, web-registry/src/pages/BasicInfo.tsx, web-registry/src/pages/EntityDisplay.tsx, web-registry/src/pages/Media.tsx, web-registry/src/pages/ProjectList.tsx, web-registry/src/pages/ProjectLocation.tsx, web-registry/src/pages/Roles.tsx, web-registry/src/pages/Story.tsx
Closes: regen-network/regen-registry#782
Also fixes: https://monosnap.com/file/UENMzD25yWDAShVljPGlyGKRjnR97N
Also fixes missing "see example" links in Story form
---
I have...
I have...
=> Fix "see example" in wrong place

web-components/src/components/description/index.tsx, web-components/src/components/label/index.tsx, web-components/src/components/read-more/index.tsx, web-components/src/components/table/TablePagination.tsx, web-registry/graphql.schema.json, web-registry/src/components/atoms/Link.tsx, web-registry/src/components/molecules/EcocreditsSection.tsx, web-registry/src/components/organisms/CreditActivityTable.tsx, web-registry/src/components/organisms/CreditBatches.tsx, web-registry/src/components/organisms/CreditTotals.tsx, web-registry/src/generated/graphql.tsx, web-registry/src/graphql/CreditClassByOnChainId.graphql, web-registry/src/lib/block-explorer.ts, web-registry/src/lib/ecocredit.ts, web-registry/src/lib/metadata-graph.ts, web-registry/src/lib/titleCase.ts, web-registry/src/lib/wallet.tsx, web-registry/src/pages/CreditClassDetails.tsx, web-registry/src/pages/CreditClassDetailsSimple.tsx, web-registry/src/pages/CreditClassDetailsWithContent.tsx, web-registry/src/types/ledger/ecocredit.ts
Closes: regen-network/regen-registry#805
Needs server update https://github.com/regen-network/registry-server/pull/129
If a `classId` is provided in url, like `/credit-classes/C02`, show the simplified credit class page with ledger data, and metadata fetched from postgres db.
The main new code is `CreditClassDetailsSimple`.
Modified a few shared components to make them easier to work with `sx`, among other tweaks.
Added a `metadata-graph` REST route file.
---
I have...
I have...
=> Simple credit class page

web-registry/src/hooks/useBasketDetails.ts, web-registry/src/lib/ecocredit.ts
Closes: #XXXX
---
I have...
I have...
=> Use queryEcoBatchInfo

web-components/src/components/form/BasketPutForm.tsx, web-components/src/components/form/BasketTakeForm.tsx, web-components/src/components/form/CreditRetireForm.tsx, web-components/src/components/form/CreditSendForm.tsx, web-components/src/components/form/form.stories.tsx, web-components/src/components/inputs/AmountField.tsx, web-components/src/components/modal/BasketPutModal.tsx, web-components/src/components/modal/BasketTakeModal.tsx, web-components/src/components/modal/CreditRetireModal.tsx, web-components/src/components/modal/CreditSendModal.tsx, web-components/src/components/modal/modal.stories.tsx, web-registry/src/__snapshots__/storyshots.test.ts.snap, web-registry/src/hooks/useMsgClient.ts, web-registry/src/pages/MyEcocredits.tsx
Closes: https://github.com/regen-network/regen-registry/issues/809
Closes: https://github.com/regen-network/regen-registry/issues/889
---
I have...
I have...
=> Send and retire ecocredits

web-registry/src/hooks/useBasketDetails.ts, web-registry/src/lib/metadata-graph.ts, web-registry/src/types/ledger/ecocredit.ts
Closes: #XXXX
---
I have...
I have...
=> Add getMetadataFromUint8Array

web-components/src/components/credits/CreditDetails.tsx, web-components/src/components/form/BasketTakeForm.tsx, web-components/src/components/hexa-images/index.tsx, web-components/src/components/inputs/ImageField.tsx, web-components/src/components/inputs/ImageUpload.tsx, web-components/src/components/tabs/tabs.stories.tsx, web-registry/src/components/molecules/BatchInfoGrid.tsx, web-registry/src/components/molecules/BatchMetadata.tsx, web-registry/src/components/organisms/ProjectTopSection.tsx, web-registry/src/generated/json-ld/batch-metadata.ts, web-registry/src/types/rdf/index.ts
Closes: regen-network/regen-registry#870
- removes verification and monitoring docs from Credit Batch metadata
- adds Additional Certifications
- cleans up some lint errors
Testable redwood ledger metadata at https://deploy-preview-910--regen-registry.netlify.app/credit-batches/C01-20190101-20210101-008
---
I have...
I have...
=> batch metadata update

web-components/src/components/inputs/RoleField.tsx, web-components/src/components/inputs/inputs.stories.tsx, web-components/src/components/modal/IndividualModal.tsx, web-components/src/components/modal/OrganizationModal.tsx, web-registry/src/components/organisms/BasicInfoForm.tsx, web-registry/src/components/organisms/EntityDisplayForm.tsx, web-registry/src/components/organisms/MediaForm.tsx, web-registry/src/components/organisms/ProjectLocationForm.tsx, web-registry/src/components/organisms/RolesForm.tsx, web-registry/src/components/organisms/StoryForm.tsx, web-registry/src/lib/rdf.test.ts, web-registry/src/lib/rdf.ts, web-registry/src/lib/transform.ts, web-registry/src/pages/BasicInfo.tsx, web-registry/src/pages/Certificate.tsx, web-registry/src/pages/ChooseCreditClass.tsx, web-registry/src/pages/CreditsIssue.tsx, web-registry/src/pages/CreditsRetire.tsx, web-registry/src/pages/CreditsTransfer.tsx, web-registry/src/pages/EntityDisplay.tsx, web-registry/src/pages/Media.tsx, web-registry/src/pages/ProjectLocation.tsx, web-registry/src/pages/Roles.tsx, web-registry/src/pages/Story.tsx
Closes: https://github.com/regen-network/regen-registry/issues/904
---
I have...
I have...
=> Update project forms to use compacted JSON-LD

web-registry/src/components/templates/PortfolioTemplate.tsx
Closes: https://github.com/regen-network/regen-registry/issues/930
---
I have...
I have...
=> Switch ordering of ecocredits and basket tokens on portfolio

.github/PULL_REQUEST_TEMPLATE.md, README.md
Ref: https://github.com/regen-network/regen-web/pull/968 and https://github.com/regen-network/regen-web/pull/971
=> Manual backport of #968 and #971 to redwood

.github/PULL_REQUEST_TEMPLATE.md, README.md
Ref: https://github.com/regen-network/regen-web/pull/968 and https://github.com/regen-network/regen-web/pull/971
=> Manual backport of #968 and #971 to hambach

.github/PULL_REQUEST_TEMPLATE.md
Add backport instructions in PR template
---
I have...
I have...
=> Add backport instructions in PR template

web-registry/src/hooks/useMsgClient.ts, web-registry/src/pages/MyEcocredits.tsx, web-registry/src/pages/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/MyEcocredits/hooks/useBasketPutSubmit.tsx, web-registry/src/pages/MyEcocredits/hooks/useBasketTakeSubmit.tsx, web-registry/src/pages/MyEcocredits/hooks/useCreditRetireSubmit.tsx, web-registry/src/pages/MyEcocredits/hooks/useCreditSendSubmit.tsx, web-registry/src/pages/MyEcocredits/hooks/useMyEcocreditsStyles.tsx, web-registry/src/pages/MyEcocredits/hooks/useOpenTakeModal.tsx, web-registry/src/pages/MyEcocredits/hooks/useUpdateCrediBaskets.tsx, web-registry/src/pages/MyEcocredits/index.ts, web-registry/src/types/react/use-state.ts
Closes: regen-network/regen-registry#964
- Add batch denom link to `send` and `retire` actions
- refactor `MyEcocredits`: split callbacks into hooks
---
I have...
``` …
```
=> feat: add batch denom link

web-components/src/utils/format.ts, web-registry/src/components/molecules/BatchInfoGrid.tsx, web-registry/src/components/organisms/CreditBatches.tsx
Closes: #1007 
- Adds UTC option to formatDate util. This leverages the `utc` plugin from `dayjs`
- Applies UTC formatting to CreditBatches table and BatchDetails page
---
I have...
``` …
```
=> fix: batch dates to UTC

web-components/src/utils/schemaURL.ts, web-registry/src/components/organisms/MediaForm/MediaForm.tsx
Closes: #XXXX
---
I have...
```
git push origin redwood-backport-<PR#>`
```
c. Open new PRs in …
=> fix: Update MediaForm validation logic

web-registry/.eslintrc.js
Closes: regen-network/regen-registry#990
This ESLint rule is no longer needed since React 17, see the issue for more context.
For VSCode users it might have been frustrating if you were using the auto-import clean/sort command which removes the React import and triggers the ESLint rule.
The default binding for the VSCode organize import command:
---
I have...
a. Pull latest `master`, `hambach` and `redwood` …
=> chore: remove react unused eslint rule

web-registry/src/components/organisms/CreditBatches.tsx, web-registry/src/components/organisms/EcocreditsTable.tsx, web-registry/src/lib/ecocredit/api.ts, web-registry/src/types/ledger/ecocredit.ts
Closes: regen-network/regen-registry#1015
Add the project request to the ledger to complete the credit batch data with the location (jurisdiction)
---
I have...
``` …
```
=> feat: add project query and display location

web-registry/src/components/organisms/RegistryNav.tsx
Closes: regen-web/regen-registry#1046
Update navigation:
- remove program
- add Trade (link to `/storefront`)
- update projects to link directly to `/projects`
**Note: not to be merged before `/storefront` and `/projects` pages are available**
---
I have...
```
git …
```
=> feat: 1046 Update navigation

web-www/src/components/ConnectSection.tsx
Bug fix: https://regen-network.slack.com/archives/C01LX9E8QN8/p1658989565298679
---
I have...
```
git …
```
=> fix: center text on connect section

web-components/src/components/inputs/LocationField.tsx
Closes: https://github.com/regen-network/regen-registry/issues/1097
---
I have...
``` …
```
=> fix: add more types of geographic features to geocoder

package.json, web-registry/src/hooks/useQueryIfCreditClassAdmin.ts, web-registry/src/hooks/useQueryIfCreditClassCreator.ts, web-registry/src/hooks/useQueryListAdminClasses.ts, web-registry/src/lib/ecocredit/api.ts, web-registry/src/pages/CreateCreditClass/CreateCreditClass.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/Dashboard/MyCreditClasses/MyCreditClasses.tsx
Closes: https://github.com/regen-network/regen-registry/issues/1103
---
I have...
``` …
```
=> feat: add permissions for credit class creators and credit class admins

web-registry/src/components/organisms/RegistryNav.tsx
Closes: regen-network/regen-registry#1119
- uses chainId as a feature flag:
If Mainnet, show legacy nav items (equivalent to current PROD - expected when v4 -> master deploy preview)
Else show v4 nav items (expected for this deploy preview):
---
I have...
```
git …
```
=> feat 1119 nav feature flag

web-registry/src/pages/ProjectLocation/ProjectLocation.tsx, web-registry/src/pages/ProjectReview/ProjectReview.util.tsx
Related: regen-network/regen-registry#1097
Fixes 2 bugs. 
1. When picking a region ("Taita-Tveta, Kenya"), the ISO code lookup fails
2. When going back to edit location step, postgres error prevents update `error: addresses object does not exist`
- fix: getCountryKey from country name
- delete db address mutations in ProjectLocationForm because they caused blocking error on update - not needed.
---
I have...
3. If your branch does have merge commits:
a. …
=> fix: Location Input does not give valid ISO code, can't edit location

web-registry/src/hooks/useQueryIfCreditClassCreator.ts, web-registry/src/hooks/useQueryIfIssuer.ts, web-registry/src/lib/asyncSome.ts, web-registry/src/pages/Dashboard/Dashboard.tsx
Closes: regen-network/regen-registry#1113
Fix: Project tab is visible only to credit class issuers and existing project admins
- uses an `asyncSome` method to make sure to wait until an a credit class issuer list returns a match with user's wallet before returning true.
---
I have...
b. Create new branches for backports and merge `master` (replace `<PR#>` …
=> fix 1113 project permissions

package.json, web-components/.eslintrc.js, web-components/jest.config.js, web-components/package.json, web-components/src/components/cards/Card.tsx, web-components/src/components/cards/CreateCards/CreateCard.tsx, web-components/src/components/cards/GreenTopIconCard.tsx, web-components/src/components/cards/ImageActionCard.tsx, web-components/src/components/cards/MediaCard.tsx, web-components/src/components/cards/ReviewCard/ReviewCard.ItemDisplay.tsx, web-components/src/components/cards/ReviewCard/ReviewCard.tsx, web-components/src/components/faq/Question.tsx, web-components/src/components/icons/AvailableCreditsIcon.tsx, web-components/src/components/icons/AvailableCreditsIconAlt.tsx, web-components/src/components/icons/AvatarIcon.tsx, web-components/src/components/loading/Loading.tsx, web-components/src/components/table/DocumentationTable.tsx, web-components/src/components/text-layouts/LabeledDetail.tsx, web-components/src/components/text-layouts/TitleBody.tsx, web-components/tsconfig.json, web-registry/package.json, web-registry/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-www/package.json, yarn.lock
Just set this up quickly and didn’t test much - we should definitely check nothing breaks before merging
- Add ts-jest + setup
- Swap path alias for absolute import 
- Correct a few imports / exports from changing the `isolatedModules` config setting (this is probably something we want… can avoid circular deps)
- Removed `tsc` before linting (I have another PR that does this, but just did it here to quicken the time to run `format-and-fix` - shoudln’t impact anything)
- ran `format-and-fix
NOTE: if we want a smaller diff, we can revert the `paths` alias that was changed: https://github.com/regen-network/regen-web/pull/1136/files#diff-52492c429214977badbfa365bb1d6dba4ec855ddf9bfdecdd74bfd46faad0928L9, then re-run `format-and-fix`. Should return stuff to the prior state. 
---
_All items are …
=> fix: swap react-scripts for jest, convert path alias to absolute import

web-components/src/components/empty-state/EmptyState.stories.tsx, web-components/src/components/empty-state/EmptyState.tsx, web-components/src/components/empty-state/index.ts, web-components/src/components/icons/EmptyCartIcon.tsx, web-registry/src/__snapshots__/storyshots.test.ts.snap, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx
Closes: regen-network/regen-registry#1049
- Add EmptyState component
- Use EmptyState for sell orders table
---
I have...
```
git checkout -b redwood-backport-<PR#> …
```
=> feat: add empty state for sell orders table

web-registry/src/App.tsx, web-registry/src/lib/ga.ts
Closes: https://github.com/regen-network/regen-registry/issues/1069
---
I have...
``` …
```
=> fix: adjust GA to track all registry pages

web-registry/src/hooks/useEcocredits.ts, web-registry/src/lib/ecocredit/api.ts, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/Home/Home.constants.ts, web-registry/src/pages/Home/Home.styles.tsx, web-registry/src/pages/Home/Home.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx
Closes: regen-network/regen-registry#1056
- Add a button that links to `/projects` page
- Enhance dashboard performance by using one `Balances` query instead of many `Balance` queries
- Add loader to user eco credits table
- Add `limit` parameter to `useProjectsSellOrders` hook
- Some refactor of styles/utils function into dedicated files
On a test account with 4 credits:
| Before  | After  |
|---|---|
| ~186 requests  | ~88 requests  |
| ![image](https://user-images.githubusercontent.com/530644/186175031-76eca0d4-089d-4311-b362-6b4307b394b1.png) | ![image](https://user-images.githubusercontent.com/530644/186174949-347b23b6-2272-4bb6-b228-aee4f31246c2.png)  |
---
please add links to any relevant …
=> feat: discover projects section + performance enhancement

web-registry/src/components/organisms/CreditTotals.tsx, web-registry/src/pages/Home/Home.tsx, web-registry/src/pages/Projects/Projects.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx
Closes: regen-network/regen-registry#1143
- Fixes math error in calculating total ecocredits on Activity page
- Fixes Featured Projects failure to load in PROD
---
I have...
``` …
```
=> fix: parse numbers before summing

web-registry/src/features/marketplace/BuySellOrderFlow.tsx, web-registry/src/pages/Home/Home.FeaturedProjects.tsx, web-registry/src/pages/Home/Home.tsx, web-registry/src/pages/Projects/Projects.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx
Closes: regen-network/regen-registry#1152
- Wire buy sell order action on home page
- Refactor featured projects to its own component
- Refactor buy sell order action on projects page into `BuySellOrderFlow`to make it reusable
- Revert sort on home page to keep projects on the featured section with sell orders first
---
I have...
b. Create new branches …
=> feat: wire buy action home

web-components/src/components/inputs/NumberTextField.tsx, web-components/src/components/inputs/TextField.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.styles.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.utils.ts
Closes: regen-network/regen-registry#1164
- add validation to credit count in `BuyCreditsModal`
- fix broken error display for `NumberTextField` component
---
I have...
``` …
```
=> fix: buy order max input and format amount to spend

netlify.toml, web-components/src/components/banner/CookiesBanner.tsx, web-registry/package.json, web-registry/src/App.tsx, yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1110
Adds integration to Sentry, following the guide for Sentry <> React:
https://docs.sentry.io/platforms/javascript/guides/react/
Thus far, capturing un-tracked exceptions and integration with `react-router-dom` is configured. We may want to consider adding support for ["react error boundaries"](https://docs.sentry.io/platforms/javascript/guides/react/components/errorboundary/) but I don't know what those are and if they make sense for our application. Feedback on that will be appreciated. 
---
I have...
1. If …
=> feat: add sentry setup including support for react router

netlify.toml, web-auth/.env.example, web-registry/src/siteMetadata.ts, web-www/src/components/MarketingNav.tsx, web-www/src/layouts/layout.tsx, web-www/static/_redirects
Closes: https://github.com/regen-network/regen-registry/issues/1106
---
I have...
``` …
```
=> feat: redirect registry to app

web-components/src/components/cards/CreditClassCard/CreditClassCard.stories.tsx, web-components/src/components/cards/CreditClassCard/CreditClassCard.styles.tsx, web-components/src/components/cards/CreditClassCard/CreditClassCard.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.ts
Closes: regen-network/regen-registry#1061
- Add credit class card to project page
- Modify CreditClassCard to accept React component for title/description in order to handle sanity content
---
I have...
```
git merge …
```
=> feat: add credit class card to project details

netlify.toml, web-registry/src/App.tsx
Fixes: https://github.com/regen-network/regen-web/pull/1172
---
I have...
``` …
```
=> fix: add REACT_APP_ prefix to sentry env var

web-components/src/components/form/CreateSellOrderForm.tsx, web-components/src/components/inputs/NumberTextField.tsx, web-components/src/components/inputs/SelectTextField.tsx, web-components/src/components/inputs/TextField.tsx, web-components/src/components/modal/CreateSellOrderModal.tsx, web-components/src/components/modal/modal.stories.tsx, web-registry/src/hooks/useEcocreditQuery.ts, web-registry/src/hooks/useMarketplaceQuery.ts, web-registry/src/hooks/useQueryIfCreditClassCreator.ts, web-registry/src/lib/ecocredit/api.ts, web-registry/src/lib/ecocredit/marketplace/marketplace.ts, web-registry/src/lib/ecocredit/marketplace/marketplace.types.ts, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.utils.ts, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreateSellOrderSubmit.tsx
Closes: regen-network/regen-registry#1158
**Node:** this PR has not been tested yet because there's no approved denom on redwood yet but the code is ready to be reviewed.
Also, this PR uses changes from the `main` ledger branch. We will need a release from the ledger in order to properly update regen-js.
- add hook + API file marketplace module (like the ecocredit one)
- Get only on-chain allowed denoms by calling `AllowedDenoms`
- Add dropdown with on-chain denoms in `CreateSellOrderForm`
- Migrate some ledger API changes because of ecrocredit proto file update
---
I have... …
=> feat: add denom dropdown in sell order creation

web-registry/src/features/marketplace/BuySellOrderFlow.tsx, web-registry/src/pages/Home/Home.FeaturedProjects.tsx, web-registry/src/pages/Marketplace/Storefront/hooks/useCancelSellOrderSubmit.tsx, web-registry/src/pages/Projects/Projects.tsx
Closes: regen-network/regen-registry#1184
- format price correctly on cancel sell order modal confirmation
- fix an issue that prevents opening the buy order modal on the same project twice
---
I have...
```
git merge …
```
=> fix: format price correctly + buy modal open issue

web-components/src/components/icons/QuestionIconOutlined.tsx, web-components/src/components/icons/TradeableIcon.tsx, web-components/src/components/icons/icons.stories.tsx, web-components/src/components/info-label/InfoLabel.stories.tsx, web-components/src/components/info-label/InfoLabel.tsx, web-components/src/components/info-label/InfoLabel.types.ts, web-components/src/components/info-label/InfoLabel.utils.ts, web-components/src/components/info-label/index.ts, web-registry/src/__snapshots__/storyshots.test.ts.snap, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.config.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.constants.ts, web-registry/src/components/organisms/SellOrdersTable/SellOrderstable.PurchaseIcon.tsx
Closes: regen-network/regen-registry#1204
add:
- new purchase options column
- new InfoLabel component
- new icons
---
I have...
``` …
```
=> feat:  add new purchase option sell orders column

web-registry/src/components/organisms/CreditBatches/CreditBatches.tsx, web-registry/src/components/organisms/EcocreditsTable.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.config.tsx, web-registry/src/hooks/batches/useBatchesWithSupply.tsx, web-registry/src/hooks/useBasketTokens.ts, web-registry/src/hooks/useEcocredits.ts, web-registry/src/lib/ecocredit/api.ts, web-registry/src/lib/metadata-graph.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.normalizer.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Marketplace/Storefront/hooks/useFetchMetadataProjects.tsx, web-registry/src/styles/table.ts, web-registry/src/types/ledger/ecocredit.ts
Closes: regen-network/regen-registry#1072 regen-network/regen-registry#1191 regen-network/regen-registry#1225
- add the project name and credit class name columns to all data tables.
- update hooks and API calls to project name and credit class name.
- add common style for an ellipsis column with approx ~10 char.acters
- prevent unnecessary requests from `useBasketTokens` hook.
- filter credit class column on some pages
---
I have...
2. If your branch …
=> feat: add project name and credit class name to tables

web-registry/src/components/molecules/Statistic.tsx, web-registry/src/components/organisms/CreditBatches/CreditBatches.tsx, web-registry/src/components/organisms/CreditTotals.tsx, web-registry/src/lib/ecocredit/api.ts
Closes: regen-network/regen-registry#1236
- query transactions by `DESC` order to get the latest ones
- add skeleton to statistics header
- reduce number of queries done by statistics header
---
I have...
```
git merge …
```
=> fix: activity missing events

web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx, web-registry/src/utils/number/format.ts, web-registry/src/utils/number/format/format.test.ts, web-registry/src/utils/number/format/format.ts
Closes: regen-network/regen-registry#1231
Before the computing of the total available credits of a project sometimes end up with `NaN` when a project had sell orders with fractional quantity (ie: 0.01).
We're now parsing all order quantities as if they could have decimals.
Note: Ensure if having orders with fractional quantity is legit or if it should be prevented earlier on, will clarify that.
---
I have...
a. …
=> fix: orders with decimals quantity

web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.utils.ts, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrderstable.PurchaseIcon.tsx
Closes: regen-network/regen-registry#1205 regen-network/regen-registry#1233
- the sell orders in the buy modal are now grouped by their tradable status
- fix reversed tradable label on the storefront page
- change tradeable labels wording
---
I have...
```
git …
```
=> feat: group sell orders in buy modal and update tradable label in storefront

web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
Closes: regen-network/regen-registry#1161
- change buy modal wording
- add learn more links
---
I have...
```
git …
```
=> feat: change buy modal wording

netlify.toml, web-registry/src/components/organisms/Portfolio.tsx, web-registry/src/hooks/useQueryBaskets.ts, web-registry/src/lib/ledger.ts
Closes: regen-network/regen-registry#1243
- disable basket feature
---
I have...
``` …
```
=> chore: disable basket feature

web-registry/src/features/marketplace/CreateSellOrderFlow/hooks/useCreateSellOrderData.tsx, web-registry/src/hooks/useQueryIfIssuer.ts, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.utils.ts
Closes: regen-network/regen-registry#1185
- filter batch option without tradable credit
- prevent multiple fetching for checking issuer
---
I have...
```
git …
```
=> fix: remove option with no tradable credit on create sell order

web-registry/src/components/organisms/AppFooter.tsx
Closes: https://github.com/regen-network/regen-registry/issues/1230
---
I have...
``` …
```
=> chore: add link to discord support channel

web-registry/src/components/templates/ProjectDetails/ProjectDetails.MoreProjects.tsx
Closes: regen-network/regen-registry#1265
Simply add the modal with the credit purchase flow and manage the selection status etc.
---
I have...
``` …
```
=> fix: add buy credits flow and modal state to more projects section

web-components/src/components/form/CreditSendForm.tsx, web-components/src/components/modal/CreditSendModal.tsx, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx
Closes: regen-network/regen-registry#1263
We have 2 implementations for the recipient's address field. One that uses YUP, which does do regen address validation, and another implementation with plain validation. It simply adds the corresponding util function to the flat validation.
Also passed from the registry application down to the components (while they are in web-components) is the address prefix for validation.
---
I have...
2. If your branch does …
=> feat: add regen address validation and prefix to send implementation

web-components/src/components/form/CreateSellOrderForm.tsx, web-components/src/components/inputs/validation.ts
Closes: regen-network/regen-registry#1229
Add validation to askDenom field to be required
---
I have...
```
git merge …
```
=> feat: add validation to askDenom field in create sell order

web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts
Fixes whitescreen on legacy project pages.
- handles the null case for projects with no "admin" field, or still loading
---
I have...
``` …
```
=> fix: handle undefined in getDisplayAdmin

web-components/src/components/form/CreditRetireForm.tsx, web-components/src/components/form/CreditSendForm.tsx, web-components/src/components/inputs/AmountField.tsx, web-components/src/components/modal/FormModalTemplate.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditSendSubmit.tsx
Closes: regen-network/regen-registry#1190
- simplify send credit flow with retire option
- allow `AmountField` to have an `auxiliarLabel`
- change `MyEcoCredits` modals width to take scrollbar into account
- add link to recipient in send tx confirmation modal
---
I have...
b. Create new branches for backports and merge `master` (replace `<PR#>` with your …
=> feat: update send modal retire flow

web-registry/src/App.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx
Closes: regen-network/regen-registry#1287
The carbonplus grasslands page (offchain credit class) was frozen and unresponsive, because an onchain query parameter was being initialized by default as empty list, despite not being an onchain case (undefined param).
---
I have...
b. Create new branches for backports and merge `master` (replace `<PR#>` with …
=> Fix CarbonPlus Grasslands page unresponsive

web-components/src/components/modal/index.tsx, web-registry/src/App.tsx, web-registry/src/components/organisms/Modals/MobileSupport/MobileSupportModal.tsx, web-registry/src/components/organisms/RegistryNav.tsx
Closes: regen-network/regen-registry#1285
- add modal to warn about mobile support
- update RegenModal to use optionally fullscreen for mobile
---
I have...
```
git …
```
=> feat: add mobile support warning

web-components/src/components/inputs/Radio.tsx, web-components/src/components/inputs/Toggle.tsx, web-components/src/components/inputs/inputs.stories.tsx, web-components/src/components/tooltip/InfoTooltipWithIcon.tsx, web-components/src/components/typography/typography.stories.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.styles.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
Closes: regen-network/regen-registry#1160
- fix tooltip for Toggle component
- update type to pass ReactNode in tooltip
- add tooltip in `BuyCreditsModal` toggle
- update global radio disabled style
- disable LinkStyle in toggle description when disabled
- update retire option in disabled state in `BuyCreditsModal`
---
I have...
b. Create new branches for …
=> feat: customize disabled toggle

web-components/src/components/form/CreateSellOrderForm.tsx
Closes: regen-network/regen-registry#1272
---
I have...
```
git push origin redwood-backport-<PR#>` …
```
=> chore: spacing between selectors in sell orders form

web-registry/src/pages/Projects/Projects.tsx
Closes: regen-network/regen-registry#1298
---
I have...
```
git push origin redwood-backport-<PR#>` …
```
=> fix: justify cards section to center in projects page

web-registry/src/pages/CreditClassDetails/CreditClassDetails.ApprovedMethodologies.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.constants.ts
Closes: regen-network/regen-web#1365
- display all approved offset protocols links on credit class page
---
I have...
```
git checkout -b redwood-backport-<PR#> …
```
=> feat: display all approved offset protocols

web-components/src/components/form/CreditRetireForm.tsx
Closes: regen-network/regen-registry#1221
* The Retire form works standalone and also as part of Send
---
I have...
```
git checkout -b redwood-backport-<PR#> …
```
=> chore: add location infotooltip to Retire form

web-components/src/components/inputs/validation.ts
Closes: regen-network/regen-registry#1260
---
I have...
```
git push origin redwood-backport-<PR#>` …
```
=> feat: add decimal places validation to amount field

web-components/src/components/form/CreditRetireForm.tsx, web-components/src/components/inputs/LocationCountryField.tsx, web-components/src/utils/locationStandard.ts, web-registry/src/components/organisms/CreditsPurchaseForm.tsx, web-registry/src/pages/ProjectReview/ProjectReview.util.tsx
Closes: regen-network/regen-registry#1291
* Extend function to prepare the list of country options. Now optionally filters using the list of excluded countries.
* Refactor by encapsulating the `iso-3166-2` library in a few functions in the `locationStandard` file.
---
I have...
b. Create new branches for backports and merge `master` (replace `<PR#>` with …
=> Feat exclude some countries in retirement flow

web-registry/src/pages/Marketplace/Storefront/Storefront.normalizer.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts
Closes: http://regen-network/regen-registry#1299
- paginate metadata queries on storefront page
- wait for metadata before removing skeleton loader
| Before (redwood)  | After (redwood)  |
|---|---|
| **225 requests**  | **27 requests**  |
---
I have...
```
git …
```
=> perf: paginate metadata queries on storefront

.github/PULL_REQUEST_TEMPLATE.md
Closes: regen-network/regen-registry#1070
[New doc](https://github.com/regen-network/regen-web/blob/d3672c8a9c7c5a9d00e8c0197388a2e31954eb9f/.github/PULL_REQUEST_TEMPLATE.md)
Change PR document workflow as follow:
- all new PR should now target `dev` instead of `master`
- if the PR is a bug fix then it should be also backported into `master` (on top of `hambach` and `redwood`)
---
I have...
a. Pull latest …
=> doc: update PR template to handle dev branch

web-components/src/components/header/MarketplaceLaunchBanner.stories.tsx, web-components/src/components/header/MarketplaceLaunchBanner.tsx, web-components/src/components/header/index.tsx, web-registry/src/__snapshots__/storyshots.test.ts.snap
Closes: https://github.com/regen-network/regen-web/issues/1133
Note: Don't merge this until the marketplace v1 is live.
---
I have...
``` …
```
=> feat: add MarketplaceLaunchBanner component

web-registry/src/components/atoms/Link.tsx, web-registry/src/components/atoms/LinkWithArrow.tsx, web-registry/src/components/molecules/ProjectMetadata/ProjectMetadata.CFC.tsx, web-registry/src/components/molecules/ProjectMetadata/ProjectMetadata.VCS.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/generated/json-ld/cfc-project-metadata.ts, web-registry/src/generated/json-ld/project-metadata.ts, web-registry/src/lib/ecocredit/constants.ts, web-registry/src/lib/metadata-graph.ts
Closes: regen-network/regen-registry#1322
Closes: regen-network/regen-web#1366
- Fix: display IRI-resolved metadata for onchain projects (previously it was showing the meta from db project.metadata)
- Add `MsgUpdateProjectMetadata`, `MsgUpdateProjectAdmin`, and `MsgBridge` to Activity page.
---
I have...
your PR:
a. Pull latest …
=> fix: display IRI metadata

web-registry/src/pages/Roles/Roles.tsx
Closes: regen-network/regen-registry#1325
- On Roles step, gets Credit Class Id from selected credit class context instead of postgres.
- With credit class ID available, the Roles Form now shows the correct ProfileModal:
---
I have...
your PR:
b. Create new branches for …
=> fix: project dev image

web-registry/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx
Closes: regen-network/regen-registry#1326
- This change uses a simple href to change project pages, instead of `useNavigate`. This restores data reloading (including images)
- Also, this shows a bare-bones page if there is onChain data, but no DB project (instead of 404)
We may want to revisit `useNavigate` to restore a react-router implementation (much nicer UX), but it was not triggering data refresh in this case.
---
I have...
your PR:
- …
=> Fix: project data reload

web-registry/src/features/ecocredit/CreateBatchBySteps/hooks/useUpdateProjectClass.ts
Closes: regen-network/regen-registry#1331
---
I have...
your PR:
```
git merge dev …
```
=> fix: reference update - VCS is C01, CFC is C02 in mainnet

web-registry/src/lib/rdf.compacted-context.ts
Closes: regen-network/regen-registry#1332
---
I have...
your PR:
```
git merge dev …
```
=> fix: adjust COMPACT_CONTEXT to provide typical geojson Feature style

web-registry/public/index.html, web-registry/src/components/templates/ProjectDetails/hooks/useSeo.ts, web-registry/src/siteMetadata.ts
fix: change site title to regen marketplace
---
I have...
your PR:
```
git merge dev …
```
=> fix: change site title to regen marketplace

web-components/src/components/sliders/ProjectMedia.tsx
- handle projects with 3 assets
---
I have...
your PR:
```
git merge dev …
```
=> fix: project media with 3 images

web-components/src/components/modal/OrganizationModal.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx, web-registry/src/components/organisms/RolesForm.tsx, web-registry/src/pages/Home/Home.tsx, web-www/src/pages/resources.tsx, web-www/src/sections/home/LedgerSection.tsx
Closes: regen-network/regen-registry#1334
- Updates headline to "Unlock Regenerative Finance with Regen Marketplace"
- Hides "with Regen Marketplace" in mobile to avoid cramping
- width tweaks to handle new text
- changes some instances of "Regen Registry" to "Regen Marketplace"
Note: In Sanity, we will also need to update the subheader to:
"Introducing Regen Marketplace, the place to buy, sell, and retire on-chain carbon and ecological assets."
---
I have...
your PR:
- If PR is a new feature: …
=> Feat/1334 Homepage copy

web-registry/src/pages/Buyers/Buyers.tsx
Closes: regen-network/regen-registry#1336
Filters out projects that do not have a handle or an onChainId (which are necessary for linking).
This helps us avoid displaying projects that are in the DB, but not yet finished.
---
I have...
your PR:
b. Create new branches for …
=> Fix/buyers  projects

web-registry/sanity-graphql.schema.json, web-registry/src/generated/sanity-graphql.tsx, web-registry/src/graphql/sanity/AllHomePage.graphql, web-registry/src/graphql/sanity/SEOFragment.graphql, web-registry/src/pages/Home/Home.tsx, web-www/src/pages/nct.tsx
Closes: https://github.com/regen-network/regen-registry/issues/1333
---
I have...
your PR:
```
git merge dev …
```
=> feat: add SEO for social links

web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
Closes: regen-network/regen-registry#1335
---
I have...
your PR:
```
git merge dev …
```
=> fix: reset selectedSellOrder when modal closes or submits

web-registry/src/components/templates/ProjectDetails/hooks/useGeojson.ts, web-registry/src/components/templates/ProjectDetails/hooks/useMedia.tsx, web-registry/src/pages/ProjectReview/ProjectReview.tsx, web-registry/src/pages/ProjectReview/ProjectReview.util.tsx
Closes: regen-network/regen-registry#1338
---
I have...
your PR:
```
git merge dev …
```
=> Fix - map with 1 photo

web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.styles.ts, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
Closes: regen-network/regen-registry#1337
---
I have...
your PR:
```
git merge dev …
```
=> feat: use ReactPlayer to display video, handle non-embed urls

web-www/src/pages/nct.tsx
fix: revert change to nctPage graphql
This fixes the failing builds for web-www by reverting a change to nctPage, where instead of using a fragment that is unavailable to the web-www graphql, it just uses the fields it previously used.
```
11:14:08 PM: web-www: success update schema - 0.035s
11:14:08 PM: web-www: success onPreExtractQueries - 0.003s
11:14:10 PM: web-www: error There was an error in your GraphQL query:
11:14:10 PM: web-www: The fragment "seoFields" does not exist.
11:14:10 PM: web-www:    6 | import {
11:14:10 PM: web-www:    7 |   BannerSection,
11:14:10 PM: web-www:    8 |   LedgerSection,
11:14:10 PM: web-www:    9 |   MarketplaceSection,
11:14:10 PM: web-www:   10 |   MediaSection,
11:14:10 PM: web-www:   11 |   OverviewSection,
11:14:10 PM: web-www:   12 | …
```
=> fix: revert change to nctPage graphql

web-components/src/utils/format.test.ts, web-registry/src/pages/Marketplace/Storefront/hooks/useBuySellOrderSubmit.tsx, web-registry/src/utils/number/format/format.test.ts
- buy confirmation modal round price
- add some more tests
---
I have...
your PR:
```
git merge dev
git …
```
=> fix: buy confirmation modal round price

web-registry/src/hooks/projects/useProjectsWithOrders.ts, web-registry/src/lib/coingecko.ts, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.types.ts, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx
- fix order price range computing with eeur/usdc ask denom
We're now getting EEUR/USDC prices from coingecko and using them to compute the correct price range in dollars.
---
I have...
your PR:
b. Create new branches for backports and merge `dev` (replace `<PR#>` with your PR …
=> fix: order price range computing with eeur/usdc ask denom

web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx
Closes: regen-network/regen-registry#1352
* add function to check if the price per ton in the project cards is displayed as a range or a single price (i.e. when the upper and lower limits of the range are equal)
---
I have...
your PR:
b. Create new branches for backports and …
=> Fix project card price display as single or range

netlify.toml, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx, web-registry/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-registry/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/index.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Projects/Projects.tsx
Closes: regen-network/regen-registry#1373
This PR adds the buy1 tracking event to the sticky nav buy button on the project page and credit class page. It also adds that event to the sell order table buy buttons.
Additionally this PR adds some additional metadata for the buy1 event that improves the experience for those looking at the analytics data.
---
I have...
your PR: …
=> fix: add buy1 tracking event to project page, credit class page and sell order buy buttons

web-components/src/components/header/components/UserMenuItem.tsx, web-components/src/components/tabs/IconTab.tsx, web-components/src/components/tabs/IconTabs.tsx, web-registry/src/App.test.tsx, web-registry/src/App.tsx, web-registry/src/components/atoms/AccountLink.tsx, web-registry/src/components/organisms/Portfolio.tsx, web-registry/src/features/ecocredit/CreateBatchBySteps/CreateBatchMultiStepForm/Result.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/features/marketplace/CreateSellOrderFlow/CreateSellOrderFlow.tsx, web-registry/src/index.tsx, web-registry/src/lib/block-explorer.ts, web-registry/src/pages/Admin/Admin.tsx, web-registry/src/pages/BatchDetails/BatchDetails.tsx, web-registry/src/pages/Dashboard/Dashboard.context.tsx, web-registry/src/pages/Dashboard/Dashboard.styles.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/Dashboard/MyCreditBatches/MyCreditBatches.tsx, web-registry/src/pages/Dashboard/MyCreditClasses/MyCreditClasses.tsx, web-registry/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.styles.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-registry/src/pages/EcocreditsByAccount/PortfolioTab/EcocreditsByAccount.PortfolioTab.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/routes.tsx
Closes: regen-network/regen-registry#1366
- add separate urls for the public and private profile page
- update `IconTabs` to handle tab with link and to support initial active tab
- use nested routes and `<Outlet />` component for both  public and private profiles to preserve the layout
- rename `App` to `routes` and clean it
---
I have...
your PR:
2. If your branch does …
=> feat: add separate urls for portfolio page and public profile

web-components/src/components/form/BasketTakeForm.tsx
Closes: regen-network/regen-registry#1371
---
I have...
your PR:
```
git merge dev …
```
=> feat: add tooltip for fixed retirement in Take from basket

web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
Closes: regen-network/regen-registry#1370
---
I have...
your PR:
```
git merge dev …
```
=> fix: retirement note label truncated

web-registry/src/pages/Dashboard/Dashboard.tsx
Closes: regen-network/regen-registry#1407
- Hides Bridge tab in dashboard, if chain-id is "regen-1" (mainnet).
- We will delete this feature flag when bridge feature is ready for release.
---
I have...
your PR:
b. Create new branches for backports and merge `dev` (replace …
=> chore: feature flag to temporarily hide Bridge tab in mainnet (regen-1)

web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
Closes: regen-network/regen-registry#1407
Hides Bridge tab in Account view, via feature flag
---
I have...
your PR:
```
git merge dev
git push …
```
=> chore: temporarily hide Bridge tab in account view

web-components/src/components/header/components/UserMenuItem.config.tsx, web-components/src/components/header/components/UserMenuItem.tsx
Closes: regen-network/regen-registry#1297
- Add Bridge link to user menu
---
I have...
your PR:
```
git merge dev …
```
=> feat: bridge user dropdown

web-registry/src/pages/Home/Home.tsx
Fix SVG used from credit class section on home page.
---
I have...
your PR:
```
git merge dev
git checkout …
```
=> fix: credit class bg image

netlify.toml, web-registry/.env.example, web-registry/src/index.tsx
Closes: regen-network/regen-registry#1340
This PR sets an environment variable to control which environments sentry will be used in. It sets the new environment variable in the `netlify.toml` only for the production environment. So this means Sentry will only be used in production.
---
I have...
your PR:
a. Pull latest `dev`, …
=> feat: use flag to set sentry to production environment only

netlify.toml, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-components/src/components/form/CreateSellOrderForm.tsx, web-components/src/components/form/CreditSendForm.tsx, web-components/src/components/header/components/UserMenuItem.tsx, web-registry/src/components/organisms/BridgableEcocreditsTable/BridgableEcocreditsTable.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx, web-registry/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-registry/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx, web-registry/src/components/organisms/WalletButton/WalletButton.tsx, web-registry/src/components/organisms/WalletButton/hooks/useConnectToWallet.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/hooks/useMsgClient.ts, web-registry/src/index.tsx, web-registry/src/lib/tracker/types.ts, web-registry/src/lib/tracker/useTracker.ts, web-registry/src/lib/wallet/hooks/useConnectWallet.tsx, web-registry/src/lib/wallet/wallet.tsx, web-registry/src/lib/wallet/wallet.utils.ts, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreateSellOrderSubmit.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditRetireSubmit.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditSendSubmit.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.normalizer.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.types.ts, web-registry/src/pages/Marketplace/Storefront/hooks/useBuySellOrderSubmit.tsx, web-registry/src/pages/Projects/Projects.tsx, web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx
Closes: https://github.com/regen-network/regen-registry/issues/1341
---
I have...
your PR:
```
git merge dev …
```
=> feat: Add requested metadata to buy, send, and sell events

web-components/src/components/tabs/IconTabs.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.Header.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
Closes: regen-network/regen-registry#1408
---
I have...
your PR:
```
git merge dev …
```
=> fix: spacing issue on user profile

web-components/src/components/tooltip/index.tsx
Closes: regen-network/regen-registry#1430
---
I have...
your PR:
```
git merge dev …
```
=> fix: tooltip arrow

web-registry/src/components/molecules/DenomLabel/DenomLabel.utils.ts, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx, web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.utils.tsx, web-registry/src/components/organisms/BuyCreditsModal/hooks/useFetchUserBalance.tsx, web-registry/src/components/organisms/BuyCreditsModal/hooks/useRefreshUserBalance.tsx, web-registry/src/config/allowedBaseDenoms.ts, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/lib/queries/react-query/cosmos/bank/getAllBalancesQuery/getAllBalancesQuery.constants.ts, web-registry/src/lib/queries/react-query/cosmos/bank/getAllBalancesQuery/getAllBalancesQuery.ts, web-registry/src/lib/queries/react-query/cosmos/bank/getAllBalancesQuery/getAllBalancesQuery.types.ts, web-registry/src/utils/string/capitalizeWord.ts
Closes: regen-network/regen-registry#1379
- check user balance in form validation for `BuyCreditsModal`
---
I have...
your PR:
```
git merge dev …
```
=> feat: check user balance in buy modal

web-registry/src/components/organisms/Bridge/Bridge.tsx, web-registry/src/components/organisms/Bridge/hooks/useActiveTab.ts, web-registry/src/features/marketplace/BridgeFlow/BridgeFlow.tsx, web-registry/src/pages/Dashboard/MyBridge/MyBridge.BridgableEcocreditsTable.tsx, web-registry/src/pages/Dashboard/MyBridge/MyBridge.BridgedEcocreditsTable.tsx, web-registry/src/pages/Dashboard/MyBridge/MyBridge.context.tsx, web-registry/src/pages/Dashboard/MyBridge/MyBridge.tsx, web-registry/src/pages/EcocreditsByAccount/BridgeTab/BridgeTab.tsx, web-registry/src/routes.tsx
Closes: regen-network/regen-registry#1438
---
I have...
your PR:
```
git merge dev …
```
=> Fix 1438 open bridged tab

web-registry/src/components/organisms/CreditSendForm/CreditSendForm.tsx
Closes: regen-network/regen-registry#1461
* Temporary validation rule added to the Send form in order to prevent sending ecocredits to the same address (sender and recipient must be different)
---
I have...
your PR:
b. Create new branches for backports and merge `dev` (replace …
=> fix: prevent sending credits to the same account

.github/mergify.yml, .github/workflows/main.yml
ref: https://regen-network.slack.com/archives/C01LX9E8QN8/p1669277313928079
https://docs.mergify.com/actions/backport/#using-labels-to-backport-pull-requests
This change will need to be on master to be effective.
---
I have...
your PR:
b. Create new branches for backports and …
=> chore: add mergify.yml

web-registry/src/components/organisms/BridgableEcocreditsTable/BridgableEcocreditsTable.tsx, web-registry/src/components/organisms/BridgedEcocreditsTable/BridgedEcocreditsTable.tsx, web-registry/src/components/organisms/EcocreditsTable.tsx
Closes: regen-network/regen-registry#1455
In ecocredits dashboard:
* portfolio ecocredits table 
* bridgable and bridged tables
---
I have...
your PR:
``` …
```
=> chore: update columns order

web-components/src/components/banner/index.tsx, web-registry/src/components/atoms/KeplrRoute.tsx, web-registry/src/config/contents.ts, web-registry/src/features/marketplace/BridgeFlow/BridgeFlow.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx
Closes: regen-network/regen-registry#1436
* It also adds a file for static `content` in the registry app's config folder, where the banner error message is first extracted.
---
I have...
your PR:
b. Create new branches for backports and merge `dev` (replace `<PR#>` with your PR …
=> fix: red banner displaced

web-registry/src/pages/ProjectEdit/ProjectEdit.tsx
Closes: regen-network/regen-registry#1418
---
I have...
your PR:
```
git merge dev …
```
=> chore: Remove settings page from project edit form 

web-components/src/components/cards/GettingStartedResourcesCard/GettingStartedResourcesCard.tsx, web-registry/src/components/organisms/BridgedEcocreditsTable/BridgedEcocreditsTable.constants.ts, web-registry/src/lib/bridge.ts, web-registry/src/types/ledger/ecocredit.ts
Closes: regen-network/regen-registry#1441
---
I have...
your PR:
```
git merge dev …
```
=> feat: 1441 pre pending status

web-registry/src/components/molecules/ProjectPageMetadata/ProjectPageMetadata.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx
Closes: regen-network/regen-registry#1442
- Moves Project Id out of the "Additional Info" section, and puts it at the top of the page for on-chain projects.
- If there is no `metadata[schema:name]`, uses the projectId for the header
---
I have...
your PR:
b. Create new branches …
=> feat: project id move

web-components/src/components/tooltip/index.tsx
Closes: regen-network/regen-registry#1470
* Created a wrapper in the custom tooltip base component to set the `enterTouchDelay` (mobile) property to `100 ms` (default is `700 ms`)
---
I have...
your PR:
b. Create new branches for backports and merge `dev` (replace `<PR#>` with …
=> fix: tooltips mobile to appear faster on tap

web-registry/src/pages/Projects/hooks/useProjects.tsx
Closes: regen-network/regen-registry#1481
- fix projects page pagination computing
---
I have...
your PR:
```
git merge dev …
```
=> fix: projects pagination

web-registry/src/components/templates/ProjectDetails/hooks/useMoreProjects.ts, web-registry/src/hooks/projects/useLastRandomProjects.ts, web-registry/src/hooks/projects/useProjectsWithOrders.ts
Closes: regen-network/regen-registry#1480
- prevent more projects from flickering
- reduce metadata requests when using random flag in`useProjectsWithOrders` hook
---
I have...
your PR:
``` …
```
=> fix: random projects flickering

web-registry/src/pages/Home/Home.FeaturedProjects.tsx
- fix discover projects link
---
I have...
your PR:
```
git merge dev …
```
=> fix: discover projects link

web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx, web-registry/src/pages/Home/Home.FeaturedProjects.tsx
Backport of hotfixes from v1.0.3 tag on `main`
---
I have...
your PR:
```
git merge dev …
```
=> chore: dev sync v1.0.3 tag

web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx, web-registry/src/pages/Home/Home.FeaturedProjects.tsx
Backport hotfixes from v1.0.3
---
I have...
your PR:
```
git merge dev …
```
=> Hambach backport v1.0.3

web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx, web-registry/src/pages/Home/Home.FeaturedProjects.tsx
Backport hotfixes from v1.0.3
---
I have...
your PR:
```
git merge dev …
```
=> Redwood backport v1.0.3

web-registry/src/pages/ProjectEdit/ProjectEdit.tsx
Closes: regen-network/regen-registry#1409
- change back to projects link, in edit form, to `/ecocredits/projects`
---
I have...
your PR:
```
git …
```
=> fix: back projects link

web-registry/package.json, yarn.lock
Bump `regen-js` to v0.5.0
---
I have...
your PR:
```
git merge dev
git checkout -b redwood-backport-<PR#> …
```
=> chore: bump regen-js

web-registry/src/lib/db/types/json-ld/credit-class-metadata.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetails.AdditionalInfo.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.styles.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.tsx
Closes: regen-network/regen-registry#1507
- Handle new metadata field `tokenizationSource` coming from tco2 metadata
- extract styles from `CreditClassDetailsSimple`
---
I have...
your PR:
``` …
```
=> feat: add support for tco2 metadata

web-registry/sanity-graphql.schema.json, web-registry/src/components/molecules/GettingStartedResourcesCardDefault/GettingStartedResourcesCardDefault.tsx, web-registry/src/generated/graphql.tsx, web-registry/src/generated/sanity-graphql.tsx, web-registry/src/graphql/sanity/AllBasketDetailsPage.graphql, web-registry/src/lib/queries/react-query/sanity/getAllBasketDetailsPageQuery/getAllBasketDetailsPageQuery.ts, web-registry/src/lib/queries/react-query/sanity/getAllBasketDetailsPageQuery/getAllBasketDetailsPageQuery.types.ts, web-registry/src/pages/BasketDetails/BasketDetails.tsx
Closes: regen-network/regen-registry#1466
Sanity PR: https://github.com/regen-network/regen-sanity/pull/24
- create reusable molecule for single resources card
- add resources card to `BasketDetails` page
---
I have...
your PR:
b. Create new branches for backports and merge …
=> feat: resources card to basket details page

web-registry/src/features/marketplace/CreateSellOrderFlow/hooks/useCreateSellOrderData.tsx, web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useFetchBaskets.tsx, web-registry/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts, web-registry/src/pages/EcocreditsByAccount/PortfolioTab/EcocreditsByAccount.PortfolioTab.tsx
Closes: regen-network/regen-registry#1513
- This page was still using old hooks to fetch data. It's now using react-query based hooks. 
---
I have...
your PR:
``` …
```
=> fix: public account page data fetching

web-registry/src/lib/block-explorer.ts, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.Header.tsx
Closes: regen-network/regen-registry#1505
- Use the explorer link on the public account page instead of the registry one
---
I have...
your PR:
```
git checkout -b hambach-backport-<PR#> …
```
=> fix: explorer link on public account page

web-registry/src/lib/bridge.ts, web-registry/src/lib/ecocredit/api.ts
Closes: regen-network/regen-web#1755
- update status endpoint from: `${apiUri}/regen/events/${hash}/status` to `${apiUri}/regen/events/${hash}`
- update fields in response: 
- `tx_hash`-> `regen_tx_hash`
- `destination_tx_hash` -> `evm_tx_hash`
---
I have...
your PR:
b. Create …
=> chore: update bridge event status endpoint

.eslintrc.js, web-registry/src/components/molecules/Form/hook/useZodForm.tsx, web-registry/src/components/organisms/CreditSendForm/CreditSendForm.schema.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-registry/src/components/templates/ProjectDetails/hooks/useIssuanceModal.ts, web-registry/src/components/templates/ProjectDetails/hooks/useOtherProjects.ts, web-registry/src/components/templates/ProjectDetails/hooks/useSeo.ts, web-registry/src/utils/mui/sxToArray.ts
Closes: regen-network/regen-registry#1536
Disable explicit return type eslint rule.
The reasoning is that most of the time typescript inference is good enough and sometimes we lose time figuring out complex types that can be inferred automatically.
---
I have...
your PR:
b. …
=> chore: disable explicit return type rule

web-registry/src/components/molecules/ProjectPageMetadata/ProjectPageMetadata.tsx, web-registry/src/components/molecules/ScrollableCodebox/ScrollableCodebox.stories.tsx, web-registry/src/components/organisms/CreditClassForms/CreditClass.mocks.ts, web-registry/src/lib/db/types/json-ld/credit-class-metadata.ts, web-registry/src/lib/db/types/json-ld/project-metadata.ts
ref: https://github.com/regen-network/regen-registry-standards/issues/35
---
I have...
your PR:
```
git merge dev …
```
=> chore: update project metadata `regen:offsetGenerationMethod` to be a list

.github/PULL_REQUEST_TEMPLATE.md, .github/mergify.yml, netlify.toml, web-registry/.env.example, web-registry/src/ledger.tsx, web-registry/src/lib/ecocredit/api.ts, web-registry/src/lib/ledger.ts
Closes: regen-network/regen-registry#1545
Remove code related to Hambach.
---
I have...
your PR:
```
git merge dev …
```
=> chore: remove hambach

web-components/src/components/cards/ProjectImpactCard.tsx, web-registry/src/components/organisms/ProjectImpactSection.tsx
Closes: regen-network/regen-registry#1547
Also fix the cards to have the same height on mobile, which wasn't the case:
---
I have...
your PR:
``` …
```
=> fix: text alignment on ProjectImpactCard

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-registry/CHANGELOG.md, web-registry/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json
Release dev sync v1.2.0
---
I have...
1.
I have...
=> Release dev sync v1.2.0

web-registry/public/_redirects, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx, web-registry/src/routes.tsx
ref: regen-network/regen-web#1786
---
I have...
your PR:
```
git merge dev …
```
=> feat: update /land-stewards to /project-developers and add redirect

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/lib/queries/react-query/ecocredit/marketplace/getSellOrdersExtendedQuery/getSellOrdersExtendedQuery.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts
Fix the computation price on the storefront page.
---
I have...
1.
I have...
=> fix: dev sync v1.2.1

web-components/src/components/footer/index.tsx, web-components/src/components/header/index.tsx, web-components/src/components/mobile-menu/index.tsx
ref: https://github.com/regen-network/web-www/pull/2#issuecomment-1448167324
---
I have...
1.
I have...
=> feat: backport recent changes from react-17 branch

web-components/src/components/cards/ProjectCard/ProjectCard.constants.ts, web-components/src/components/cards/ProjectCard/ProjectCard.constants.tsx, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-components/src/types/shared/buttonType.ts, web-registry/src/lib/queries/react-query/registry-server/graphql/getWalletByAddrQuery/getWalletByAddrQuery.ts, web-registry/src/lib/queries/react-query/registry-server/graphql/getWalletByAddrQuery/getWalletByAddrQuery.types.ts, web-registry/src/pages/Dashboard/MyProjects/MyProjects.constants.tsx, web-registry/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-registry/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx, web-registry/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByIdsWithOrders.tsx
Closes: regen-network/regen-registry#1410
- add edit button on all cards for `/ecocredits/projects`
- use project data whenever it is available
- use react-query for all page requests
---
I have...
1.
I have...
=> feat: edit project button

web-registry/src/pages/ProjectEdit/ProjectEdit.Denied.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.Nav.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.styles.ts, web-registry/src/pages/ProjectEdit/ProjectEdit.tsx
Closes: regen-network/regen-registry#1526
Add a project denied page when trying to edit a project for a non-admin user.
---
I have...
1. https://deploy-preview-1806--regen-registry.netlify.app/project-pages/C01-001/edit
I have...
=> feat: protect project edit page

web-registry/src/pages/LandStewards/LandStewards.tsx
Closes: regen-network/regen-registry#1566
Fix the start process button `onClick` by using `onBtnClick` util function.
---
I have...
1.
I have...
=> fix: footer link land stewards

web-registry/src/components/molecules/BatchTotalsGrid.tsx
ref: https://regen-network.slack.com/archives/C01LX9E8QN8/p1678353098390459?thread_ts=1678302081.598509&cid=C01LX9E8QN8
---
I have...
https://deploy-preview-1816--regen-registry.netlify.app/credit-batches/C52-001-20140701-20141231-001
I have...
=> fix: use 2 maximumFractionDigits for credits on batch details page

web-registry/src/components/molecules/ProjectPageMetadata/ProjectPageMetadata.tsx, web-registry/src/lib/db/types/json-ld/credit-class-metadata.ts, web-registry/src/lib/db/types/json-ld/methodology.ts, web-registry/src/lib/db/types/json-ld/toucan-project-metadata.ts, web-registry/src/lib/rdf/rdf.constants.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetails.AdditionalInfo.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.ApprovedMethodologies.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.utils.ts
Closes: regen-network/regen-registry#1570
---
I have...
Use https://deploy-preview-1817--regen-registry.netlify.app/credit-classes/C51 which has appropriate metadata to test these fixes
I have...
=> fix: Handle missing fields on TCO2 credit class page

web-registry/src/components/organisms/BuyCreditsModal/hooks/useFetchUserBalance.tsx
=> fix: enable balances query only if wallet addr available

netlify.toml
We've been using a new credit class on redwood for testing bridgeable credits. This PR should update the UI to support that.
---
I have...
1.
I have...
=> test: update test bridge credit class on netlify.toml

web-components/src/components/cards/ProjectTopCard.tsx, web-components/src/components/text-layouts/LabeledNumber.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
Closes: regen-network/regen-registry#1584
---
I have...
https://deploy-preview-1825--regen-registry.netlify.app/project/C52-001
I have...
=> fix: various UI issues on project page

netlify.toml
fix: update redwood bridge class
Note: 
- I accidentally merged this PR from Cory to `main`, it was supposed to go to `dev`.
- I've since reverted that change in the `main` branch.
- This puts it into dev where it was supposed to be
---
I have...
1.
I have...
=> fix: update redwood bridge class

netlify.toml
We've had to update bridge credit class again, and this PR will set the correct env var on dev.app.regen.network
---
I have...
1.
I have...
=> Clev/update redwood bridge credit class C56

web-registry/.env.example, web-registry/src/components/organisms/Portfolio.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx, web-registry/src/hooks/useQueryBaskets.ts, web-registry/src/lib/ledger.ts
Closes: regen-network/regen-registry#1497
---
I have...
1.
I have...
=> chore: re-enable NCT page in navigation and baskets on portfolio page

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/lib/db/api/metadata-graph.ts, web-registry/src/lib/rdf/rdf.compact.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx
**Important**: Do not merge from the Github UI. See release process document.
Syncs the dev branch with the latest v1.2.2 hotfix release
---
I have...
1.
I have...
=> Dev sync v1.2.2

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/lib/queries/react-query/coingecko/simplePrice/simplePriceQuery.ts, web-registry/src/lib/queries/react-query/coingecko/simplePrice/simplePriceQuery.types.ts, web-registry/src/lib/queries/react-query/ecocredit/marketplace/getSellOrdersExtendedQuery/getSellOrdersExtendedQuery.ts, web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts
Related fix: regen-network/regen-registry#1630
Syncs the dev branch with the latest v1.2.3 hotfix release
---
I have...
1.
I have...
=> Dev sync v1.2.3

web-registry/src/apollo.tsx, web-registry/src/hooks/projects/useProjectsWithOrders.ts, web-registry/src/lib/normalizers/projects/normalizeProjectsWithCreditClass.ts, web-registry/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts, web-registry/src/lib/normalizers/projects/normalizeProjectsWithOrderData.ts
Closes: regen-network/regen-registry#1626
Use credit class for default project card image.
---
I have...
1. https://deploy-preview-1835--regen-registry.netlify.app/
I have...
=> feat: use credit credit for default project image

web-registry/src/components/molecules/EcocreditsSection.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.SidebarBox.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx, web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.styles.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.tsx
Closes: regen-network/regen-registry#1578
---
I have...
https://deploy-preview-1830--regen-registry.netlify.app/credit-classes/C01
I have...
=> chore: Add image to credit class pages

web-components/src/utils/s3.ts
Closes: https://github.com/regen-network/regen-registry/issues/1636
---
I have...
1.
I have...
=> feat: include credentials files requests

web-registry/src/components/molecules/BatchTotalsGrid.tsx
Closes: regen-network/regen-web#1834
---
I have...
https://deploy-preview-1843--regen-registry.netlify.app/credit-batches/C56-002-20140701-20141231-001
https://deploy-preview-1843--regen-registry.netlify.app/credit-batches/C55-002-20170101-20170131-001
I have...
=> fix: credits rounding on credit batch page

web-registry/src/components/organisms/BasketsTable.tsx
Closes: #1849
Show fractional balances in basket table.
---
I have...
1. https://deploy-preview-1852--regen-registry.netlify.app/ecocredits/accounts/regen1l0ck43z80q7uzfd70qzsm9lggwvz3gdy774x30/portfolio
I have...
=> fix: basket fractional balance

web-registry/src/components/molecules/BatchMetadata/BatchMetadata.AdditionalInfo.tsx
Closes: #1847
---
I have...
https://deploy-preview-1854--regen-registry.netlify.app/credit-batches/C56-001-20170101-20170131-001
I have...
=> fix: display toucan vintage token id even when no toucanURI

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/apollo.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/Dashboard/Dashboard.utils.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-registry/src/pages/ProfileEdit/ProfileEdit.tsx, web-registry/src/pages/ProfileEdit/hooks/usePartyInfos.tsx, web-storybook/CHANGELOG.md, web-storybook/package.json
Dev sync of https://github.com/regen-network/regen-web/pull/1857
---
I have...
1.
I have...
=> Fix dev sync v1.4.0

web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
Closes: request from @erikalogie to remove this content:
---
I have...
1.
I have...
=> fix: remove profile header and account from public profile

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
Syncs: https://github.com/regen-network/regen-web/pull/1859
---
I have...
1.
I have...
=> Fix dev sync v1.4.1

web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/ProfileEdit/ProfileEdit.tsx
Closes: #1864
---
I have...
1.
I have...
=> fix: edit user profile on first connection

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/ProfileEdit/ProfileEdit.tsx
=> Fix dev sync v1.4.2

web-registry/src/components/organisms/BasketDetailsActionsBar/BasketDetailsActionsBar.constants.ts
Closes: regen-network/regen-registry#1624
With the launch of NCT on Osmosis we are now ready to update the link on the Buy NCT Button.  This code updates href constant to https://app.osmosis.zone/?from=REGEN&to=NCT
---
I have...
1.
I have...
=> chore: update buy_button_link to Osmosis Pool

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/BasketDetailsActionsBar/BasketDetailsActionsBar.constants.ts
Syncs v1.4.3
---
I have...
1.
I have...
=> Fix dev sync v1.4.3

web-components/src/components/sliders/ProjectMedia.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
Closes: 
regen-network/regen-registry#1641
regen-network/regen-registry#1111
- remove gallery photos from the ProjectDetails media header
- clean code related to using gallery photos
---
I have...
1. https://deploy-preview-1870--regen-registry.netlify.app/project/C01-001
I have...
=> feat: hide old gallery photos

netlify.toml, web-registry/src/components/organisms/BuyModalOptions/BuyModalOptions.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/lib/tracker/types.ts, web-registry/src/lib/tracker/useBuyModalOptionsTracker.ts, web-registry/src/pages/Projects/Projects.tsx
Closes: regen-network/regen-registry#1607
Sample of events from deploy preview:
---
I have...
1. Note-to-self: set `REACT_APP_ANALYTICS_ENABLED="true"` in deploy preview env's to test.
2. Go to the "Regen Marketplace [DEVELOPMENT]" property in https://analytics.google.com
3. Go to "Reports" => "Realtime" this is where you can observe analytics events
4. Go to the deploy preview: https://deploy-preview-1868--regen-registry.netlify.app/
5. Go to a project page or a project card and click "Buy"
6. Click "schedule" or "buy credits" in the modal
7. Observe the events in Step 3
_All items are required. Please add a note if the item is not applicable and …
=> feat: tracking for buyScheduleCall and buyKeplr events

web-registry/src/components/organisms/BasketOverview/BasketOverview.modals.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Marketplace/Storefront/hooks/useBuySellOrderSubmit.tsx, web-registry/src/pages/ProfileEdit/ProfileEdit.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.tsx
Closes: 
regen-network/regen-registry#1669
regen-network/regen-registry#1668
regen-network/regen-registry#1667
https://github.com/regen-network/regen-web/issues/1861
While investigating on regen-network/regen-registry#1654 I found various issues while rejecting transactions on different pages. The initial issue could only be reproduced when rejecting a transaction which is an expected behavior.
---
I have...
1. 1877: https://deploy-preview-1876--regen-registry.netlify.app/ecocredits/accounts/regen1rn2mn8p0j3kqgglf7kpn8eshymgy5sm8w4wmj4/portfolio
- profile info should be displayed correctly
2. 1667: …
=> fix: errors with rejected transactions and csrf party requests

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/BasketOverview/BasketOverview.modals.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-registry/src/pages/Dashboard/Dashboard.tsx, web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-registry/src/pages/Marketplace/Storefront/Storefront.tsx, web-registry/src/pages/Marketplace/Storefront/hooks/useBuySellOrderSubmit.tsx, web-registry/src/pages/ProfileEdit/ProfileEdit.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.tsx
Dev sync for: https://github.com/regen-network/regen-web/pull/1876
---
I have...
1.
I have...
=> chore: dev sync v1.4.4

web-registry/src/lib/wallet/hooks/useDetectKeplrMobileBrowser.tsx, web-registry/src/lib/wallet/wallet.tsx
Closes: #1862
Closes: #1863
---
I have...
1.
I have...
=> fix: login on keplr mobile

web-registry/src/lib/wallet/hooks/useConnectWallet.tsx, web-registry/src/lib/wallet/wallet.tsx
Ref: https://github.com/regen-network/regen-web/pull/1881#issuecomment-1522951766
---
I have...
1.
I have...
=> fix: set keplr mobile web on auto-connect wallet

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/lib/wallet/hooks/useConnectWallet.tsx, web-registry/src/lib/wallet/wallet.tsx
=> Fix dev sync v1.4.6

web-components/src/components/fixed-footer/SaveFooter.tsx, web-components/src/components/inputs/new/FieldFormControl/FieldFormControl.styles.ts, web-components/src/components/inputs/new/FieldFormControl/FieldFormControl.tsx, web-components/src/components/inputs/new/TextAreaField/TextAreaField.ChartCounter.tsx, web-components/src/components/inputs/new/TextAreaField/TextAreaField.tsx, web-registry/src/components/molecules/EditProjectPageFooter.tsx, web-registry/src/components/molecules/ProjectPageFooter.tsx, web-registry/src/components/organisms/DescriptionForm/DescriptionForm.constants.ts, web-registry/src/components/organisms/DescriptionForm/DescriptionForm.schema.ts, web-registry/src/components/organisms/DescriptionForm/DescriptionForm.tsx, web-registry/src/components/organisms/EditProfileForm/EditProfileForm.tsx, web-registry/src/components/organisms/index.ts, web-registry/src/hooks/projects/useProjectWithMetadata.ts, web-registry/src/lib/rdf/rdf.constants.ts, web-registry/src/lib/rdf/rdf.ts, web-registry/src/pages/Description/Description.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.tsx, web-registry/src/pages/ProjectEdit/ProjectEdit.types.ts, web-registry/src/pages/ProjectMetadata/ProjectMetadata.config.ts, web-registry/src/pages/ProjectReview/ProjectReview.tsx
Closes: regen-network/regen-registry#1610
Migrates `DescriptionForm` to react-hook-form
---
I have...
1. Login with our test account on https://deploy-preview-1880--regen-registry.netlify.app/
1. Create: https://deploy-preview-1880--regen-registry.netlify.app/project-pages/0932bcf4-e403-11ed-8a8d-0267c2be097b/description
1. Edit: https://deploy-preview-1880--regen-registry.netlify.app/project-pages/C01-012/edit/description
I have...
=> feat: Update description form to include story fields

web-components/src/components/cards/ProjectTopCard.tsx, web-components/src/components/user/UserAvatar.tsx, web-components/src/components/user/UserInfo.tsx, web-components/src/components/user/UserInfoWithTitle.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts
Closes: regen-network/regen-registry#1648
---
I have...
1. For a profile that does have info: https://deploy-preview-1886--regen-registry.netlify.app/project/C45-010
2. For a profile that has not filled anything out yet: https://deploy-preview-1886--regen-registry.netlify.app/project/C45-011
I have...
=> feat: link project page admin to profile

web-components/src/components/image-crop/index.tsx, web-components/src/components/inputs/new/Radio/Radio.constants.ts, web-components/src/components/inputs/new/Radio/Radio.stories.tsx, web-components/src/components/inputs/new/Radio/Radio.styles.ts, web-components/src/components/inputs/new/Radio/Radio.tsx, web-components/src/components/inputs/new/Radio/Radio.types.ts, web-components/src/components/inputs/new/RadioGroup/RadioGroup.stories.tsx, web-components/src/components/inputs/new/RadioGroup/RadioGroup.tsx, web-components/src/components/inputs/new/VideoInput/VideoInput.styles.ts, web-components/src/components/inputs/new/VideoInput/VideoInput.tsx, web-registry/src/components/organisms/MediaForm/MediaForm.constants.ts, web-registry/src/components/organisms/MediaForm/MediaForm.schema.tsx, web-registry/src/components/organisms/MediaForm/MediaForm.tsx, web-registry/src/components/organisms/MediaForm/MediaForm.types.ts, web-registry/src/components/organisms/MediaForm/MediaFormPhotos.tsx, web-registry/src/components/organisms/MediaForm/MediaFormStory.tsx, web-registry/src/components/organisms/MediaForm/index.ts, web-registry/src/lib/db/types/json-ld/project-metadata.ts, web-registry/src/lib/env.ts, web-registry/src/lib/rdf/rdf.constants.ts, web-registry/src/pages/Media/Media.tsx
Closes: regen-network/regen-registry#1672
Migrate inputs:
- VideoInput
- Radio
Add:
- story media form
---
I have...
1.
I have...
=> feat: add story media form

web-registry/package.json, yarn.lock
Closes: regen-network/regen-registry#1679
---
I have...
1.
I have...
=> chore: remove stripe dependency

web-registry/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.tsx
Closes: regen-network/regen-registry#1680
---
I have...
https://deploy-preview-1893--regen-registry.netlify.app/project/C02-018
I have...
=> fix: hide project tabs if no document or batch

web-registry/src/components/organisms/ProjectImpactSection/ProjectImpactSection.styles.ts, web-registry/src/components/organisms/ProjectImpactSection/ProjectImpactSection.tsx
Closes: regen-network/regen-registry#1681
Display impact cards container overflow.
---
I have...
1. https://deploy-preview-1892--regen-registry.netlify.app/project/C02-018
I have...
=> fix: impact cards container

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-registry/CHANGELOG.md, web-registry/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
Sync of v1.5.0 release
---
I have...
1.
I have...
=> chore: dev sync v1.5.0

web-registry/src/pages/Buyers/Buyers.EcologicalCreditCardsSection.tsx
Closes: regen-network/regen-registry#1688
---
I have...
1. Go to https://deploy-preview-1897--regen-registry.netlify.app/buyers and see:
I have...
=> fix: missing images on EcologicalCreditCard

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/pages/Buyers/Buyers.EcologicalCreditCardsSection.tsx
=> Fix dev sync v1.5.1

web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
Closes: regen-network/regen-registry#1696
---
I have...
1. https://deploy-preview-1900--regen-registry.netlify.app/project/C02-002
I have...
=> fix: issues with admin and project developer on project page

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/ProjectCards.tsx, web-registry/src/lib/queries/react-query/registry-server/graphql/getMoreProjectsQuery/getMoreProjectsQuery.ts, web-registry/src/lib/queries/react-query/registry-server/graphql/getMoreProjectsQuery/getMoreProjectsQuery.types.ts, web-registry/src/lib/rdf/rdf.constants.ts, web-registry/src/pages/CreditClassDetails/CreditClassDetailsWithContent/CreditClassDetailsWithContent.tsx
=> Fix dev sync v1.5.2

CHANGELOG.md, lerna.json, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
=> Fix dev sync v1.6.0

web-registry/src/lib/queries/react-query/ecocredit/getProjectsQuery/getProjectsQuery.constants.ts, web-registry/src/lib/queries/react-query/ecocredit/getProjectsQuery/getProjectsQuery.ts, web-registry/src/lib/queries/react-query/registry-server/graphql/getWalletByAddrQuery/getWalletByAddrQuery.ts, web-registry/src/lib/queries/react-query/registry-server/graphql/getWalletByAddrQuery/getWalletByAddrQuery.utils.ts, web-registry/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-registry/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx, web-registry/src/pages/ProjectReview/ProjectReview.tsx
Closes: regen-network/regen-registry#1675
clear cache for:
- daft project
- newly onchain project
---
I have...
1. https://deploy-preview-1909--regen-registry.netlify.app/ecocredits/projects
I have...
=> fix: clear cache for newly created projects

web-components/src/components/cards/ReviewCard/ReviewCard.Photo.tsx, web-registry/src/lib/rdf/rdf.constants.ts, web-registry/src/pages/ProjectReview/ProjectReview.constants.ts, web-registry/src/pages/ProjectReview/ProjectReview.tsx
Closes: regen-network/regen-registry#1673
Closes: regen-network/regen-registry#1704
Update review step with:
- gallery photos
- caption and credit for photos
- story media (image/video)
---
I have...
1. https://deploy-preview-1905--regen-registry.netlify.app/project-pages/0551d790-b68c-11ed-9317-0267c2be097b/review (on the shared account)
I have...
=> feat: update project review

web-components/src/components/header/components/UserMenuItem.Profile.tsx, web-components/src/components/header/components/UserMenuItem.types.ts, web-components/src/components/header/components/UserMenuItems.tsx, web-components/src/components/modal/add-wallet-modal/AddWalletModalSwitchWarning.constants.tsx, web-components/src/components/modal/add-wallet-modal/AddWalletModalSwitchWarning.stories.tsx, web-components/src/components/modal/add-wallet-modal/AddWalletModalSwitchWarning.tsx, web-components/src/components/modal/add-wallet-modal/AddWalletModalTemplate.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.AddWalletModalSwitchWarning.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-registry/src/components/organisms/RegistryLayout/RegistryLayout.tsx, web-registry/src/lib/atoms/modals.atoms.ts
Closes: regen-network/regen-registry#1691
- add a modal to warn the user to switch profile in Keplr when clicking on an item in the dropdown
---
I have...
1. https://deploy-preview-1916--regen-registry.netlify.app/
I have...
=> feat: add profile switch warning modal

web-components/src/components/cards/ProjectTopCard.tsx, web-registry/graphql.schema.json, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-registry/src/generated/graphql.tsx, web-registry/src/graphql/ProjectFragment.graphql, web-registry/src/lib/db/types/json-ld/project-metadata.ts
Closes: regen-network/regen-registry#1600
---
I have...
https://deploy-preview-1915--regen-registry.netlify.app/project/C45-008
I have...
=> feat: add verifier to project page

web-registry/src/components/organisms/RolesForm/RolesForm.schema.ts, web-registry/src/components/organisms/RolesForm/RolesForm.tsx, web-registry/src/generated/graphql.tsx, web-registry/src/graphql/ProjectById.graphql, web-registry/src/pages/Roles/Roles.tsx, web-registry/src/pages/Roles/Roles.utils.ts, web-registry/src/pages/Roles/hooks/useRolesSubmit.tsx
Closes: regen-network/regen-registry#1604
---
I have...
Testable from netlify deploy previews once merged into [feat-1504-project-roles-profiles](https://github.com/regen-network/regen-web/tree/feat-1504-project-roles-profiles)
I have...
=> feat: add verifier to project roles form

web-registry/src/components/molecules/ProjectPageMetadata/ProjectPageMetadata.constants.ts, web-registry/src/components/molecules/ProjectPageMetadata/ProjectPageMetadata.tsx, web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-registry/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.config.tsx, web-registry/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.types.ts
Closes: regen-network/regen-registry#1717
- move additional info and the project id section to the project table
- add a tooltip to the project id
- add helper text
---
I have...
1. https://deploy-preview-1937--regen-registry.netlify.app/project/C02-002
I have...
=> feat: move additional info section to table

web-components/src/components/cards/CreditClassCard/CreditClassCard.tsx
Closes: regen-network/regen-registry#1741
- Truncate credit class card to 3 lines
---
I have...
1.
I have...
=> feat: truncate credit class card to 3 lines

web-registry/src/components/templates/ProjectDetails/tables/documentation/ProjectDetails.Documentation.tsx
Closes: regen-network/regen-registry#1746
- wire button link in documentation table
---
I have...
1.
I have...
=> fix: add missing document link

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-components/src/components/image/index.tsx, web-registry/CHANGELOG.md, web-registry/package.json, web-registry/src/components/organisms/MediaForm/MediaFormPhotos.tsx, web-registry/src/components/organisms/MediaForm/MediaFormStory.tsx, web-registry/src/components/organisms/ProjectStorySection/ProjectStorySection.tsx, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
Closes: regen-network/regen-registry#1754
---
I have...
1.
I have...
=> fix: dev sync v1.8.2

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-registry/CHANGELOG.md, web-registry/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
=> chore: dev sync v1.10.0

web-www/components/organisms/MarketingNav/MarketingNav.config.ts
Closes: #1944
---
I have...
https://deploy-preview-1981--regen-website.netlify.app/
I have...
=> chore: remove NCT and project developers link from website navigation

web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx
Closes: https://github.com/regen-network/regen-web/issues/1967
---
I have...
1. https://deploy-preview-1986--regen-registry.netlify.app/credit-classes/MEC01 vs https://dev.app.regen.network/credit-classes/MEC01
2. https://deploy-preview-1986--regen-registry.netlify.app/credit-classes/C01 vs https://dev.app.regen.network/credit-classes/C01
I have...
=> fix: credit class admin link on credit class page

web-components/src/components/organisms/ImpactTags/ImpactTags.tsx
Closes: regen-network/regen-registry#1762
---
I have...
https://deploy-preview-1993--regen-registry.netlify.app/project/C01-001
I have...
=> fix: ImpactTags width on project page

web-registry/src/components/templates/ProjectDetails/ProjectDetails.Stakeholders.tsx
Closes: #1995
---
I have...
1. Confirm Lato font is being used on project pages in project stakeholder section
- https://deploy-preview-2001--regen-registry.netlify.app/project/C01-001
I have...
=> fix: incorrect font for project stakeholders

web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts
Closes: regen-network/regen-web#1992
---
I have...
1. Update project metadata to include certifications and no ratings and then confirm title "certifications"
2. Update project metadata to include ratings and no certifications and then confirm title "ratings"
3. Update project metadata to include both certifications and ratings and then confirm title "certifications & ratings"
4. Update project metadata to not include certifications and ratings and then confirm no title and section
I …
=> fix: project certification and ratings title

web-components/src/components/read-more/truncate.ts
Closes: #1958
---
I have...
https://deploy-preview-1994--regen-registry.netlify.app/project/C01-020
I have...
=> fix: truncate function in ReadMore component

.prettierignore, web-components/package.json, web-registry/.prettierrc.js, web-registry/package.json, web-registry/src/auth0.ts, web-www/package.json
Closes: https://github.com/regen-network/regen-web/issues/2008
---
I have...
1.
I have...
=> fix: yarn format-and-fix to ignore generated code

web-components/src/components/footer/footer-new.tsx, web-components/src/components/footer/index.tsx, web-components/src/components/party/party.stories.tsx, web-registry/src/mocks/mock.json, web-registry/src/pages/Buyers/Buyers.tsx, web-registry/src/pages/Home/Home.tsx, web-registry/src/pages/LandStewards/LandStewards.tsx
Part of: regen-network/regen-registry#1456
---
I have...
1. Confirm updated company title in footer of website and application
- https://deploy-preview-2002--regen-website.netlify.app/
- https://deploy-preview-2002--regen-registry.netlify.app/
I have...
=> chore: update company title from inc to pbc

web-www/next.config.js
Closes: https://github.com/regen-network/regen-web/issues/1956
---
I have...
1.
I have...
=> fix: add redirect for /team to homepage

web-components/src/components/cards/MediaCard.tsx
Closes: regen-network/regen-registry#1647
---
I have...
Check out project cards on https://deploy-preview-2014--regen-registry.netlify.app/ or https://deploy-preview-2014--regen-registry.netlify.app/projects/1
I have...
=> feat: Change project titles on project cards so that they have two lines

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-registry/CHANGELOG.md, web-registry/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
=> Dev sync v1.11.0

web-marketplace/src/pages/Projects/Projects.CommunityFilter.tsx, web-www/components/organisms/MarketingNav/MarketingNav.config.ts, web-www/components/templates/Layout/Layout.config.ts, web-www/components/templates/home/Climate/Home.Climate.tsx
Closes: #2021
This pull request updates the registry link throughout the website and marketplace.
---
I have...
1. Search code for any instance of the deprecated notion page for the registry
2. Check registry links in selected locations of the website and application
I have...
=> chore: update regen registry link

web-components/src/components/cards/CreditClassCard/CreditClassCard.tsx, web-components/src/components/cards/ImageActionCard.tsx, web-components/src/components/cards/MediaCard.Image.tsx, web-components/src/components/cards/MediaCard.tsx, web-components/src/components/cards/ProjectCard/ProjectCard.ImageChildren.tsx, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-components/src/components/cards/card.stories.tsx, web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.types.ts, web-components/src/components/user/UserInfoCard.tsx, web-marketplace/sanity-graphql.schema.json, web-marketplace/src/components/organisms/CreditClassCards.tsx, web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.CreditClassCard.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/generated/sanity-graphql.tsx, web-marketplace/src/graphql/sanity/EcologicalCreditCardFragment.graphql, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithCreditClass.ts, web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts, web-marketplace/src/pages/Buyers/Buyers.EcologicalCreditCardsSection.tsx, web-marketplace/src/pages/Buyers/hooks/useFetchProjectsByIds.ts, web-marketplace/src/pages/Buyers/normalizers/normalizeEcologicalCreditCards.ts, web-marketplace/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByIdsWithOrders.tsx, web-marketplace/src/pages/Home/Home.tsx, web-marketplace/src/pages/Home/hooks/useCreditClasses.ts, web-marketplace/src/pages/Projects/Projects.tsx
Closes: regen-network/rnd-dev-team#1653
Sanity PR: https://github.com/regen-network/regen-sanity/pull/46
Add program info to:
- Project Card
- Credit Class Card
- Featured Card
- Ecological Credit Card
---
I have...
1. Home: https://deploy-preview-2015--regen-registry.netlify.app/
2. Project: https://deploy-preview-2015--regen-registry.netlify.app/project/C01-001
3. Buyers: https://deploy-preview-2015--regen-registry.netlify.app/buyers
I have...
=> feat: add program registry to cards

web-components/src/components/cards/CreditClassCard/CreditClassCard.tsx
Closes: regen-network/rnd-dev-team#1767
- stack generation method items in credit class card
---
I have...
1. https://deploy-preview-2029--regen-marketplace.netlify.app/
I have...
=> feat: stack credit class card items

web-components/src/components/molecules/RoundLogoItemsList/RoundLogoItemsList.tsx, web-components/src/components/organisms/CollapseList/CollapseList.constants.ts, web-components/src/components/organisms/CollapseList/CollapseList.tsx, web-components/src/components/organisms/ImpactTags/ImpactTags.tsx, web-components/src/components/organisms/ProjectTags/ProjectTags.tsx, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.types.ts, web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.tsx, web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.types.ts, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.styles.ts, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/TableTabs.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Stakeholders.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.tsx, web-marketplace/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.types.ts
Closes: regen-network/regen-registry#1770
- consistent spacing in the main and side columns on the project page.
- swap story and details section
---
I have...
1. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C02-002
2. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C02-009
3. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C01-001
I have...
=> feat: adjust spacing project page

web-components/src/components/organisms/CardsGridContainer/CardsGridContainer.tsx, web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.Projects.tsx, yarn.lock
- Display community projects on the credit class page.
- Fix projects cards alignments with 2 cards
---
I have...
1.
I have...
=> feat: display community projects on credit class page

web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormTemplate.constants.ts, web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormTemplate.tsx
Closes: regen-network/rnd-dev-team#1525
- redirect onchain project to edit flow
---
I have...
1. https://deploy-preview-2050--regen-marketplace.netlify.app/project-pages/02c8c412-4331-11ed-80fc-0267c2be097b/basic-info
I have...
=> fix: redirect onchain project to edit flow

web-www/next.config.js
Closes: https://github.com/regen-network/regen-web/issues/2053
---
I have...
1. Go to https://deploy-preview-2063--regen-website.netlify.app/nct
I have...
=> fix: redirect for nct page

package.json, yarn.lock
Reverts regen-network/regen-web#2058
=> fix: revert "fix: yarn lock"

web-marketplace/src/components/organisms/ProjectMetadataForm/ProjectMetadataForm.tsx
Closes: #2036
- fix project creation metadata wording
---
I have...
1.
I have...
=> fix: project creation metadata wording

web-www/pages/token.tsx
Closes: regen-network/regen-registry#1766
---
I have...
Inspect https://deploy-preview-2068--regen-website.netlify.app/token header and verify `noindex` is defined for `robots` meta
I have...
=> chore: add noindex to token page seo

web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx
Closes: #2047
---
I have...
1. Open: https://deploy-preview-2062--regen-marketplace.netlify.app/
2. Login with an account that is a credit class issuer (i.e. the regen web team testing account regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46)
3. Create a project from my portfolio projects tab
4. Observe creation without any issue
I have...
=> fix: clear cache for getProjectById after select credit class step

web-marketplace/src/pages/Projects/Projects.CommunityFilter.tsx, web-marketplace/src/pages/Projects/Projects.SideFilter.tsx, web-marketplace/src/pages/Projects/Projects.types.ts, web-marketplace/src/pages/Projects/Projects.utils.tsx
Closes: regen-network/regen-registry#1765
---
I have...
Go to https://deploy-preview-2065--regen-marketplace.netlify.app/projects/1 and apply some filters.
Check that the events are appearing on https://analytics.google.com/analytics/web/?authuser=1#/p340668480/realtime/overview?params=_u..nav%3Dmaui%26_u.dateOption%3Dtoday%26_u.comparisonOption%3Ddisabled&collectionId=life-cycle
I have...
=> feat: add tracking events for filterPermissionlessCredits and filterCreditClass

web-marketplace/src/components/organisms/Stakeholders/Stakeholders.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Stakeholders.tsx, web-marketplace/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.Stakeholders.tsx
Closes: regen-network/regen-registry#1773
Refactoring using a single `Stakeholders` component.
---
I have...
https://deploy-preview-2070--regen-marketplace.netlify.app/project/KSH01-001
I have...
=> fix: entities spacing on project and credit class page

web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.MoreProjects.tsx, web-marketplace/src/components/templates/ProjectDetails/hooks/useMoreProjects.ts, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/pages/Home/Home.tsx, web-marketplace/src/pages/Home/hooks/useCreditClasses.ts, web-marketplace/src/pages/Home/hooks/useFeaturedProjects.ts, web-marketplace/src/pages/Projects/Projects.tsx, web-marketplace/src/pages/Projects/hooks/useFetchCreditClasses.tsx
Closes: regen-network/regen-registry#1777
Also fixes credit classes loading on marketplace homepage.
`MyProjects` fixed as part of https://github.com/regen-network/regen-web/pull/2060
---
I have...
https://deploy-preview-2079--regen-marketplace.netlify.app/ Featured projects
https://deploy-preview-2079--regen-marketplace.netlify.app/projects/1
https://deploy-preview-2079--regen-marketplace.netlify.app/project/C01-007 (scrolling to More projects section right away)
I have...
=> fix: project cards loading

web-marketplace/src/components/molecules/ProjectPageFooter.tsx, web-marketplace/src/pages/ProjectCreate/ProjectCreate.constants.ts, web-marketplace/src/pages/ProjectCreate/ProjectCreate.utils.ts
Closes: regen-network/regen-registry#955
- compute progress percentage on project creation
---
I have...
1. https://deploy-preview-2082--regen-marketplace.netlify.app/project-pages/3060b6b6-4cbb-11ee-961a-0267c2be097b/basic-info
I have...
=> feat: add percentage on project creation

web-components/src/components/cards/ProjectImpactCard/ProjectImpactCard.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/lib/db/types/json-ld/project-metadata.ts, web-marketplace/src/lib/rdf/rdf.constants.ts, web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.utils.ts, web-marketplace/src/pages/CreditClassDetails/hooks/useImpact.ts
Closes: regen-network/regen-registry#1738
- handle project-specific impact description
---
I have...
1. https://deploy-preview-2067--regen-marketplace.netlify.app/project/C01-001
I have...
=> feat: add project impact description

web-components/src/components/cards/MediaCard.tsx
Closes: regen-network/regen-registry#1785
- fix image card blinking
This is an issue we previously had in the past and fixed but recent changes break that fix, here's a detailed explanation:
The root issue here is that `CardMedia` from `MUI` does not accept directly a react component as prop `component: () => JSX.Element`: https://github.com/regen-network/regen-web/blob/a3e471a95eb1f7b3e3f920807cd446ee612e3c0e/web-components/src/components/cards/MediaCard.tsx#L96
For this reason, we previously added a useCallback around the `MediaCardImage` component and prevent blinking from the image with rerenders: https://github.com/regen-network/regen-web/blob/a3e471a95eb1f7b3e3f920807cd446ee612e3c0e/web-components/src/components/cards/MediaCard.tsx#L66-L78
However we recently added a children prop …
=> fix: project card blinking

web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
Closes: regen-network/regen-registry#1790
---
I have...
https://deploy-preview-2103--regen-marketplace.netlify.app/projects/1
I have...
=> fix: projects page reloading on buy

web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/ProjectFragment.graphql, web-marketplace/src/pages/Dashboard/Dashboard.tsx, web-marketplace/src/pages/Dashboard/Dashboard.utils.tsx, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-marketplace/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByAdmin.tsx, web-marketplace/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-marketplace/src/pages/EcocreditsByAccount/PortfolioTab/EcocreditsByAccount.PortfolioTab.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ ProjectsTab.constants.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.constants.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.types.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.utils.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/hooks/useFetchProjectsWithOrders.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/index.ts, web-marketplace/src/pages/EcocreditsByAccount/hooks/useProfileData.tsx, web-marketplace/src/routes.tsx
Closes: regen-network/regen-web#2075
Display on-chain an approved off-chain projects on public user profile.
---
I have...
1. https://deploy-preview-2099--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/projects
I have...
=> feat: display user projects on public profile

web-www/components/templates/buyers/Buyers.FeaturedProjectsSection.tsx
Fix buyers' page feature projects card link.
---
I have...
1.
I have...
=> fix: buyers page links

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/components/templates/buyers/Buyers.FeaturedProjectsSection.tsx, web-www/package-lock.json, web-www/package.json
Dev sync for v1.12.1
---
I have...
1.
I have...
=> fix: dev sync v1.12.1

docs/adding-denom.md, web-marketplace/src/config/allowedBaseDenoms.ts, web-marketplace/src/lib/coingecko.ts, web-marketplace/src/lib/queries/react-query/ecocredit/marketplace/getSellOrdersExtendedQuery/getSellOrdersExtendedQuery.ts, web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.tsx, web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.utils.ts, web-marketplace/src/pages/Marketplace/Storefront/Storefront.normalizer.ts, web-marketplace/src/pages/Marketplace/Storefront/Storefront.utils.ts, web-marketplace/src/pages/Projects/hooks/useProjectsSellOrders.types.ts
Closes: regen-network/rnd-dev-team#1709
- refactor denom handling to make it easier to add new denom
- add some documentation
---
I have...
1.
I have...
=> feat: refactor denom handling and add documentation

web-marketplace/src/pages/Marketplace/Storefront/Storefront.tsx
Closes: #2133
---
I have...
1. https://deploy-preview-2133--regen-marketplace.netlify.app/storefront
2. Try to log in but do not approve the sign arbitrary transaction
3. Click on the buy button for one of the sell orders
5. You should see a popup that prompts to login with keplr (this is currently how it works, but I wonder if we should display the buy actions modal instead similar to what we do with the "buy ecocredits" button elsewhere in the app cc/ @erikalogie )
I have...
=> fix: update Storefront actions using isConnected state

.nvmrc
Closes: regen-network/regen-registry#1803
Using latest LTS version, ie node 18.
---
I have...
1.
I have...
=> chore: use node latest lts

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
Release dev sync v1.13.0
---
I have...
1.
I have...
=> Release dev sync v1.13.0

web-marketplace/graphql.schema.json, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/AllProjects.graphql, web-marketplace/src/pages/Projects/hooks/useOffChainProjects.tsx
=> fix: show only approved off chain projects on projects page

web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.Item.tsx, web-components/src/components/header/components/UserMenuItems.mock.tsx, web-components/src/components/mobile-menu/index.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx, web-marketplace/src/hooks/useQueryIsClassAdmin.ts, web-marketplace/src/lib/queries/react-query/ecocredit/getClassesByAdminQuery/getClassesByAdminQuery.constants.ts, web-marketplace/src/lib/queries/react-query/ecocredit/getClassesByAdminQuery/getClassesByAdminQuery.ts, web-marketplace/src/lib/queries/react-query/ecocredit/getClassesByAdminQuery/getClassesByAdminQuery.types.ts, web-marketplace/src/pages/Dashboard/Dashboard.constants.tsx, web-marketplace/src/pages/Dashboard/Dashboard.tsx, web-marketplace/src/pages/Dashboard/MyCreditClasses/MyCreditClasses.tsx, web-marketplace/src/pages/Dashboard/hooks/useProfileItems.tsx
Closes: #2138
---
I have...
Login from https://deploy-preview-2146--regen-marketplace.netlify.app/ using an account that is an issuer and/or is a project admin.
I have...
=> feat: add projects and batches to user account dropdown

web-marketplace/src/components/organisms/EditProfileForm/EditProfileForm.tsx, web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx
Closes: regen-network/rnd-dev-team#1592
- display warning modal, with draft changes, on profile edit
---
I have...
1. https://deploy-preview-2144--regen-marketplace.netlify.app/profile/edit
I have...
=> feat: add warning modal on profile edit

web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-marketplace/src/components/templates/ProjectDetails/tables/ProjectDetails.TableTabs.tsx
Closes: #2117
---
I have...
- off chain published project: https://deploy-preview-2153--regen-marketplace.netlify.app/project/a1fbc990-60fd-11ee-b6eb-0267c2be097b
- also make sure existing on chain project pages are unchanged
I have...
=> feat: update project page for off-chain projects

web-marketplace/src/routes.tsx
Closes: #2143 
---
I have...
https://deploy-preview-2162--regen-marketplace.netlify.app/profile
https://deploy-preview-2162--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46
I have...
=> fix: use portfolio as profile index route

web-components/src/components/section/OnBoardingSection.tsx, web-components/src/components/section/index.tsx, web-marketplace/src/lib/rdf/rdf.ts, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.Grid.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.OffchainCard.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.config.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx
Closes: #2160
- add create project without a credit class option
---
I have...
1. https://deploy-preview-2170--regen-marketplace.netlify.app/project-pages/b0421740-6687-11ee-9bde-0267c2be097b/choose-credit-class
I have...
=> feat: add create project without credit class option

web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/AllProjects.graphql, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts, web-marketplace/src/lib/queries/react-query/registry-server/graphql/getAllProjectsQuery/getAllProjectsQuery.ts, web-marketplace/src/lib/queries/react-query/registry-server/graphql/getProjectByIdQuery/getProjectByIdQuery.ts, web-marketplace/src/lib/rdf/rdf.compact.ts, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.types.tsx, web-marketplace/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByAdmin.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.types.tsx, web-marketplace/src/pages/Projects/Projects.tsx, web-marketplace/src/pages/Projects/Projects.types.ts, web-marketplace/src/pages/Projects/hooks/useOffChainProjects.tsx, web-marketplace/src/pages/Projects/utils/getCreditsTooltip.ts
Closes: regen-network/rnd-dev-team#1808
---
I have...
Go to https://deploy-preview-2165--regen-marketplace.netlify.app/projects, then show off chain projects and go to the last page to check them out.
Project card component: https://deploy-preview-2165--regen-storybook.netlify.app/?path=/story/cards--project-card
I have...
=> fix: offchain project cards on /projects page

web-marketplace/src/hooks/useQueryIfCreditClassCreator.ts, web-marketplace/src/hooks/useQueryIsIssuer.ts, web-marketplace/src/hooks/useQueryIsProjectAdmin.ts, web-marketplace/src/pages/CreateCreditClass/CreateCreditClass.tsx, web-marketplace/src/pages/Dashboard/MyCreditBatches/MyCreditBatches.Table.tsx, web-marketplace/src/pages/Dashboard/MyCreditBatches/MyCreditBatches.tsx, web-marketplace/src/pages/Dashboard/hooks/useProfileItems.tsx, web-marketplace/src/pages/EcocreditsByAccount/CreditBatchesTab/CreditBatchesTab.constants.ts, web-marketplace/src/pages/EcocreditsByAccount/CreditBatchesTab/CreditBatchesTab.tsx, web-marketplace/src/pages/EcocreditsByAccount/CreditClassTab/CreditClassTab.tsx, web-marketplace/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx, web-marketplace/src/routes.tsx
Closes: regen-network/rnd-dev-team#1293
---
I have...
1. https://deploy-preview-2141--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
I have...
=> feat: display all tabs on public profile

web-www/pages/_document.tsx, web-www/public/regenie.js
This adds a chat bot named Regenie to www.regen.network powered by [Botsonic](https://writesonic.com/botsonic). The bot is trained with data from www.regen.network, registry.regen.network, docs.regen.network and guides.regen.network and is there to help our users and prospective users learn about Regen Network, Registry, Marketplace, Ledger, etc.
---
I have...
1.
I have...
=> feat: add regenie chat bot

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync v1.14.0
---
I have...
1.
I have...
=> chore: dev sync v1.14.0

web-marketplace/src/apollo.tsx, web-marketplace/src/lib/queries/react-query/registry-server/getCsrfTokenQuery/getCsrfTokenQuery.constants.ts, web-marketplace/src/lib/queries/react-query/registry-server/getCsrfTokenQuery/getCsrfTokenQuery.ts
Closes: regen-network/regen-web#2085
As described [here](https://github.com/regen-network/regen-web/issues/2085#issuecomment-1770436847) the issue we had about `csrf` token sometimes getting invalid during a user session was because of multi-tab usage.
In order to fix this PR adds a new `errorLink` to the Apollo client that intercepts network error that contains `status code 403`, refetch the `csrf` token in that case, and replays the failed request intercepted. This should ensure that multi-tab usage works as expected.
---
I have...
1. Open this page in 2 tabs: https://deploy-preview-2196--regen-marketplace.netlify.app/project-pages/C45-010/edit/medi …
=> fix: csrf token refetch

web-components/.eslintrc.js, web-components/src/components/modal/keplr-wallet-connect-modal/KeplrWalletConnectModal.constants.ts, web-components/src/components/modal/keplr-wallet-connect-modal/KeplrWalletConnectModal.stories.tsx, web-components/src/components/modal/keplr-wallet-connect-modal/KeplrWalletConnectModal.tsx
UI for: regen-network/regen-web#2159
- add UI for web2 users trying to do transactions
---
I have...
1.
I have...
=> feat: add KeplrWalletConnectModal

web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.constants.ts, web-marketplace/src/pages/CreditClassDetails/CreditClassDetails.tsx
Closes: regen-network/rnd-dev-team#1813
- use sanity for book call link on credit class details
The book call link was also updated on sanity.
---
I have...
1.
I have...
=> feat: change schedule call link

web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx
Closes: #2207
---
I have...
Check that the buy button is in the footer of https://deploy-preview-2208--regen-marketplace.netlify.app/credit-classes/C01 or any other credit class page with some sell orders and test it works as expected.
I have...
=> fix: buy button on credit class page

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx
dev sync v1.14.1
---
I have...
1.
I have...
=> chore: dev sync v1.14.1

web-marketplace/src/lib/atoms/projects.atoms.ts, web-marketplace/src/pages/Projects/Projects.CommunityFilter.tsx, web-marketplace/src/pages/Projects/Projects.OffChainFilter.tsx, web-marketplace/src/pages/Projects/Projects.SideFilter.tsx, web-marketplace/src/pages/Projects/Projects.tsx
Closes: regen-network/rnd-dev-team#1823
- persist projects filters
---
I have...
1. https://deploy-preview-2215--regen-marketplace.netlify.app/projects/1
I have...
=> fix: persist projects filters

web-marketplace/graphql.schema.json, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/AccountById.graphql, web-marketplace/src/lib/auth/auth.tsx, web-marketplace/src/lib/queries/react-query/registry-server/getAccounts/getAccountsQuery.types.ts, web-marketplace/src/lib/wallet/hooks/useLogin.tsx, web-marketplace/src/lib/wallet/hooks/useLogout.tsx, web-marketplace/src/lib/wallet/wallet.utils.ts, web-marketplace/src/pages/ProfileEdit/ProfileEdit.Settings.tsx, web-marketplace/src/pages/ProfileEdit/hooks/useConnectWalletToAccount.tsx
Closes: #2197
Also update code to use /wallet-auth instead of /web3-auth server route per https://github.com/regen-network/regen-server/pull/411#discussion_r1392896089
---
I have...
1.
I have...
=> feat: use private account info

web-components/src/components/modal/EmailConfirmationModal/EmailConfirmationModal.tsx, web-marketplace/src/components/organisms/LoginButton/LoginButton.constants.ts, web-marketplace/src/components/organisms/LoginButton/LoginButton.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/onLoginPostData.ts, web-marketplace/src/components/organisms/LoginButton/hooks/useEmailConfirmationData.tsx, web-marketplace/src/components/organisms/LoginButton/utils/getEmailModalError.tsx, web-marketplace/src/utils/fetch/postData.ts, web-marketplace/tailwind.config.js
Closes: regen-network/regen-web#2155
Wire email passcode strategy.
---
I have...
1. https://deploy-preview-2218--regen-marketplace.netlify.app/
I have...
=> feat: wire email confirmation code

web-components/src/components/header/Header.stories.ExtraComponent.tsx, web-components/src/components/header/components/UserMenuItem.Profile.tsx, web-components/src/components/header/components/UserMenuItem.types.ts, web-components/src/components/header/components/UserMenuItems.tsx, web-marketplace/src/components/organisms/LoginButton/LoginButton.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useLoginData.tsx, web-marketplace/src/components/organisms/LoginFlow/LoginFlow.tsx, web-marketplace/src/components/organisms/LoginFlow/hooks/useEmailConfirmationData.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/components/organisms/RegistryLayout/hooks/useOnProfileClick.tsx, web-marketplace/src/lib/block-explorer.ts, web-marketplace/src/lib/wallet/hooks/useConnectWallet.tsx, web-marketplace/src/lib/wallet/hooks/useOnAccountChange.tsx, web-marketplace/src/lib/wallet/wallet.tsx, web-marketplace/src/lib/wallet/wallet.utils.ts, web-marketplace/src/pages/Dashboard/Dashboard.tsx, web-marketplace/src/pages/Dashboard/Dashboard.utils.tsx
Closes: #2193
---
I have...
From https://deploy-preview-2220--regen-marketplace.netlify.app/, test the following use cases:
1. Log in and click "+ add account" from the user dropdown to see the different methods for adding an account. This will automatically add the account to the current list of authenticated accounts.
2. Switch to a web2 authenticated account by clicking on it in the account dropdown.
3. Switch from a web2 account to a web3 authenticated account: this should be possible as long as this account corresponds to the account address set in Keplr, else a warning is displayed.
4. Log in with Keplr using wallet address A and switch to …
=> feat: add and switch accounts

README.md
Closes: regen-network/regen-web#2236
Update readme post bun migration.
---
I have...
1.
I have...
=> doc: update readme with bun changes

web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts, web-marketplace/src/hooks/useTags.ts, web-marketplace/src/pages/CreditClassDetails/CreditClassDetailsSimple/hooks/useCreditClassDetails.tsx
Closes: regen-network/regen-web#2232
- fix icons mapping for credit type, activities and ecosystem
---
I have...
1.
I have...
=> fix: updates for jaguar pilot

web-components/src/components/sliders/ResponsiveSlider.tsx
Closes: #2240
---
I have...
https://deploy-preview-2244--regen-website.netlify.app/
I have...
=> fix: dots height in ResponsiveSlider

web-marketplace/.env.example, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.config.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/lib/env.ts
Closes: regen-network/regen-web#2250
- add buy button for Sharamentsa pilot
---
I have...
1.
I have...
=> feat: add buy button jaguar

README.md
=> docs: fix bun install

docs/docker-dev-setup.md
This pull request adds instructions for using docker to set up a local development environment.
---
I have...
1. Follow the instructions added as documentation
I have...
=> docs: add instructions for docker dev setup

web-marketplace/src/pages/ProjectReview/ProjectReview.tsx, web-marketplace/src/pages/Roles/Roles.tsx, web-marketplace/src/pages/Roles/hooks/useRolesSubmit.tsx
Closes: #2262
---
I have...
1. Login and create an off-chain project from https://deploy-preview-2270--regen-marketplace.netlify.app/profile/projects
1. Go through all the project creation steps
1. Go back to /profile/projects and try to edit the project you just created
1. It will go to the edit flow
I have...
=> fix: refetch current account projects after project published

web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx
Closes: #2260
---
I have...
1. Log in from https://deploy-preview-2274--regen-marketplace.netlify.app/ on mobile or with a mobile window on desktop
2. Go to edit profile
3. Click on the back arrow twice to go back to your profile page
I have...
=> fix: navigate to profile page on back click on mobile

web-components/src/components/footer/SocialLinks.tsx, web-www/components/templates/press-kit/ConnectSection/ConnectSection.config.tsx, web-www/components/templates/token/TokenConnectSection/TokenConnectSection.config.tsx
Reference: https://discord.com/channels/684494798358315010/947551295546462278/1200253124137455709
- The Discord link in the footer currently leads to a compromised Discord server.
- If you check the Discord at https://discord.gg/regen-network, you will find a phishing verification bot.
- This is a problem for anybody who is not savvy enough to spot a phishing attempt.
- This PR updates the link to the actual Discord, which is referenced here: https://guides.regen.network/guides/regen-network/network-basics/connect-with-us
- Is there anything that can be done to delete or terminate the compromised Discord server at https://discord.gg/regen-network ?
- Please strongly consider how to terminate the old compromised Discord server at https://discord.gg/regen-network
---
_All items are …
=> Update Discord links

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
ref: https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#5b52533e5fec45729a585611ba24c2bc
---
I have...
1.
I have...
=> chore: release dev sync v2.0.0

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Prefinance.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.PrefinanceStatus.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.PrefinanceTimeline.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.constant.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
Closes: #2284
---
I have...
Check out the project and credit class timelines on https://deploy-preview-2296--regen-marketplace.netlify.app/project/prefinance-project
I have...
=> feat: add prefinance project and credit class timeline modal

web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.styles.ts, web-components/src/components/header/index.tsx, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/Projects.context.tsx, web-marketplace/src/pages/Projects/Projects.tsx
Targeting main so it's a hot fix.
ref: https://regen-network.slack.com/archives/C04NR9HSNCB/p1709051205775379
---
I have...
https://deploy-preview-2299--regen-marketplace.netlify.app/projects/1 and test filters and switching tabs
I have...
=> fix: improve projects loading

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.styles.ts, web-components/src/components/header/index.tsx, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/Projects.context.tsx, web-marketplace/src/pages/Projects/Projects.tsx, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync v2.1.0
---
I have...
1.
I have...
=> chore: dev sync v2.1.0

web-marketplace/graphql.schema.json, web-marketplace/src/components/organisms/Stakeholders/Stakeholders.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Stakeholders.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-marketplace/src/components/templates/ProjectDetails/hooks/useStakeholders.ts, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/ProjectFragment.graphql, web-marketplace/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.Stakeholders.tsx
Needs: https://github.com/regen-network/regen-server/pull/444
Closes: regen-network/rnd-dev-team#1857
---
I have...
https://deploy-preview-2301--regen-marketplace.netlify.app/project/prefinance-project
I have...
=> feat: add project partners

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
=> chore: dev sync v2.2.0

web-components/src/components/image/index.tsx, web-marketplace/src/components/organisms/LoginFlow/LoginFlow.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.PrefinanceTimeline.tsx
ref: https://github.com/regen-network/rnd-dev-team/issues/1895#issuecomment-1977032320
---
I have...
Go to https://deploy-preview-2311--regen-marketplace.netlify.app/ and from your dev tools network tab, check on /projects and on any project page that the images are not loaded twice (in non optimized and optimized versions as it was the case), but loaded from our server /marketplace/v1/image endpoint with some `w` and `q` url parameters (and not from our S3 bucket directly).
I have...
=> fix: optimized `Image` component

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-components/src/components/image/index.tsx, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/LoginFlow/LoginFlow.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.PrefinanceTimeline.tsx, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync v2.2.1
---
I have...
1.
I have...
=> chore: dev sync v2.2.1

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.loader.ts, web-marketplace/src/generated/graphql.tsx, web-marketplace/src/graphql/AllProjects.graphql, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/ledger.tsx, web-marketplace/src/pages/Marketplace/Storefront/Storefront.normalizer.ts, web-marketplace/src/pages/Marketplace/Storefront/hooks/useNormalizedSellOrders.tsx, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/hooks/useOffChainProjects.tsx
Ref: regen-network/rnd-dev-team#1895
A few optimizations for improving /projects loading 
---
I have...
https://deploy-preview-2315--regen-marketplace.netlify.app/projects/1
I have...
=> fix: ledger/projects queries optimization

web-marketplace/src/components/organisms/BasicInfoForm/BasicInfoForm.schema.ts, web-marketplace/src/components/organisms/BasicInfoForm/BasicInfoForm.tsx, web-marketplace/src/components/organisms/BasicInfoForm/hooks/useSubmitCreateProject.ts, web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormAccessTemplate.tsx, web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormTemplate.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.Grid.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.constants.ts, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx, web-marketplace/src/pages/ProjectCreate/ProjectCreate.tsx
---
I have...
1. Go to https://deploy-preview-2332--regen-marketplace.netlify.app/ and log in
2. Create a new project: with and without credit class (you have to use an credit class issuer account to create a project with a credit class)
3. Double check that the whole flow is still working as usual, except that on the "Choose credit class" and "Basic info" forms (until you have submitted the later), the project id is set to "draft" in the URL. After you submit the basic info form, then the URL will contains the newly created project id.
_All items are required. Please add a note if the item is not …
=> chore: APP-14 Don't create a new project until after saving project name and size on the basic info form

web-components/src/components/image-crop/ImageCrop.constants.ts, web-components/src/components/image-crop/canvas-utils.ts, web-components/src/components/image-crop/index.tsx, web-components/src/components/inputs/ImageDrop.tsx, web-components/src/components/inputs/ImageField.tsx, web-components/src/components/inputs/new/FileDrop/FileDrop.tsx, web-components/src/components/inputs/new/ImageField/ImageField.tsx, web-components/src/utils/s3.ts, web-marketplace/src/components/organisms/MediaForm/MediaForm.stories.tsx, web-marketplace/src/components/organisms/MediaForm/MediaForm.tsx, web-marketplace/src/components/organisms/MediaForm/MediaForm.utils.ts, web-marketplace/src/components/organisms/MediaForm/MediaFormPhotos.tsx, web-marketplace/src/components/organisms/MediaForm/MediaFormStory.tsx, web-marketplace/src/components/organisms/MediaForm/hooks/useHandleUpload.ts, web-marketplace/src/components/organisms/PostForm/PostForm.tsx, web-marketplace/src/hooks/projects/useProjectWithMetadata.ts, web-marketplace/src/pages/Media/Media.tsx
Closes: regen-network/rnd-dev-team#1880
---
I have...
1. Go to https://deploy-preview-2326--regen-marketplace.netlify.app/ and log in
2. Create or edit project and go to the Media form
3. Try to upload a large image, you should see some loading spinner while it gets uploaded.
I have...
=> feat: add loading spinner when file gets uploaded APP-10

web-marketplace/src/pages/Certificate/Certificate.tsx
Closes https://regennetwork.atlassian.net/browse/APP-88 
---
I have...
1.
I have...
=> fix: APP-88 fix certificate share URL

web-components/src/components/read-more/index.tsx, web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.StoryText.tsx, web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.styles.ts
https://regennetwork.atlassian.net/browse/APP-89?atlOrigin=eyJpIjoiNDQwY2ZlZTU0NTc0NDNiNGJiMzBjZmMzZGRkMTRmYWEiLCJwIjoiaiJ9
---
I have...
https://deploy-preview-2343--regen-marketplace.netlify.app/project/C01-008
Testing project with the exact same video and story as the [ihp-pilot](https://app.regen.network/project/ihp-pilot) project where the UI issue was seen on.
I have...
=> fix: APP-89 story text covered by media on project page

web-components/src/components/inputs/new/FileDrop/FileDrop.tsx
https://regennetwork.atlassian.net/browse/APP-18?atlOrigin=eyJpIjoiNzRhZmVhZjU0OTczNDMwYTk3OWM0Zjk1MDE1N2Q4ZDMiLCJwIjoiaiJ9
---
I have...
1. From https://deploy-preview-2346--regen-marketplace.netlify.app/ log in
2. Create or edit an existing project, go to the Media form
3. For the gallery photos, try selecting multiple files to upload (either drag and drop or select multiple)
I have...
=> feat: APP-18 upload multiple photos in project media form gallery photo by selecting multiple files in file browser

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-components/src/components/header/Header.styles.ts, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/ListProject/ListProject.constants.ts, web-marketplace/src/components/organisms/ListProject/ListProject.tsx, web-marketplace/src/components/organisms/LoginButton/LoginButton.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useConnectToWallet.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useLoginData.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useSocialProviders.ts, web-marketplace/src/components/organisms/LoginFlow/LoginFlow.tsx, web-marketplace/src/components/organisms/LoginFlow/hooks/useEmailConfirmationData.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/lib/wallet/hooks/useConnectWallet.tsx, web-marketplace/src/lib/wallet/wallet.utils.ts, web-marketplace/src/pages/Dashboard/hooks/useProfileItems.tsx, web-marketplace/src/pages/ProfileEdit/ProfileEdit.Settings.tsx, web-www/CHANGELOG.md, web-www/components/organisms/BackgroundImage/BackgroundImage.tsx, web-www/components/templates/press-kit/ConnectSection/ConnectSection.config.tsx, web-www/components/templates/press-kit/EnableSection/EnableSection.tsx, web-www/components/templates/token/TokenConnectSection/TokenConnectSection.config.tsx, web-www/lib/utils/sanity/sanity-transforms.tsx, web-www/package-lock.json, web-www/package.json
=> chore: dev sync v2.4.0

web-marketplace/src/components/molecules/EditProjectPageFooter.tsx, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx, web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx, web-marketplace/src/pages/ProjectFinished/ProjectFinished.constants.tsx, web-marketplace/src/pages/ProjectFinished/ProjectFinished.tsx
https://regennetwork.atlassian.net/browse/APP-108?atlOrigin=eyJpIjoiNDUwN2E3NGNkNDhkNDNkMmIxNGVmMzE5YTFhNTNlMDAiLCJwIjoiaiJ9
---
I have...
1. Log in from https://deploy-preview-2351--regen-marketplace.netlify.app/
2. Edit one of your published project, you should need the new "view project" button that opens up the project page in a new tab
3. On a project page you're an admin of, the bottom banner should just have one button to "edit project", try to edit both an offchain and an onchain project from there
your handle next to the items reviewed if you only …
=> feat: APP-108 edit/view project buttons

web-marketplace/src/components/organisms/ListProject/ListProject.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useLoginData.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
https://regennetwork.atlassian.net/browse/APP-134?atlOrigin=eyJpIjoiZmRlOTc0YmY4ZmRhNGZkNjhlYmM0ZjE4NmNlNjc5NmQiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2360--regen-marketplace.netlify.app/:
1. Test that "list a project" feature still works as expected, especially that once logged in, it navigates to the basic info form if not an issuer, else to the choose credit class form
2. The app should be more responsive than https://dev.app.regen.network/, this was especially visible on the /projects page
your handle next to the items reviewed if you only …
=> fix: APP-134 ListProject optimization

web-components/src/components/image-crop/canvas-utils.ts, web-components/src/components/inputs/ImageUpload.tsx, web-components/src/components/inputs/new/ImageField/ImageField.tsx, web-components/src/utils/s3.ts, web-marketplace/src/components/organisms/EditProfileForm/EditProfileForm.tsx, web-marketplace/src/components/organisms/MediaForm/MediaForm.constants.ts, web-marketplace/src/components/organisms/MediaForm/MediaForm.tsx, web-marketplace/src/pages/ProfileEdit/ProfileEdit.Main.tsx, web-marketplace/src/pages/ProfileEdit/hooks/useOnUploadCallback.tsx
needs: https://github.com/regen-network/regen-server/pull/466
https://regennetwork.atlassian.net/browse/APP-114?atlOrigin=eyJpIjoiOGE2YzJkZTgzMjE2NDVlNGE3NGUxZjYyMmY0YmI1ZDQiLCJwIjoiaiJ9
---
I have...
Log in from https://deploy-preview-2355--regen-marketplace.netlify.app/ and try to edit your profile (profile/background image and another field)
If you have access to s3, also check that when you update an image, the old one gets deleted.
I have...
=> fix: APP-114 edit profile

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/ListProject/ListProject.tsx, web-marketplace/src/components/organisms/LoginButton/hooks/useLoginData.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
dev sync v2.4.1
---
I have...
1.
I have...
=> chore: dev sync v2.4.1

web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/lib/db/types/json-ld/project-metadata.ts
https://regennetwork.atlassian.net/browse/APP-145?atlOrigin=eyJpIjoiYTZlNzBhYjMxYjc2NGFiMWI5NTRlNzg1ZjNjNDgxODciLCJwIjoiaiJ9
---
I have...
https://deploy-preview-2366--regen-marketplace.netlify.app/project/C01-001 
I have...
=> feat: APP-145 get ecosystemType primarily from projectMetadata

web-components/src/components/organisms/ProjectTags/ProjectTags.tsx
https://regennetwork.atlassian.net/browse/APP-103?atlOrigin=eyJpIjoiNGZmZjAyMTA1NmNkNDQ3ZDg5NGExNTc5NjUwY2FmZDIiLCJwIjoiaiJ9
---
I have...
https://deploy-preview-2358--regen-marketplace.netlify.app/project/C04-001
I have...
=> fix: APP-103 ecosystem tags margin bottom

web-marketplace/src/pages/Projects/Projects.tsx
ref: https://regen-network.slack.com/archives/C04NR9HSNCB/p1715614043812439
---
I have...
https://deploy-preview-2361--regen-marketplace.netlify.app/projects/prefinance
I have...
=> fix: add prefinance sanity content to /projects/prefinance

web-www/public/_redirects
https://regennetwork.atlassian.net/browse/WWW-1?atlOrigin=eyJpIjoiOTA0NTk4NDU4YWYwNGQ4NDkxMzE1ZTEwMTA0ZmUxZDQiLCJwIjoiaiJ9
---
I have...
Test /nct page redirect: https://deploy-preview-2369--regen-website.netlify.app/nct
as well as all the other redirects listed in https://github.com/regen-network/regen-web/pull/2369/files
I have...
=> fix: WWW-1 website redirects

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/lib/db/types/json-ld/project-metadata.ts
dev sync v2.5.0
---
I have...
1.
I have...
=> chore: dev sync v2.5.0

web-marketplace/src/lib/atoms/modals.atoms.ts, web-marketplace/src/pages/ProfileEdit/hooks/useConnectWalletToAccount.tsx
https://regennetwork.atlassian.net/browse/APP-113?atlOrigin=eyJpIjoiMTZiYzA4OWJjNDcyNDc5N2I2MGE1MDA0Yzg0ZWI5ZDciLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2371--regen-marketplace.netlify.app/, try to buy some credits from /storefront (or any other "buy" button within the app: featured projects on home page, projects list, project page) and choose to log in. You should be able to log in successfully with Keplr and see the "Buy Ecocredits" pop up.
I have...
=> fix: APP-113 logging in from buy button

netlify.toml, web-marketplace/src/lib/block-explorer.ts
https://regennetwork.atlassian.net/browse/APP-167?atlOrigin=eyJpIjoiOGM3MjgzNjBlZjNiNDM3ODg5MDc3OTMyNDkzMDYzMjMiLCJwIjoiaiJ9
---
I have...
1.
I have...
=> fix: APP-167 use atomscan as block explorer

web-marketplace/src/lib/ecocredit/api.ts, web-marketplace/src/lib/queries/react-query/ecocredit/getClassesQuery/getClassesQuery.ts
Closes: #2201
https://regennetwork.atlassian.net/browse/APP-112
---
I have...
1. You need to seed the ledger with > 100 projects... ideally from a single project admin. 
- I already have some scripts for generating projects in bulk from source Airtable data so it was easy to prepare this.
- If you can configure regen-web to use regen-redwood-1 you could also likely test > 100 projects.
- Otherwise... maybe we should add additional projects to the local ledger docker data/scripts so we always have > 100 when testing locally? Happy to add this if it helps.
1. Go to the "Projects" page. Enable all filters and make sure > 100 total projects are shown in …
=> fix: APP-112 project and credit class pagination

web-components/src/components/modal/SadBeeModal/SadBeeModal.stories.tsx, web-components/src/components/modal/SadBeeModal/SadBeeModal.tsx, web-marketplace/src/components/molecules/EditProjectPageFooter.tsx, web-marketplace/src/components/organisms/UserAccountSettings/UserAccountSettings.ConnectedEmailErrorModal.tsx, web-marketplace/src/pages/ProjectEdit/ProjectEdit.WarningModal.tsx, web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx
https://regennetwork.atlassian.net/browse/APP-136?atlOrigin=eyJpIjoiYzIwZDZmZDVlYzg3NDhiMzk5ZTAxNjdmNmViNmJjYmYiLCJwIjoiaiJ9
---
I have...
1. From https://deploy-preview-2363--regen-marketplace.netlify.app/, log in and edit a published project (not a draft)
2. Make some changes without saving and click "view project"
3. Click "cancel" to stay on the form or "yes, delete" to go to the project page without saving
I have...
=> feat: APP-136 show warning when clicking "view project" from project edit with unsaved changes

CHANGELOG.md, lerna.json, netlify.toml, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/lib/block-explorer.ts
dev sync v2.5.1
---
I have...
1.
I have...
=> chore: dev sync v2.5.1

web-components/src/components/cards/ProjectCard/ProjectCard.constants.tsx, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-marketplace/sanity-graphql.schema.json, web-marketplace/src/components/molecules/EditProjectPageFooter.tsx, web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx, web-marketplace/src/generated/sanity-graphql.tsx, web-marketplace/src/graphql/sanity/AllProfilePage.graphql, web-marketplace/src/pages/Dashboard/Dashboard.BannerCard.tsx, web-marketplace/src/pages/Dashboard/Dashboard.context.tsx, web-marketplace/src/pages/Dashboard/Dashboard.tsx, web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx, web-marketplace/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByAdmin.tsx, web-marketplace/src/pages/EcocreditsByAccount/ProjectsTab/ProjectsTab.tsx, web-marketplace/src/pages/Home/Home.FeaturedProjects.tsx, web-marketplace/src/pages/ProjectFinished/ProjectFinished.constants.tsx, web-marketplace/src/pages/ProjectFinished/ProjectFinished.tsx, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/PrefinanceProjects/PrefinanceProjects.tsx
https://regennetwork.atlassian.net/browse/APP-98?atlOrigin=eyJpIjoiYTZkMjc2YjI4Mzc1NDVkM2EwMTljMzg5ZmNkZDA3YWQiLCJwIjoiaiJ9
---
I have...
1. Verify project cards are rendered properly, ie:
- view project button and no price/credits info for off-chain projects
- prefinance tag and button for prefinance projects
- price/credits info and buy button for on-chain projects
on:
- https://deploy-preview-2372--regen-marketplace.netlify.app/ (featured projects):
- https://deploy-preview-2372--regen-marketplace.netlify.app/projects/1
- https://deploy-preview-2372--regen-marketplace.netlify.app/projects/prefinance
- …
=> feat: APP-98 project cards update

web-components/src/components/image-crop/index.tsx, web-components/src/components/modal/CropImageModal.tsx, web-components/src/components/organisms/CancelButtonFooter/CancelButtonFooter.tsx
https://regennetwork.atlassian.net/browse/APP-139?atlOrigin=eyJpIjoiZTI1ZTUyN2QxMmIwNDBhOGJlYTQ3MmZhMmJjOTJkNTciLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2375--regen-marketplace.netlify.app, log in and create/edit a project
Go to the media form and try adding photos, check the upload modal layout on all screen sizes. 
I have...
=> fix: APP-139 upload modal layout

web-marketplace/src/lib/wallet/wallet.tsx
https://regennetwork.atlassian.net/browse/APP-115?atlOrigin=eyJpIjoiYzY2MjE2ZjdkYThlNGU3M2E5NTg2MDMxZjgyNDBmM2QiLCJwIjoiaiJ9
---
I have...
Try to log in via wallet connect on mobile from https://deploy-preview-2377--regen-marketplace.netlify.app/
Once connected, reload the page, it should not show the prompt to open the keplr app again.
I have...
=> fix: connecting with wallet connect on mobile

web-marketplace/sanity-codegen.yml, web-marketplace/sanity-graphql.schema.json, web-marketplace/src/generated/sanity-graphql.tsx, web-marketplace/src/graphql/sanity/AllCreateProjectPage.graphql, web-marketplace/src/lib/queries/react-query/sanity/getAllCreateProjectPageQuery/getAllCreateProjectPageQuery.constants.ts, web-marketplace/src/lib/queries/react-query/sanity/getAllCreateProjectPageQuery/getAllCreateProjectPageQuery.ts, web-marketplace/src/lib/queries/react-query/sanity/getAllCreateProjectPageQuery/getAllCreateProjectPageQuery.types.ts, web-marketplace/src/pages/BasicInfo/BasicInfo.CreateProjectPageModal.tsx, web-marketplace/src/pages/BasicInfo/BasicInfo.tsx, web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx, web-marketplace/src/pages/ChooseCreditClass/hooks/useGetCreditClassOptions.tsx
https://regennetwork.atlassian.net/browse/APP-140?atlOrigin=eyJpIjoiZjJkNjE5NTllY2NjNDdmMWFmZDA4MjU2YWE1MTEyMGMiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2374--regen-marketplace.netlify.app/
1. Log in with a web2 account and create a project (either from list a project top nav button or from the create project button on your profile page), you should see the popup on top of the basic info form
2. Log in with a web3 account that is an issuer and create a project:
- if you choose a credit class then you'll get to the basic info form without the popup being displayed
- if you do no choose any credit class then you'll get to the basic info …
=> feat: APP-140 add a popup with basic info about offchain project pages for users

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync v2.6.0
---
I have...
1.
I have...
=> chore: dev sync v2.6.0

web-marketplace/src/lib/rdf/rdf.compact.ts
ref: https://regen-network.slack.com/archives/C05LGSWT344/p1718202097996419
---
I have...
1.
I have...
=> chore: overwrite incoming metadata context with full context

.github/workflows/main.yml, web-components/src/components/inputs/new/Radio/Radio.stories.tsx, web-components/src/components/inputs/new/Radio/Radio.tsx, web-components/src/components/inputs/new/VideoInput/VideoInput.constants.ts, web-components/src/components/inputs/new/VideoInput/VideoInput.tsx, web-marketplace/src/components/organisms/MediaForm/MediaForm.constants.ts, web-marketplace/src/components/organisms/MediaForm/MediaFormStory.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.tsx
https://regennetwork.atlassian.net/browse/APP-155?atlOrigin=eyJpIjoiZWRiMmI2YWY3MzU2NDgzOGFiYTg0NzczNmJkZGQ1OGUiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2385--regen-marketplace.netlify.app/, go to a project media form and add a video:
- as soon as a valid video url is entered, it will set the form value and show the preview
- if an invalid url is entered, an error message is displayed under the video field. If the user types enter or navigates away with an invalid url, the error should also appear in a red banner at the top.
your handle next to the …
=> feat: APP-155 update VideoInput to detect valid url and display error

tailwind.common.js, tailwind.css, web-components/src/components/inputs/new/FileDrop/FileDrop.utils.ts, web-components/src/components/organisms/Gallery/Gallery.tsx, web-components/src/components/organisms/PostFiles/PostFiles.Drawer.tsx, web-components/src/components/organisms/PostFiles/PostFiles.Public.tsx, web-components/src/components/organisms/PostFiles/PostFiles.constants.ts, web-components/src/components/organisms/PostFiles/PostFiles.utils.tsx, web-components/src/components/organisms/PostFiles/components/FilePreview.tsx
https://regennetwork.atlassian.net/browse/APP-177?atlOrigin=eyJpIjoiMjY1NDI1ZWVhZWFlNDg1M2FhOWE5ZmY5N2Q5MjQ2NWQiLCJwIjoiaiJ9
---
I have...
- Map: https://deploy-preview-2388--regen-storybook.netlify.app/?path=/story/organisms-postfiles--public
- Gallery: https://deploy-preview-2388--regen-storybook.netlify.app/?path=/story/organisms-postfiles--private-locations
I have...
=> feat: APP-177 add colors based on post file type in gallery/map view

web-components/src/components/organisms/CancelButtonFooter/CancelButtonFooter.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.AddressUsedModal.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.AddressUsedWithEmailModal.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.SelectAccountModal.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.constants.ts, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.utils.ts, web-marketplace/src/components/organisms/ConnectWalletFlow/hooks/useConnectWalletToAccount.tsx, web-marketplace/src/components/organisms/ConnectWalletFlow/hooks/useMergeAccounts.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.ConnectWalletModal.tsx, web-marketplace/src/pages/ProfileEdit/ProfileEdit.Settings.tsx
Needs https://github.com/regen-network/regen-server/pull/467
https://regennetwork.atlassian.net/browse/APP-115?atlOrigin=eyJpIjoiYmJiMTFlYWU5NzBjNGU1YzhlOWZhOGZjYTA4ZjQ0OTgiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2370--regen-marketplace.netlify.app/profile/edit/settings
1. Log in with a web2 account and try to connect a wallet address that is already used by another account
2. Choose to keep the current account and verify that your profile remains the same and all projects from both accounts have been merged into the current account
3. Log out and redo 1. but choose to keep the web3 account. Verify that profile data is now the one from …
=> feat: APP-115 account merging

web-www/pages/_app.tsx, web-www/pages/index.tsx
https://regennetwork.atlassian.net/browse/WWW-4?atlOrigin=eyJpIjoiNjRmYjgxYjNmN2M3NDE0ZWFhZDcyM2M1YjJkYjFkZWIiLCJwIjoiaiJ9
---
I have...
Visit multiple pages of https://deploy-preview-2395--regen-website.netlify.app and check that they appear in GA real time report: https://analytics.google.com/analytics/web/?authuser=2#/p446852950/realtime/overview?params=_u..nav%3Dmaui (Regen Website [DEVELOPMENT] property)
I have...
=> fix: WWW-4 google analytics on all website pages

web-storybook/.storybook/main.js
fixing this issue https://github.com/mui/material-ui/issues/32727#issuecomment-1697253782 when running storybook locally
---
I have...
Run storybook locally.
Also test storybook deploy preview.
I have...
=> fix: storybook vite config

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
Fixing https://regennetwork.atlassian.net/browse/APP-213?atlOrigin=eyJpIjoiNGVhN2QwNThjMGE2NDY4MTgyYTljYWNlNGI1MmQyYjIiLCJwIjoiaiJ9
The fix was on main but not on dev. Just needed to sync dev with main which I had forgotten to do.
---
I have...
https://deploy-preview-2411--regen-marketplace.netlify.app/project/woodburn
I have...
=> chore: dev sync v2.6.1

web-components/src/components/fixed-footer/SaveFooter.tsx, web-components/src/components/fixed-footer/footer.stories.tsx, web-marketplace/src/components/molecules/ProjectPageFooter.tsx
https://regennetwork.atlassian.net/browse/APP-158?atlOrigin=eyJpIjoiOTI2MjlhOTE4ZTIyNDI1YWJiMDdkNGU0NzVlNDcyZDEiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2420--regen-marketplace.netlify.app/, log in and create a new project to check the button text has been updated from "save and next" to "next".
I have...
=> chore: APP-158 next button

web-marketplace/src/components/organisms/CreditClassCards.tsx
https://regennetwork.atlassian.net/browse/APP-63?atlOrigin=eyJpIjoiNTgyNmRiYzliYmM4NGIwNDgwYTJhNWM1MjhlZTJiYzkiLCJwIjoiaiJ9
---
I have...
Check that on chain class ids do not appear in parenthesis in the credit classes section on https://deploy-preview-2422--regen-marketplace.netlify.app/
I have...
=> chore: APP-63 remove class id from credit class cards title on homepage

web-components/src/components/buttons/PostAdminButton/PostAdminButton.tsx, web-components/src/components/cards/PostCard/PostCard.MenuItems.tsx, web-components/src/components/cards/PostCard/PostCard.constants.ts, web-components/src/components/cards/PostCard/PostCard.tsx, web-components/src/components/cards/PostCard/PostCardActionButton.tsx, web-marketplace/src/components/organisms/DeletePostWarningModal/DeletePostWarningModal.constants.ts, web-marketplace/src/components/organisms/DeletePostWarningModal/DeletePostWarningModal.tsx, web-marketplace/src/components/organisms/PostFlow/PostFlow.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.Post.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.constant.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-marketplace/src/lib/queries/react-query/registry-server/getPostQuery/getPostQuery.ts, web-marketplace/src/lib/queries/react-query/registry-server/getPostsQuery/getPostsQuery.constants.ts, web-marketplace/src/lib/queries/react-query/registry-server/getPostsQuery/getPostsQuery.ts, web-marketplace/src/lib/queries/react-query/registry-server/getPostsQuery/getPostsQuery.types.ts, web-marketplace/src/lib/queries/react-query/registry-server/getPostsQuery/getPostsQuery.utils.ts, web-marketplace/src/pages/Post/Post.Header.tsx, web-marketplace/src/pages/Post/Post.constants.ts, web-marketplace/src/pages/Post/Post.tsx, web-marketplace/src/pages/Post/hooks/useDelete.ts, web-marketplace/src/utils/fetch/postData.ts
https://regennetwork.atlassian.net/browse/APP-188
needs: https://github.com/regen-network/regen-server/pull/477
---
I have...
From https://deploy-preview-2409--regen-marketplace.netlify.app/, log in and go to a project page you're an admin of with some existing posts.
Try to delete a post from the data stream section. The post should be removed from the timeline.
Access one of the posts page and delete the post from there. It should redirect to the project data stream section.
I …
=> feat: APP-188 delete post

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/CreateSellOrderForm/CreateSellOrderForm.tsx, web-marketplace/src/components/organisms/CreditSendForm/CreditSendForm.tsx, web-marketplace/src/lib/queries/react-query/ecocredit/marketplace/getSellOrdersExtendedQuery/getSellOrdersExtendedQuery.ts, web-marketplace/src/pages/Marketplace/Storefront/hooks/useNormalizedSellOrders.tsx
dev sync v2.6.3
**DO NOT MERGE from Github**, follow https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#1d31a07e9b624b65a04d9c0c8b8fed51
---
I have...
1.
I have...
=> fix: dev sync v2.6.3

web-marketplace/netlify.toml
https://regennetwork.atlassian.net/browse/APP-252
**DO NOT MERGE from Github**, follow instructions in https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#8acaa2cb42e740868083ab24df616be1
---
I have...
This isn't really testable on deploy previews since they are not using the prod environment variables.
I have...
=> chore: APP-252 use mintscan as block explorer

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/netlify.toml, web-marketplace/package.json
dev sync v2.6.4
**DO NOT MERGE FROM GITHUB**, see https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#1d31a07e9b624b65a04d9c0c8b8fed51
---
I have...
1.
I have...
=> chore: dev sync v2.6.4

web-components/src/components/image-crop/canvas-utils.ts, web-components/src/components/inputs/ImageDrop.tsx, web-components/src/components/inputs/ImageField.tsx, web-components/src/components/inputs/ImageUpload.tsx, web-components/src/components/inputs/new/FileDrop/FileDrop.tsx, web-components/src/components/inputs/new/ImageField/ImageField.tsx, web-components/src/utils/s3.ts, web-marketplace/src/components/organisms/EditProfileForm/EditProfileForm.tsx, web-marketplace/src/components/organisms/MediaForm/hooks/useHandleUpload.ts, web-marketplace/src/components/organisms/RolesForm/components/ProfileModal/ProfileModal.tsx, web-marketplace/src/components/organisms/RolesForm/components/RoleField/RoleField.tsx, web-marketplace/src/pages/ProfileEdit/hooks/useOnUploadCallback.tsx
https://regennetwork.atlassian.net/browse/APP-283
---
I have...
From https://deploy-preview-2435--regen-marketplace.netlify.app/
Make sure that file upload, from any places in the app, is working correctly: profile edit and project media form (post form not yet on `main`).
I have...
=> fix: APP-283 file upload

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.tsx
https://regennetwork.atlassian.net/browse/APP-237
---
I have...
From https://deploy-preview-2426--regen-marketplace.netlify.app/
Log in with a class issuer wallet, try to create a post for one of your on chain project data stream section, with and without files. In particular, with our testing account, you can test on project https://deploy-preview-2426--regen-marketplace.netlify.app/project/C01-008
I have...
=> fix: APP-237 use offChainProjectId in PostFlow on onchain project data stream

web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.Item.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx
Fix: https://regennetwork.atlassian.net/browse/APP-307
Some constants used in `UseMenuItems` and converted to lingui macro were not translated.
---
I have...
1.
I have...
=> fix: APP-307 user menu translate issue

web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx
- fix issue on `profile/portfolio` page initialization
- regenerate i18n messages
---
I have...
1.
I have...
=> fix: profile portfolio issue

web-components/src/components/inputs/new/LocationPicker/LocationPicker.tsx
https://regennetwork.atlassian.net/browse/APP-238
---
I have...
From https://deploy-preview-2440--regen-marketplace.netlify.app/, log in and create a post for a project.
Upload the file mentioned in https://regennetwork.atlassian.net/browse/APP-238 or any file with a geolocation.
Make sure the pin location on the map is correct.
I have...
=> fix: APP-238 pin position on post file location picker

web-components/src/components/organisms/PostFiles/components/TextOrIconFilePreview.tsx, web-marketplace/src/components/molecules/Form/Form.tsx, web-marketplace/src/components/organisms/PostForm/PostForm.tsx
https://regennetwork.atlassian.net/browse/APP-262
APP-263 looks fixed too: https://regennetwork.atlassian.net/browse/APP-263
---
I have...
1. Create a New Post in a project and upload files to verify the files thumbnail doesn't overflow its container.  I have used .csv, .docx, .xls, .mp3, .mp4 and .json files while working on this. (APP-262)
2. In the Project Page, verify that the Share Link icon is not cut. (APP-263)
I have...
=> fix: APP-262 APP-303 create post files rendering

tailwind.common.js, web-components/src/components/inputs/new/LocationPicker/LocationPicker.tsx, web-components/src/components/inputs/new/Radio/Radio.tsx, web-marketplace/src/components/organisms/EditFileForm/EditFileForm.tsx, web-marketplace/src/components/organisms/PostForm/PostForm.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
https://regennetwork.atlassian.net/browse/APP-265
---
I have...
From https://deploy-preview-2442--regen-marketplace.netlify.app/, log in and create a post for a project.
Upload a file and check that a hint has been added for the last location option "(drag map to choose location)"
I have...
=> chore: APP-265 add hint to drag file location

CHANGELOG.md, lerna.json, web-auth/CHANGELOG.md, web-auth/package.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/EditProfileForm/EditProfileForm.tsx, web-marketplace/src/pages/ProfileEdit/hooks/useOnUploadCallback.tsx, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
=> chore: dev sync v2.6.5

web-components/src/components/cards/ProjectCard/ProjectCard.CreditPrice.tsx, web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-components/src/components/gradient-badge/GradientBadge.tsx, web-components/src/components/text-layouts/LabeledValue.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.constants.ts, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Prefinance.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.PrefinanceStatus.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/Projects/AllProjects/AllProjects.constants.ts, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/AllProjects/utils/getIsSoldOut.ts, web-marketplace/src/pages/Projects/PrefinanceProjects/PrefinanceProjects.tsx, web-marketplace/src/pages/Projects/Projects.context.tsx, web-marketplace/src/pages/Projects/Projects.tsx
https://regennetwork.atlassian.net/browse/APP-214?atlOrigin=eyJpIjoiYTM4NjU1MjUxZWJmNDU5ZmE4NjM2NjgzOGE3NTY1ZmYiLCJwIjoiaiJ9
---
I have...
1. Sold out prefinance project card: https://deploy-preview-2414--regen-marketplace.netlify.app/projects/prefinance
2. Sold out prefinance project page: https://deploy-preview-2414--regen-marketplace.netlify.app/project/prefinance-project
3. Sold out on chain project card: https://deploy-preview-2414--regen-marketplace.netlify.app/projects/1 and **filter to show only Urban Forest Carbon Credit Class**, 2nd project is sold out
4. Sold out on chain project page: …
=> feat: APP-214 sold out projects

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.Post.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/hooks/batches/useAddDataToBatches.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/lib/normalizers/batches/normalizeBatchesWithData.ts, web-marketplace/src/lib/queries/react-query/cosmos/bank/getTxsEventQuery/getTxsEventQuery.ts, web-marketplace/src/lib/queries/react-query/cosmos/bank/getTxsEventQuery/getTxsEventQuery.types.ts, web-marketplace/src/lib/queries/react-query/cosmos/bank/getTxsEventQuery/getTxsEventQuery.utils.ts, web-marketplace/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx, web-marketplace/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts, web-marketplace/src/pages/Post/Post.Timeline.tsx, web-marketplace/src/pages/Post/Post.tsx, web-marketplace/src/pages/Post/hooks/useAttestEvents.ts
https://regennetwork.atlassian.net/browse/APP-264
This also fixes `GetTxsEvent` to fetch more than 100 items (default limits).
---
I have...
https://deploy-preview-2443--regen-marketplace.netlify.app/post/regen:13toVhoyn9zGbPQXYhRtFe7MSG29KF7CM7tHgE8nYyMNrH9NmWXt7wx.rdf
I have...
=> chore: APP-264 separate created from signed events on post timeline

web-components/src/components/organisms/PostFiles/PostFiles.Public.tsx
https://regennetwork.atlassian.net/browse/APP-299
---
I have...
https://deploy-preview-2456--regen-marketplace.netlify.app/post/regen:13toVgcBUmHqa4uQDjdmVkoEP9DEjnsiZmTS4B4zU1ZLb5Fpt7vnoNq.rdf
I have...
=> fix: APP-299 fix mobile padding on PostFilesPublic map 

web-components/src/components/organisms/PostFiles/PostFiles.Public.tsx
https://regennetwork.atlassian.net/browse/APP-279
---
1. Go to a post page of a post with files and verify that the files icons (the marker in the map) toggles the files window
I have...
=> fix: add state to control visibility of files window

.eslintrc.js, web-marketplace/src/config/contents.ts, web-marketplace/src/features/ecocredit/CreateBatchBySteps/hooks/useUpdateProjectOptions.ts, web-marketplace/src/features/marketplace/BridgeFlow/BridgeFlow.constants.ts, web-marketplace/src/features/marketplace/BridgeFlow/BridgeFlow.tsx, web-marketplace/src/features/marketplace/BridgeFlow/hooks/useCreditBridgeSubmit.tsx, web-marketplace/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.constants.ts, web-marketplace/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx, web-marketplace/src/features/marketplace/CreateSellOrderFlow/CreateSellOrderFlow.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/serviceWorker.ts, web-marketplace/src/siteMetadata.ts, web-marketplace/src/utils/components/ShareSection/getSocialItems.tsx
- translate features components
---
I have...
1.
I have...
=> feat: translate features

web-components/src/components/organisms/PostFiles/PostFiles.Public.tsx
https://regennetwork.atlassian.net/browse/APP-335
---
I have...
1. https://deploy-preview-2463--regen-marketplace.netlify.app/post/regen:13toVhek5wriSdpWzXyu4PUTvoAxuXuzmwjJLsbQbh7NrsZUEtinWTo.rdf
I have...
=> fix: APP-335 add icon for video files in data post map

web-marketplace/src/components/organisms/PostForm/PostForm.tsx
https://regennetwork.atlassian.net/browse/APP-358
---
I have...
1. Go to https://deploy-preview-2481--regen-marketplace.netlify.app/ and in the create a post modal upload a .pdf file to verify it doesn't overflow anymore - any other supported files should not overflow too.
I have...
=> fix: APP-358 add overflow-hidden class to PostForm gallery items

web-components/src/components/organisms/ConnectWallet/ConnectWallet.tsx, web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.PaymentOptions.tsx, web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.stories.tsx, web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.test.tsx, web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx, web-marketplace/src/components/organisms/LoginButton/LoginButton.tsx, web-marketplace/src/components/organisms/LoginFlow/LoginFlow.tsx, web-marketplace/src/components/organisms/LoginModal/LoginModal.tsx, web-marketplace/src/components/organisms/LoginModal/components/LoginModal.Select.tsx, web-marketplace/src/components/organisms/RegistryLayout/components/ConnectWalletModal/ConnectWalletModal.constants.ts, web-marketplace/src/components/organisms/RegistryLayout/components/ConnectWalletModal/ConnectWalletModal.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-marketplace/src/components/templates/ProjectDetails/hooks/useGetProject.ts, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx, web-marketplace/src/pages/BuyCredits/BuyCredits.tsx, web-marketplace/src/pages/BuyCredits/BuyCredits.utils.ts
Final splited PR for APP-204:
- Integrating the new buy credits page on project page (from the project card, this will be addressed in another task APP-365)
- Fixes some issues when fiat sell order ids mentioned in sanity might not be available anymore
---
I have...
1.
I have...
=> feat: APP-204 buy credits integration

web-marketplace/src/clients/Clients.constants.tsx, web-marketplace/src/clients/regen/Regen.Providers.tsx, web-marketplace/src/clients/terrasos/Terrasos.Providers.tsx
Make providers import lazy to avoid conflicts in CSS imports.
---
I have...
1.
I have...
=> fix: make provider import dynamic

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/PostForm/PostForm.tsx
=> chore: dev sync v2.7.3

web-components/src/components/form/NewsletterForm.tsx
https://regennetwork.atlassian.net/browse/WWW-6
I have...
1. Go to https://deploy-preview-2502--regen-website.netlify.app/ and at the bottom of the page chack that the subscription form works as expected.
I have...
=> fix: WWW-6 update newsletter subscription url

.eslintrc.js, web-components/src/components/atoms/CardRibbon/CardRibbon.tsx, web-components/src/components/buttons/ContainedButton.tsx, web-components/src/components/buttons/PrevNextButton.tsx, web-components/src/components/cards/CredibilityCard/CredibilityCard.tsx, web-components/src/components/cards/CredibilityCard/CredibilityCard.types.ts, web-components/src/components/cards/CredibilityCard/CredibilityCard.utils.ts, web-components/src/components/cards/ProjectImpactCard/ProjectImpactCard.tsx, web-components/src/components/icons/GreenPinIcon.tsx, web-components/src/components/icons/OutlinedCheckIcon.tsx, web-components/src/components/icons/utils/SvgColorOverride.tsx, web-components/src/components/organisms/ImpactTags/ImpactTags.tsx, web-components/src/components/organisms/ProjectTags/ProjectTags.tsx, web-components/src/utils/isString.ts, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx, web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.Post.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
Closes: [APP-306](https://regennetwork.atlassian.net/browse/APP-306?atlOrigin=eyJpIjoiNmIxYjIzYmEwODkzNGRkZGE0MTRlMjZjZmIzMTcyNjIiLCJwIjoiaiJ9
)
---
I have...
1.
I have...
[APP-306]: https://regennetwork.atlassian.net/browse/APP-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APP-306: update colors for project pages

web-components/src/components/cards/ProjectCard/ProjectCard.tsx, web-marketplace/src/components/organisms/TerrasosHeader/TerrasosHeader.constants.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx
hide unused elements:
- edit filters
- project card bottom
- more projects section
---
I have...
1.
I have...
=> feat: hide unused elements

web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx
https://regennetwork.atlassian.net/browse/APP-411
I have...
1. Go to https://deploy-preview-2511--regen-marketplace.netlify.app/project/mai-ndombe-4/buy, selected an amount of credits that is valid, click Next button and then on step 2 click the back to step 1 button.
2. The Next button should not be disabled.
I have...
=> fix: APP-411 use errors to set Next button state

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx, web-www/CHANGELOG.md, web-www/components/templates/Layout/Layout.config.ts, web-www/package-lock.json, web-www/package.json
dev sync v2.7.4
---
I have...
1.
I have...
=> chore: dev sync v2.7.4

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.Stakeholders.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx, web-marketplace/src/components/templates/ProjectDetails/hooks/useStakeholders.ts, web-marketplace/src/lib/db/types/json-ld/project-metadata.ts, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
Closes: https://regennetwork.atlassian.net/browse/APP-433
- adds new project stakeholders: owner, operator and monitor
- gets them from anchored metadata if on chain project else fallback to offchain project.metadata
---
I have...
1.
I have...
=> feat: add new project stakeholders

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/components/templates/ProjectDetails/hooks/useGetProject.ts, web-marketplace/src/pages/BuyCredits/BuyCredits.tsx
https://regennetwork.atlassian.net/browse/APP-412
---
I have...
1. Go to the marketplace and enter a random `slug/projectId` where the project Id goes in the URL (`https://deploy-preview-2521--regen-marketplace.netlify.app/project/PROJECT_ID_OR_SLUG_GOES_HERE/buy`, i.e: `https://deploy-preview-2521--regen-marketplace.netlify.app/project/xxxxx/buy`) and verify that the app redirects to the 404 page instead of the Buy credits flow.
I have...
=> feat: APP-412 add NotFoundPage when no project is found

web-marketplace/src/components/templates/MultiStepTemplate/StepperSection.tsx
https://regennetwork.atlassian.net/browse/APP-394
I have...
1. Check that when hover over step numbers the cursor remains the default cursor instead of the pointer: https://deploy-preview-2538--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
I have...
=> fix: APP-394 disable the cursor pointer on hover steps

web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.Retirement.tsx, web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.CustomerInfo.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
https://regennetwork.atlassian.net/browse/APP-395
I have...
1. https://deploy-preview-2535--regen-marketplace.netlify.app/project/C57-001/buy
I have...
=> feat: APP-395 hide in the UI the anonymous purchasing

web-marketplace/src/pages/Projects/Projects.tsx
Closes: APP-473
Keep consistent grid items on the projects page when page height changes (i.e., with filters).
---
I have...
1.
I have...
=> fix: APP-473 all projects grid items spacing with filters

web-marketplace/src/utils/sanity/getLocalizedData.ts
Closes: [APP-487](https://regennetwork.atlassian.net/browse/APP-487)
Fix Sanity localized data fallback.
---
I have...
1.
I have...
[APP-487]: https://regennetwork.atlassian.net/browse/APP-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: APP-487 sanity localized data fallback

web-components/src/components/cards/TebuCard/TebuCard.tsx
Closes: APP-479
Improve tooltip click zone on tebu factors.
---
I have...
1.
I have...
=> fix: improve tooltip click zone on tebu factors

web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.TebuInfo.tsx, web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.constants.tsx, web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.utils.tsx, web-marketplace/src/lib/db/types/json-ld/terrasos-project-metadata.ts, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
Closes: APP-486
Enable social and cultural card and change duration max value and tooltip for V4 projects.
---
I have...
1.
I have...
=> fix: APP-486 handle social and cultural card

web-marketplace/src/components/organisms/DetailsSection/DetailsSection.constants.ts, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.types.ts, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
Closes: APP-489
Handle custom description for Terrasos credibility card section.
---
I have...
1.
I have...
=> fix: handle custom description for terrasos credibility card section

web-marketplace/src/components/molecules/MetaDetail/MetaDetail.BaseValue.tsx, web-marketplace/src/components/molecules/MetaDetail/MetaDetail.tsx, web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.ComplianceInfo.tsx
Closes: APP-476
Improve `MetaDetail` layout.
---
I have...
1.
I have...
=> fix: improve MetaDetail layout

web-components/src/components/empty-state/EmptyState.tsx, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx, web-marketplace/src/pages/Projects/Projects.tsx
https://regennetwork.atlassian.net/browse/APP-493
---
I have...
1.
I have...
=> fix: APP-493 white box at the bottom of the projects page

.eslintrc.js, web-components/src/components/organisms/ImpactTags/ImpactTags.tsx, web-components/src/components/read-more/index.tsx, web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx, web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.StoryText.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.tsx, web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.tsx
Closes: APP-495
Fix project page spacing.
---
I have...
1.
I have...
=> fix: adjust spacing on project page

web-components/src/components/atoms/PlayPauseButton/PlayPauseButton.tsx, web-components/src/components/icons/PauseIcon.tsx, web-components/src/components/icons/PlayIcon.tsx, web-components/src/components/sliders/ProjectMedia.tsx
https://regennetwork.atlassian.net/browse/APP-506
---
I have...
Check data stream section at the bottom of https://deploy-preview-2564--terrasos.netlify.app/project/test-terrasos-project-2
I have...
=> fix: APP-506 update play/pause button color

web-marketplace/src/lib/i18n/locales/es.po
Some region names in Spanish were not capitalized.
---
I have...
Go to https://deploy-preview-2567--terrasos.netlify.app/projects/1, switch to spanish and make sure all region names are capitalized in the side filter bar.
I have...
=> fix: Terrasos region filter translations

web-components/src/components/user/UserInfo.tsx, web-components/src/components/user/UserInfoWithTitle.tsx
https://regennetwork.atlassian.net/browse/APP-453
I have...
1. Check in a project with stakeholders that the section looks aligned as expected. i.e:
- https://deploy-preview-2570--regen-marketplace.netlify.app/project/KSH01-001
- https://deploy-preview-2570--regen-marketplace.netlify.app/project/C74-005
- https://deploy-preview-2570--regen-marketplace.netlify.app/project/C61-001
I have...
=> fix: APP-353 stakeholders style

web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.ComplianceInfo.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
https://regen-network.slack.com/archives/C04NR9HSNCB/p1733868431999369
---
I have...
1.
I have...
=> fix: remove duplicate compliance info

web-components/src/components/banner/index.tsx, web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.tsx, web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.WarningBanner.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.tsx, web-marketplace/src/lib/atoms/banner.atoms.ts, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx, web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx
Closes: https://regennetwork.atlassian.net/browse/APP-408
---
I have...
Go https://deploy-preview-2578--regen-marketplace.netlify.app/project/C01-001/buy and login with keplr
Switch to "buy with crypto" and put a credit amount in REGEN that is higher 
- than the number of fiat credits available and switch to "buy with credit card"
- or the number of credits in another crypto currency and switch to this currency
in order to see the updated banner style and text
I have...
=> chore: APP-408 Change banner color and message when user switches between option that has more credits to option that has fewer credits

web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.CustomerInfo.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
https://regennetwork.atlassian.net/browse/APP-438
I have...
1. Go to step 2 of the buy credits flow and verify the wording has been updated.
2. https://deploy-preview-2579--regen-marketplace.netlify.app/project/C02-002/buy
I have...
=> fix: APP-438 change wording buy fiat flow

web-components/src/components/molecules/RoundLogoItemsList/RoundLogoItemsList.tsx, web-components/src/components/organisms/ImpactTags/ImpactTags.tsx, web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
https://regennetwork.atlassian.net/browse/APP-530
---
I have...
https://deploy-preview-2582--regen-marketplace.netlify.app/project/C02-001
I have...
=> fix: APP-530 spacing in Project top section

web-marketplace/src/components/organisms/Order/Order.Summary.Section.tsx, web-marketplace/src/components/organisms/Order/Order.Summary.tsx, web-marketplace/src/components/organisms/Order/Order.tsx, web-marketplace/src/components/organisms/OrderCryptoReceiptModal/OrderCryptoReceiptModal.Section.tsx, web-marketplace/src/components/organisms/OrderCryptoReceiptModal/OrderCryptoReceiptModal.constants.ts, web-marketplace/src/components/organisms/OrderCryptoReceiptModal/OrderCryptoReceiptModal.tsx, web-marketplace/src/components/organisms/OrderCryptoReceiptModal/OrderCryptoReceiptModal.types.ts, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx
https://regennetwork.atlassian.net/browse/APP-529
I have...
1. Go to https://deploy-preview-2586--regen-marketplace.netlify.app/
2. Login and go to My Orders
3. Verify that Orders using crypto have a receipt button that opens a modal window with the receipt information
I have...
=> feat: APP-529 receipt modal for crypto purchases

web-components/src/components/atoms/CardRibbon/CardRibbon.tsx, web-components/src/components/cards/CreditClassCard/CreditClassCard.tsx, web-components/src/theme/muiTheme.ts
https://regennetwork.atlassian.net/browse/APP-533
---
I have...
https://deploy-preview-2589--regen-marketplace.netlify.app/project/MBS01-001
I have...
=> fix: APP-533 credit class type and methodology layout

web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.schema.ts, web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.tsx
https://regennetwork.atlassian.net/browse/APP-472
---
I have...
1. Go to the last step of the buying credits flow and verify that toggling the checkbox doesn't throw any errors.
I have...
=> fix: APP-472 remove agreeerpa checkbox error

web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.CustomerInfo.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
https://regennetwork.atlassian.net/browse/APP-550
---
I have...
If logged in or a visiting user creating an account, the description of the name field in the payment info form should be "This name will appear on the retirement certificate, and is your user account name." instead of just "This name will appear on the retirement certificate."
I have...
=> chore: APP-550 update name description field in payment info form

web-marketplace/src/components/organisms/BasketOverview/hooks/useFetchEcocredit.ts, web-marketplace/src/lib/ecocredit/api.ts, web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx
https://regennetwork.atlassian.net/browse/APP-558
Closes: https://github.com/regen-network/rnd-dev-team/issues/1490 
There were actually only a few places where we needed to add it.
---
I have...
1.
I have...
=> chore: APP-558 add missing ecocredit client to getProject query

web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/BuyCredits/hooks/useFetchRetirementForPurchase.ts, web-marketplace/src/pages/BuyCredits/hooks/usePurchase.ts
https://regennetwork.atlassian.net/browse/APP-597
https://regennetwork.atlassian.net/browse/APP-602
---
I have...
1. Buy some crypto credits from C45-013 project
2. After successful purchase, you should be redirected to your portfolio page and check the credits are updated.
I have...
=> fix: APP-597 APP-602 reload credits after buying credits

web-marketplace/src/components/templates/MultiStepTemplate/MultiStep.context.tsx
https://regennetwork.atlassian.net/browse/APP-581
---
I have...
From https://deploy-preview-2607--regen-marketplace.netlify.app/project/C01-001/buy, click on the "next" button throughout the steps, it should scroll to the top of the page.
I have...
=> fix: APP-581 scroll to top of page on next

web-marketplace/src/lib/queries/react-query/registry-server/getPaymentMethodsQuery/getPaymentMethodsQuery.ts, web-marketplace/src/lib/queries/react-query/registry-server/getPaymentMethodsQuery/getPaymentMethodsQuery.utils.ts, web-marketplace/src/lib/wallet/hooks/useLogin.tsx, web-marketplace/src/lib/wallet/hooks/useLogout.tsx
https://regennetwork.atlassian.net/browse/APP-595
---
I have...
Buy some credits with credit card while being logged in with an account that has some saved payment methods. Log out while on the payment info form, the payment methods should disappear.
This also works the other way around: logging back in and the saved payment methods will re-appear.
I have...
=> fix: APP-595 invalidate payment methods query on login/logout

web-marketplace/src/pages/Projects/Projects.tsx
https://regennetwork.atlassian.net/browse/APP-547
I have...
1. Go to https://deploy-preview-2600--regen-marketplace.netlify.app/projects/1
2. Verify that the filter sidebar is sticky when scrolling and its shadow is visible.
3. When long list of filters is open, verify that there is no weird white space at the button as in image here: https://github.com/regen-network/regen-web/pull/2575#issuecomment-2590085978
I have...
=> fix: APP-547 UI issues on projects page

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx, web-marketplace/src/lib/atoms/languageSwitcher.atoms.ts
https://regennetwork.atlassian.net/browse/APP-614
---
I have...
1. Check the language switcher is hidden
2. If you have your browser default language set to Spanish, the app should remain in English
I have...
=> chore: APP-614 hide language switcher temporarily and always default to english

web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.utils.tsx
https://regennetwork.atlassian.net/browse/APP-612
I have...
1. Go to step 1 in the buy credits flow in a project where the price of 1 credit = 1 USD, for example: https://deploy-preview-2611--regen-marketplace.netlify.app/project/C01-007/buy
2. Enter `1.1` in the currency input and verify that the displayed credits value is `1.1`
3. Enter `1.11` in the currency input and verify that the displayed credits value is `1.11`
4. Test with other values (1.99, 2.55, etc.) to verify consistent precision.
5. Repeat the test for both crypto and fiat currency options.
6. Confirm that conversions between currency and credits remain accurate in all cases including …
=> fix: APP-612 improve credits calculation and currency formatting precision

web-marketplace/src/components/organisms/RegistryLayout/hooks/useShowOrders.tsx, web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx, web-marketplace/src/pages/BuyCredits/hooks/useFetchRetirementForPurchase.ts, web-marketplace/src/pages/BuyCredits/hooks/usePurchase.ts, web-marketplace/src/pages/Orders/hooks/useOrders.tsx
https://regennetwork.atlassian.net/browse/APP-596
---
I have...
From https://deploy-preview-2614--regen-marketplace.netlify.app/project/C01-001/buy
For all these cases, check orders on "My orders" page are reloaded after successful purchase
1. buy with credit card
2. buy with crypto, retired credits
3. buy with crypto, tradable credits
I have...
=> fix: APP-596 reload my orders after purchase

web-components/src/components/organisms/ProfileHeader/ProfileHeader.tsx
https://regennetwork.atlassian.net/browse/APP-584
I have...
1. Go to the marketplace and login
2. Open the profile page : https://deploy-preview-2617--regen-marketplace.netlify.app/dashboard/portfolio/
3. Verify the avatar picture is centered in small screens
I have...
=> fix: APP-584 adjust margin for ProfileHeader avatar

web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx, web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx, web-marketplace/src/pages/BuyCredits/hooks/useFetchRetirementForPurchase.ts, web-marketplace/src/pages/BuyCredits/hooks/usePurchase.ts
APP-616
---
I have...
Log in with an account that **doesn't have any name** and buy some credits.
You should not see the "payment info" form again after clicking purchase.
This is because when we recently added the ability to save the profile name from the payment info form, we were also reloading the profile data and this caused the whole page to reload (since the header depends on it) and go back to the last saved step.
I have...
=> fix: APP-616 refresh profile after processing so it doesn't reload the whole page

web-marketplace/src/generated/sanity-graphql.tsx, web-marketplace/src/graphql/sanity/AllProjects.graphql, web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx
https://regennetwork.atlassian.net/browse/APP-622
---
I have...
1. On /projects check that "credit card" buying filter option is available and it shows on chain projects with credit card purchase enabled, not only prefinance project like it's the case on dev currently: https://dev.app.regen.network/projects/1?buying_options_filters=credit_card
2. Select "crypto" and/or "credit card" filter and navigate through the pages, the filter should remain applied
I have...
=> fix: APP-622 /projects without credit card filter and pagination issue

web-components/src/components/inputs/new/ConfirmationCode/ConfirmationCode.tsx, web-marketplace/src/components/organisms/LoginFlow/hooks/useEmailConfirmationData.tsx
https://regennetwork.atlassian.net/browse/APP-585
I have...
https://deploy-preview-2624--regen-marketplace.netlify.app/
1. Go to the marketplace on an Android and an iPhone phones. 
2. Login with an email.
3. Check the confirmation email and copy the code. 
- Paste the code in the email confirmation modal by long pressing the first input field and then pressing 'paste' => Verify the login works as expected.
- Repeat the process but this time paste the code directly using the keyboard's suggestion bar => Verify the login works as expected.
- Repeat the process but this time introduce the code manually => Verify the login works as expected.
5. Go to …
=> fix: APP-585 one time password input

web-marketplace/src/pages/BuyCredits/hooks/useFetchRetirementForPurchase.ts
https://regennetwork.atlassian.net/browse/APP-618
1. Log in with an email.
2. Go to the Buy credits flow in the name field introduce a name with special characters, i.e: Sarah McFee #3
3. Verify that in the certificate the name is displayed correctly.
I have...
=> fix: APP-618 encode name parameter in certificate navigation URLs

web-components/src/components/header/components/UserMenuItem.Profile.tsx
https://regennetwork.atlassian.net/browse/APP-621
I have...
1. Verify that the user's name and avatar in profile dropdown has no shadow and colors are like in the comps. 
2. https://deploy-preview-2635--regen-marketplace.netlify.app/
I have...
=> fix: APP-621 update UserMenuItem user box avatar style

web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/Certificate/Certificate.tsx
https://regennetwork.atlassian.net/browse/APP-626
1. See https://github.com/regen-network/regen-web/pull/2636#issuecomment-2721336370
I have...
=> feat: APP-626 retirement certificate wording update

web-components/src/components/inputs/TextField.tsx, web-components/src/components/inputs/hooks/usePreventWheelScroll.tsx, web-components/src/components/inputs/new/TextField/TextField.tsx
https://regennetwork.atlassian.net/browse/APP-633
I have...
1. Verify that all numeric input fields in the marketplace do not change their value when focused and the user scrolls with the mouse wheel.
I have...
=> fix: APP-633 credit batch creation amounts shift

web-components/src/components/footer/index.tsx, web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.Item.tsx, web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.tsx, web-components/src/components/header/components/HeaderLogoLink.tsx, web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.Content.tsx, web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.tsx, web-components/src/components/header/components/NavLink.tsx, web-components/src/components/header/index.tsx, web-components/src/components/mobile-menu/index.tsx, web-www/components/organisms/MarketingNav/MarketingNav.tsx, web-www/components/templates/Layout/Layout.tsx
https://regennetwork.atlassian.net/browse/WWW-9
I have...
1. Verify GA is present across all pages
https://deploy-preview-2645--regen-website.netlify.app/
I have...
=> fix: WWW-9 use NextLink where MUI Link and <a> tags are used

web-components/src/components/modal/SadBeeModal/SadBeeModal.tsx, web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.ConnectedEmailErrorModal.tsx, web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.constants.ts, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po, web-marketplace/src/pages/BuyCredits/hooks/usePurchase.ts
https://regennetwork.atlassian.net/browse/APP-610
1. Log in with a web3 account with no email address.
2. When buying credits, provide an email address that is already used in another account.
3. Verify that the modal appears when clicking the "Next" button in step 2 (Payment Info).
4. Verify modal content has the new note at the bottom and the 'Learn more' button
**~~TODO:  We need to add the link to the guides in the 'Learn more' button~~**
I have...
=> feat: APP-610 move checking email to payment info step

web-components/src/components/cards/PostCard/PostCard.PrivateBadge.tsx, web-components/src/components/cards/PostCard/PostCard.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.Post.tsx, web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.DataStream.tsx
https://regennetwork.atlassian.net/browse/APP-682
I have...
https://deploy-preview-2656--regen-marketplace.netlify.app/project/C04-001#data-stream
I have created two posts, a private one and one with private files:
1. Verify that in the post with private files the title doesn't overlap the "Files are private" badge. 
2. Log in with the Testing account (Sarah McFee) and verify there is no issues in the private post either (we were having the same bug than in posts with private files)
I …
=> fix: APP-682 update PrivateBadge positioning in PostCard component

CHANGELOG.md, lerna.json, web-components/CHANGELOG.md, web-components/package.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-storybook/CHANGELOG.md, web-storybook/package.json, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync v2.9.0 (https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#5b52533e5fec45729a585611ba24c2bc)
---
I have...
1.
I have...
=> chore: dev sync v2.9.0

web-components/src/components/cards/ProjectCard/ProjectCard.types.ts, web-marketplace/src/hooks/projects/useProjectsWithOrders.ts, web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
https://regennetwork.atlassian.net/browse/APP-713
HOT FIX, do not merge from github
---
I have...
1. Check the estimated issuance on the prefinance project card https://deploy-preview-2667--regen-marketplace.netlify.app/projects/prefinance matches the one shown on the project page https://deploy-preview-2667--regen-marketplace.netlify.app/project/prefinance-project 
I have...
=> fix: APP-713 estimated issuance formatting in project card

web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx
https://regennetwork.atlassian.net/browse/APP-715
---
I have...
From https://deploy-preview-2669--regen-marketplace.netlify.app/, try to edit an offchain project from /dashboard/projects
I have...
=> fix: APP-715 project edit loading

CHANGELOG.md, lerna.json, web-components/CHANGELOG.md, web-components/package.json, web-components/src/components/cards/ProjectCard/ProjectCard.types.ts, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts, web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx, web-www/CHANGELOG.md, web-www/package-lock.json, web-www/package.json
dev sync PR (https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?source=copy_link#6047e1fbd4fc425c8d7a8ee101054c65) after latest hot fix releases https://github.com/regen-network/regen-web/blob/main/CHANGELOG.md#291-2025-06-04 and https://github.com/regen-network/regen-web/blob/main/CHANGELOG.md#292-2025-06-05
---
I have...
1.
I have...
=> chore: dev sync v2.9.1 and v2.9.2

CHANGELOG.md, lerna.json, web-marketplace/CHANGELOG.md, web-marketplace/package.json, web-marketplace/src/pages/Home/Home.tsx
dev sync PR for https://github.com/regen-network/regen-web/pull/2683
---
I have...
1.
I have...
=> chore: dev sync v2.9.5

web-marketplace/src/components/organisms/ConnectWalletFlow/ConnectWalletFlow.constants.ts, web-marketplace/src/components/organisms/ConnectWalletFlow/hooks/useConnectWalletToAccount.tsx, web-marketplace/src/lib/i18n/locales/en.po, web-marketplace/src/lib/i18n/locales/es.po
When trying to connect a wallet address to an existing account (from settings), we are checking any resulting error message to display certain modals, in particular the option to merge accounts when applicable. This was not displayed anymore because since we implemented i18n, we were comparing the error message from the server with the lingui message descriptor, instead of the raw string.
No Jira task, just found it out while working on something else and thought it would be a quick fix.
---
I have...
From https://deploy-preview-2685--regen-marketplace.netlify.app/, log in with a web2 account and try to connect a wallet address already used by …
=> fix: error msg checks when connecting a wallet to an existing account

web-marketplace/src/pages/BuyCredits/hooks/usePurchase.ts
https://regennetwork.atlassian.net/browse/APP-755
I have...
1.
I have...
=> fix: APP-755 handle invalid Stripe amount errors from backend

web-marketplace/netlify.toml, web-marketplace/next.config.mjs, web-marketplace/package.json, web-marketplace/public/_redirects
https://regennetwork.atlassian.net/browse/APP-769
I have...
1.
I have...
=> fix: APP-769 nextjs images missing

web-components/src/components/organisms/ProfileHeader/ProfileHeader.Infos.tsx, web-components/src/components/organisms/ProfileHeader/ProfileHeader.types.ts, web-marketplace/src/components/atoms/ToggleSwitch.tsx, web-marketplace/src/pages/Profile/Profile.tsx, web-marketplace/src/pages/Profile/ProjectsTab/NoProjectsDisplay.tsx
https://regennetwork.atlassian.net/browse/APP-737
---
I have...
1. Log in with email that has no projects and go to public profile. Make sure padding is correct on mobile and project tab shows when both logged in and out.
I have...
=> fix:  APP-737 empty state email profile

web-marketplace/src/components/organisms/Bridge/Bridge.tsx, web-marketplace/src/components/organisms/DashboardNavigation/DashboardNavigation.tsx, web-marketplace/src/components/organisms/DashboardNavigation/DashboardNavigation.types.tsx, web-marketplace/src/components/organisms/DashboardNavigation/DashboardNavigation.utils.tsx, web-marketplace/src/components/organisms/Portfolio/Portfolio.tsx, web-marketplace/src/components/organisms/SellOrdersTable/SellOrdersTable.tsx, web-marketplace/src/pages/Dashboard/Dashboard.tsx, web-marketplace/src/pages/Dashboard/MyCreditBatches/MyCreditBatches.Table.tsx, web-marketplace/src/pages/Dashboard/MyCreditBatches/MyCreditBatches.tsx, web-marketplace/src/pages/Dashboard/MyCreditClasses/MyCreditClasses.tsx
…nd credit batches
https://regennetwork.atlassian.net/browse/APP-763
---
I have...
1. Go to personal dashboard and make sure credit batches and credit classes shows when correct conditions are met. Make sure that Credit Classes shows only if your account has Credit Classes access enabled (your account is allowed to manage classes). Issued Credit Batches shows only if your account is an authorized issuer or already has issued batches. The “Credit issuance” section appears only if at least one of the above is true.
your handle next to the items reviewed if you …
=> feat: APP-763 Incorrectly showing credit classes on dashboard only if issuer
