web-registry/src/components/organisms/CreditBatches.tsx

Closes: regen-network/regen-registry#794
The header of the credit batch table is missing a row element (tr or TableRow) that wraps the cells (thead > tr > th)
---
I have...
I have...

Add missing TableRow component to the header of the credit batch table

---

web-registry/src/components/organisms/ProjectCards.tsx

Closes: regen-network/regen-registry#792
Removes the React.Fragment that wraps each item in the project card list (ProjectCards.tsx), to expose the underlying item components with the key property.
---
I have...
I have...

Fix item key warning on project cards, both desktop and mobile

---

web-components/src/components/table/TablePagination.tsx
web-components/src/components/table/table.stories.tsx
web-components/src/components/table/useTablePagination.ts

Closes: regen-network/regen-registry#807
Upgrading to MUI v5 has broken the page change function in the component. Simply rename the method/prop to `onPageChange` in a couple of locations.
https://mui.com/guides/migration-v4/#tablepagination
---
I have...
I have...

Fix pagination component upgrade

---

web-registry/src/lib/metadata-graph.ts
web-registry/src/pages/BatchDetails.tsx
web-registry/src/pages/CreditClassDetails.tsx

Closes: https://github.com/regen-network/regen-registry/issues/900
- The /metadata-graph API from the registry-server was previously
returning the metadata in a wrapped JSON object. It was decided
that we actually wanted a flat response. In other words, the API
just returns the metadata now, rather than { metadata: metadata}
- This PR also modified CreditClassDetails to use the same type of
async/await approach that BatchDetails was using. This improves
the consistency of how we are interacting with getMetadata. It
converted Promise.reject to a throw (again for async/await
consistency)
---
I have...
*All items are required. Please add a note if the …

Updates usage of metadata-graph API

---

web-registry/src/generated/json-ld/credit-class-metadata.ts
web-registry/src/generated/json-ld/index.ts
web-registry/src/pages/CreditClassDetailsSimple.tsx
web-registry/src/types/ledger/ecocredit.ts

Closes: regen-network/regen-registry#878
- Fixes missing metadata fields _Sectoral Scope_ and _Offset Generation Methods_
- Adds TS support for credit-class-metadata, derived from https://github.com/regen-network/regen-registry-standards/blob/main/jsonld/credit-classes/C01-verified-carbon-standard-class.json
https://deploy-preview-917--regen-registry.netlify.app/credit-classes/C01
---
I have...
I have...

Credit Class Metadata fix: Sectoral Scope and Offset Generation Methods

---

web-components/src/components/form/CreditRetireForm.tsx
web-registry/src/components/organisms/BuyCreditsModal.tsx
web-registry/src/components/organisms/CreditsPurchaseForm.tsx

Closes: regen-network/regen-registry#1022
Swap the order of the country and region location fields in the following files:
* CreditRetireForm
* BuyCreditsModal
* CreditsPurchaseForm
---
I have...
```
git …
```

chore: swap the order of the country and region location fields

---

web-registry/src/hooks/useEcocreditQuery.ts
web-registry/src/lib/ecocredit/api.ts

Just adds the query of a project to the ledger, since it is being requested in a couple of tasks, it is advanced independently
In order to do:
```
const { data: project } = useEcocreditQuery({
query: 'project',
params: { projectId: 'C02-002' },
});
```
---
I have... …

feat: add project ledger query

---

web-components/src/components/form/CreditSendForm.tsx
web-components/src/components/form/RecipientsForm.tsx
web-components/src/components/inputs/validation.ts

Closes: regen-network/regen-registry#1083
The validation for `amountTradable` is updated to allow it to be zero when doing a retirement in the `send` and `create batch` cases.
Each of these cases has a different implementation. 
* In one case (`send form`) a `validateAmount` util function has been updated (to optionally allow the value zero as valid)
* in the other case (`create batch form`) the validation rules of the corresponding `YUP` object have been updated.
---
I have...
your PR, `@Mergifyio …

Fix 1083 allow zero tradable amount when retirement

---

web-components/src/components/modal/BasketPutModal.tsx
web-components/src/components/modal/BasketTakeModal.tsx
web-components/src/components/modal/CreditRetireModal.tsx
web-components/src/components/modal/CreditSendModal.tsx
web-components/src/components/modal/TxSuccessfulModal.tsx
web-registry/src/lib/ecocredit/api.ts
web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.contants.ts
web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useBasketPutSubmit.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useBasketTakeSubmit.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditRetireSubmit.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditSendSubmit.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useOpenTakeModal.tsx

Closes: regen-network/regen-registry#1108
- fix empty modal title in confirmation modal on `MyEcoCredits`
- reduce the number of requests for `getEcocreditsForAccount` method
- fix a bug that was preventing take modal to be displayed
- refactor title variables name 
| Before  | After  |
|---|---|
| ~238 requests  | ~156 requests  |
|  ![before](https://user-images.githubusercontent.com/530644/184914804-a7c5cb9b-a639-4d4f-bb4c-05e8ef13b93a.png) |  ![after](https://user-images.githubusercontent.com/530644/184914841-90d44f0c-990d-44b2-ad03-09955df9c722.png) |
---
I have...
1. If …

fix: 1108 + take action bug + portfolio performance enhancement

---

web-components/src/components/banner/CookiesBanner.tsx
web-registry/src/App.tsx

Closes: https://github.com/regen-network/regen-registry/issues/1146
---
I have...
``` …
```

chore: add terms of service to cookie banner

---

web-registry/src/lib/ecocredit/api.ts
web-registry/src/lib/ecocredit/constants.ts

Closes: regen-network/regen-registry#1123
- Adds `v1alpha1` ecocredit message types to TX query for Activity table
- This restores historical activity in PROD
- the associated ledger patch is not in Redwood yet, so the deploy preview will not show the pre-upgrade activity
- This screenshot is of my localhost, pointed at mainnet. You can see the activity from 3 months ago in addition to the recent "CREATE CLASS"
---
I have...
2. If your branch does have …

fix: add v1alpha1 ecocredit messages to Activity tx query

---

web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx
web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.config.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts

Closes: regen-network/regen-registry#1167
- remove the expiration column (our sell orders don't have any currently)
- sort sell orders by id
---
I have...
```
git …
```

feat: remove expiration column and sort by id

---

netlify.toml
web-registry/public/_redirects

Fixes: https://github.com/regen-network/regen-web/pull/1176
I can't figure out a way to test this without merging to master, if someone knows a way that would be great. But I'm pretty sure I've got it right now, please review my comments.
---
I have...
```
git …
```

fix: use _redirects file syntax for registry to app redirect

---

web-registry/src/hooks/useEcocredits.ts
web-registry/src/hooks/useQueryBalances.ts
web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useUpdateCreditBaskets.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts

Closes: regen-network/regen-registry#1186
- reload user portfolio balance after doing an action
- fix racing condition while loading portfolio page
- reverse sort order on sell order table to have new sell order fist
- perform sort before doing batch info fetch
---
I have...
b. Create new branches for backports and merge `master` (replace `<PR#>` with …

feat: refresh portfolio data

---

web-registry/src/features/marketplace/BuySellOrderFlow.tsx

Closes: regen-network/regen-registry#1193
- display error banner while trying to buy a sell order and wallet is not connected
---
I have...
``` …
```

fix: show error banner on buy action when not connected

---

web-registry/src/pages/Marketplace/Storefront/Storefront.constants.ts
web-registry/src/pages/Marketplace/Storefront/Storefront.tsx

Closes: regen-network/regen-registry#1203
Quick fix for the buy sell order confirmation button for label and link.
---
I have...
``` …
```

fix: confirmation buy button label and link

---

web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx

Closes: regen-network/regen-registry#1235
- remove link on sell order id
---
I have...
```
git push …
```

fix: remove sell order id link

---

web-components/src/components/cards/ProjectTopCard.tsx
web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.utils.ts
web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx

Closes: regen-network/regen-registry#1062
(*) At the moment it just checks some harcoded addresses to see if it is RND and show as Project Admin 
---
I have...
``` …
```

feat: provisionally display RND as project admin

---

web-registry/src/components/organisms/CreditBatches/CreditBatches.tsx

Closes: regen-network/regen-registry#1264
Just move the key to the outermost element of the corresponding cell
---
I have...
``` …
```

fix: credit batches location column in project page

---

web-registry/src/components/organisms/CreditBatches/CreditBatches.tsx

Closes: regen-network/regen-registry#1195
(*) for the moment it checks that if there is no batch with Tx hash yet, the column is hidden
---
I have...
```
git …
```

fix: credit batches Tx column

---

web-registry/src/components/atoms/RegistryIconLink.tsx
web-registry/src/components/molecules/BackgroundImgSection.tsx
web-registry/src/pages/Home/Home.styles.tsx
web-registry/src/pages/Home/Home.tsx
web-registry/src/styles/gradients.ts

Closes: regen-network/regen-registry#1196
- update home page header
- fix issue with header logo on md breakpoint
---
I have...
``` …
```

feat: new homepage header

---

web-components/src/components/cards/ProjectCard/ProjectCard.styles.ts
web-registry/src/pages/Projects/Projects.tsx
web-registry/src/styles/spacing.ts

Closes: regen-network/regen-registry#1281
- fix projects page responsive
- extract header padding to make it reusable wherever we want to align content with the header logo
---
I have...
```
git push …
```

fix: projects page responsive issue

---

web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx

Closes: regen-network/regen-registry#1288
- remove $ prefix from sell orders table
---
I have...
``` …
```

feat: remove dollar prefix on sell orders

---

web-components/src/components/form/CreditRetireForm.tsx
web-components/src/components/form/CreditSendForm.tsx

- fix retire amount on retire modal (was removed in regen-network/regen-web#1300)
---
I have...
``` …
```

fix: amount input on retire form

---

web-registry/src/components/organisms/CreditTotals.tsx

Closes: regen-network/regen-registry#1273
- fix empty state for activity stats
---
I have...
```
git …
```

fix: empty state activity stats

---

web-components/src/components/cards/ProjectCard/ProjectCard.tsx
web-components/src/components/cards/ProjectCard/ProjectCard.types.ts
web-components/src/components/cards/card.stories.tsx
web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx
web-registry/src/features/marketplace/BuySellOrderFlow/hooks/useBuySellOrderData.tsx
web-registry/src/pages/Projects/hooks/useProjectsSellOrders.tsx
web-registry/src/pages/Projects/hooks/useProjectsSellOrders.utils.tsx

Closes: regen-network/regen-registry#1261
- remove own sell orders from `BuyCreditsModal`
- disabled button if a projects has only user own sell orders
---
I have...
``` …
```

fix: prevent user from buying its own orders

---

web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.tsx

- fix incorrect availability modal trigger
Video of issue: https://www.loom.com/share/5a5cf4519d6c4e8a9212eb18782613df 
---
I have...
``` …
```

fix: incorrect availability modal trigger

---

web-components/src/components/modal/TxModal.tsx

Closes: regen-network/regen-registry#1305
- Prevent card items to shrink on tx modal
---
I have...
```
git merge …
```

fix: prevent card items to shrink on tx modal

---

web-registry/src/hooks/useEcocredits.ts

Closes: regen-network/regen-registry#1238
* Add predicate function `hasBatchBalance` to filter the user's batches that currently have a balance (ie some amount such as tradable, retired, or escrowed). We want to hide the cases in which the user had only tradable credits but deposited them all in a basket.
---
I have...
your PR:
a. …

fix: filter user batches with current balance

---

web-components/src/components/tabs/IconTabs.tsx
web-registry/src/pages/Dashboard/Dashboard.tsx
web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx

Closes: regen-network/regen-registry#1300
After some discussion with @erikalogie we decided to go with a UI similar to what's on Open Sea for the tabs: https://monosnap.com/file/s8aLfFQIocpExopgLWeEpr5LJEkcnJ ie no space on the sides when scrolling but some spaces on the sides of the scrollable area
---
I have...
your PR:
a. Pull …

fix: profile tabs spacing

---

web-registry/src/components/organisms/WalletButton/WalletButton.tsx

Only show Keplr helper modal when using WalletConnect.
---
I have...
your PR:
```
git merge dev
git …
```

fix: display Keplr modal helper only when using walletconnect

---

web-registry/src/lib/tracker/types.ts
web-registry/src/pages/Dashboard/MyEcocredits/MyEcocredits.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditRetireSubmit.tsx

Closes: regen-network/regen-registry#1389
---
I have...
your PR:
```
git merge dev …
```

feat: add tracking for retire events

---

web-components/src/components/atoms/dummy/Dummy.tsx
web-components/src/components/molecules/StatCard/StatCard.stories.tsx
web-components/src/components/molecules/StatCard/StatCard.tsx
web-components/src/components/molecules/StatCard/StatCard.types.ts
web-components/src/components/molecules/StatCard/index.ts
web-components/src/components/organisms/Section/Section.tsx
web-components/src/components/organisms/StatCardsSection/StatCardsSection.constants.ts
web-components/src/components/organisms/StatCardsSection/StatCardsSection.mock.ts
web-components/src/components/organisms/StatCardsSection/StatCardsSection.stories.tsx
web-components/src/components/organisms/StatCardsSection/StatCardsSection.tsx
web-components/src/components/organisms/StatCardsSection/StatCardsSection.utils.ts
web-components/src/components/organisms/StatCardsSection/index.ts
web-components/src/components/sliders/ResponsiveSlider.tsx
web-storybook/public/illustrations/carbon-credit.svg

Part of: regen-network/regen-web#1793
Add 2 new components needed for the home page revamp:
- StatCard
- StatsCardsSection (infinite grid of StatCard)
The content of this PR will also be added to `react-17` branch.
---
I have...
1. https://deploy-preview-1811--regen-storybook.netlify.app/?path=/story/organisms-statcardssection--default
I have...

feat: add StatCard and StatsCardsSection

---

web-registry/src/lib/db/api/metadata-graph.ts
web-registry/src/lib/rdf/rdf.compact.ts
web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx

Ref: https://regen-network.slack.com/archives/C01LX9E8QN8/p1679596011497989
**HOTFIX**
**IMPORTANT NOTE: per our [Release process document](https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#3406c219896c4d3eaba9f1a14e1b5fc8), this shouldn't be merged here via Github UI but manually once approved.**
The new credit class metadata updates related to the regen IRI prefix change have been broadcasted but the front-end code is not yet ready to support it (in prod) since it's still expecting `regen` to be `http://regen.network/` instead of the new `https://schema.regen.network#` (see related PR: https://github.com/regen-network/regen-web/pull/1820 that will be included as part of the next release).
This is a hotfix to set the JSON-LD …

fix: use new regen IRI for compacting credit class metadata

---

web-registry/src/lib/queries/react-query/coingecko/simplePrice/simplePriceQuery.ts
web-registry/src/lib/queries/react-query/coingecko/simplePrice/simplePriceQuery.types.ts
web-registry/src/lib/queries/react-query/ecocredit/marketplace/getSellOrdersExtendedQuery/getSellOrdersExtendedQuery.ts
web-registry/src/pages/Marketplace/Storefront/Storefront.utils.ts
yarn.lock

Closes: regen-network/regen-registry#1630
- display project card when coingecko is unavailable
- do not display invalid prices on storefront when coingecko is unavailable
---
I have...
1.
I have...

fix: handle coingecko api failure

---

web-registry/src/components/organisms/BasketDetailsActionsBar/BasketDetailsActionsBar.constants.ts

After discussing this with @clevinson, before NCT pool launches (regen-network/regen-registry#1624), the "buy tokens" button should rather link to our "Polygon to Regen Ledger" guides and rename "buy NCT".
This should be included in the next release.
cc/ @erikalogie 
---
I have...
https://deploy-preview-1850--regen-registry.netlify.app/baskets/eco.uC.NCT
I have...

chore: update basket buy tokens link

---

web-registry/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts

Closes: #1848
- hide ecocredits when the user has a balance of 0 of all 3 fields (tradable, retired, escrowed).
---
I have...
1. go to https://deploy-preview-1853--regen-registry.netlify.app/ecocredits/accounts/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
2. Check that there's no line in the table without value on all 3 balance columns
I have...

fix: hide ecocredit batch when no balance

---

web-registry/src/apollo.tsx
web-registry/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-registry/src/pages/Dashboard/Dashboard.tsx
web-registry/src/pages/Dashboard/Dashboard.utils.tsx
web-registry/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
web-registry/src/pages/ProfileEdit/ProfileEdit.tsx
web-registry/src/pages/ProfileEdit/hooks/usePartyInfos.tsx

Closes: regen-network/regen-registry#1645
- Display profile on the public account page
- Use avatar from profile in the header
- fix a race condition in Apollo client init
---
I have...
1. Default public profile: https://deploy-preview-1857--regen-registry.netlify.app/ecocredits/accounts/regen1typewgr0qksjl0m2r0cal530zl0g835wsunxna/portfolio
2. Shared account public profile: https://deploy-preview-1857--regen-registry.netlify.app/ecocredits/accounts/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
your handle next to the items reviewed if you only reviewed …

fix: display profile header on public page

---

web-registry/src/components/organisms/ProjectCards.tsx
web-registry/src/lib/queries/react-query/registry-server/graphql/getMoreProjectsQuery/getMoreProjectsQuery.ts
web-registry/src/lib/queries/react-query/registry-server/graphql/getMoreProjectsQuery/getMoreProjectsQuery.types.ts
web-registry/src/lib/rdf/rdf.constants.ts
web-registry/src/pages/CreditClassDetails/CreditClassDetailsWithContent/CreditClassDetailsWithContent.tsx

Closes: regen-network/regen-registry#1699
A quicker fix would have been just to add `@value` to `project.metadata?.['regen:previewPhoto']?.['schema:url']` in https://github.com/regen-network/regen-web/blob/1956f70d788c79718992caeb048f199f64295ae3/web-registry/src/components/organisms/ProjectCards.tsx#L84 (since the incoming project metadata wasn't compacted which was causing the error) but decided to migrate the `MoreProjects` query to use react-query and compact the project metadata from there so it's more efficient and more consistent with our way to deal with jsonld metadata.
---
I have...
1.
_All items are required. Please add a note if the item …

fix: project card on credit class page

---

web-components/src/components/table/ActionsTable.tsx
web-components/src/components/table/Table.TablePagination.tsx

Closes: regen-network/regen-registry#1662
Remove hidden from current pagination count.
---
I have...
1. Go to https://deploy-preview-1906--regen-registry.netlify.app/ecocredits/accounts/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
2. navigate to page `21-24`
I have...

fix: pagination credit batches

---

web-registry/src/components/molecules/DenomLabel/DenomLabel.tsx
web-registry/src/components/molecules/DenomLabel/DenomLabel.utils.ts
web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.utils.tsx
web-registry/src/components/organisms/SellOrdersTable/SellOrdersTable.Row.tsx
web-registry/src/config/allowedBaseDenoms.ts

Closes: regen-network/regen-registry#1705
- fix EEUR denom display
- use `baseDenom`from `denomTrace` as fallback a denom label can't be found in the allowed list
---
I have...
1. https://deploy-preview-1910--regen-registry.netlify.app/
I have...

fix: use base denom as fallback

---

web-registry/src/components/organisms/BuyCreditsModal/BuyCreditsModal.tsx
web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
web-registry/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts
web-registry/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-registry/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
web-registry/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx
web-registry/src/pages/Marketplace/Storefront/Storefront.tsx

Closes: regen-network/regen-registry#1732
Disable OTC flow for community credit for the following pages:
- project details
- credit class
---
I have...
1. Project details: https://deploy-preview-1932--regen-registry.netlify.app/credit-classes/C46
2. Credit class details: https://deploy-preview-1932--regen-registry.netlify.app/project/C46-001 
I have...

feat: disable OTC flow for community credits

---

web-components/src/components/cards/CreditClassCard/CreditClassCard.Item.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetails.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.constants.ts
web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetailsSimple/hooks/useCreditClassDetails.tsx

Closes: regen-network/regen-registry#1721
Added the following items to the credit class page:
- credit type
- credit offset generation methods
- credit class tooltip
Also, refactor some old queries to react-query.
---
I have...
1. Single offset method: https://deploy-preview-1968--regen-registry.netlify.app/credit-classes/C02
2. Several offset methods: https://deploy-preview-1968--regen-registry.netlify.app/credit-classes/C01
I have...

feat: update credit class page

---

web-registry/src/components/organisms/BasketOverview/hooks/useBasketPutData.tsx
web-registry/src/hooks/useBasketTokens.ts
web-registry/src/hooks/useEcocredits.ts
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useCreditSendSubmit.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useFetchBaskets.tsx
web-registry/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts

Closes: #1950
---
I have...
Use our testing account regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46
Go to https://dev.app.regen.network/ecocredits/portfolio, on the ecocredits table last page (), you should see you have some tradable credits for C01-001-20170607-20220622-022, while your tradable balance for this batch is 0: http://redwood.regen.network:1317/regen/ecocredit/v1/balances/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46
Go to https://deploy-preview-1979--regen-registry.netlify.app/ecocredits/portfolio, you shouldn't see any row for C01-001-20170607-20220622-022 anymore.
_All items are required. Please add a note if the item is not applicable …

fix: batch balances which didn't always correspond to batches on portfolio ecocredits table

---

web-registry/src/components/molecules/MetaDetail/MetaDetail.BaseValue.tsx
web-registry/src/components/molecules/MetaDetail/MetaDetail.tsx
web-registry/src/components/molecules/MetaDetail/MetaDetail.utils.ts
web-registry/src/lib/db/types/json-ld/credit-class-metadata.ts
web-registry/src/lib/rdf/rdf.unknown-fields.ts
web-registry/src/pages/CreditClassDetails/CreditClassDetails.AdditionalInfo.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetails.ApprovedMethodologies.tsx
web-registry/src/pages/CreditClassDetails/CreditClassDetails.BufferPoolAccounts.tsx

Closes: regen-network/regen-registry#1756
---
I have...
https://deploy-preview-1980--regen-registry.netlify.app/credit-classes/C62
I have...

feat: Credit Class Page "Additional Info" improvements

---

web-registry/src/pages/ChooseCreditClass/ChooseCreditClass.Item.tsx
web-registry/src/pages/ChooseCreditClass/ChooseCreditClass.tsx
web-registry/src/pages/ChooseCreditClass/hooks/useGetCreditClassOptions.tsx

Closes: regen-network/regen-registry#1758
Also now uses the image from the credit class metadata too as in other places.
---
I have...
1. Go to https://deploy-preview-1987--regen-registry.netlify.app/ecocredits/projects and login with an address that is an issuer of at least one credit class
2. Click "Create project"
3. On "Choose credit class" page, you should see the credit classes you're an issuer for (the query is a bit long since it queries for all credit classes and then the issuers for all the credit classes in separate queries and we have quite a lot of credit classes on redwood...)
_All items are required. Please add a note if the item is …

fix: only display classes that the user is an issuer for on ChooseCreditClass

---

web-registry/src/lib/wallet/walletsConfig/walletsConfig.ts

Related: regen-network/regen-web#1982
This is an experimental PR.
Keplr does not currently have great support for displaying human-readable proto sign-docs for custom messages.
But their docs indicate that you can use the amino API to achieve this.
This PR does this by always using `getOfflineSignerOnlyAmino`, even for proto messages. I'm not sure if this is the direction we want to go, but it is worth testing and discussing.
**Before**
**After**
---
I have...
your PR:
- If PR is a new feature: …

feat: use getOfflineSignerOnlyAmino to see human readable message details

---

web-components/src/components/form/CreateSellOrderForm.tsx
web-components/src/components/inputs/validation.ts

Closes: regen-network/regen-registry#1664
---
I have...
1. Go to https://deploy-preview-1996--regen-registry.netlify.app and login with an address that has some credits
2. Go to your /ecocredits/portfolio
3. Try to create a sell order with a decimal price
I have...

fix: Warning when inputing decimal price values in "Create Sell Order" form

---

web-www/.prettierignore
web-www/pages/index.tsx

Closes: https://github.com/regen-network/rnd-dev-team/issues/1671
Adds GA4 tag to web-www via `NEXT_PUBLIC_GA_MEASUREMENT_ID` which will need to be set to `G-N7DHYF5D4J` in production.
---
I have...
1. Check out the branch and set the env var
2. Navigate to the Regen Network Website GA4 tag in Google Analytics, go to "realtime"
3. Click around in the local website, and observe your data being collected.
Our tag reported that data collection works with this set up:
I have...

feat: add new website GA4 tag

---

web-components/src/components/cards/ProjectCard/ProjectCard.tsx

regen-network/rnd-dev-team#1771
- use uppercase for avg price label
---
I have...
1. https://deploy-preview-2030--regen-marketplace.netlify.app/
I have...

fix: use uppercase for avg pricel label

---

web-www/pages/404.tsx

Closes: #2020
This pull request adds a `404.tsx` file with a `Custom404` function as instructed in the nextjs documentation that renders the existing `NotFound` component view.
---
I have...
1. https://deploy-preview-2032--regen-website.netlify.app/foo
I have...

fix: not found page

---

web-marketplace/src/components/organisms/BasketOverview/hooks/useFetchEcocredit.ts
web-marketplace/src/components/organisms/BridgedEcocreditsTable/hooks/useFetchBridgedEcocredits.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.loader.ts
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/hooks/batches/usePaginatedBatches.ts
web-marketplace/src/hooks/batches/usePaginatedBatchesByProject.ts
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/lib/normalizers/creditClass/normalizeCreditClassItems.ts
web-marketplace/src/lib/normalizers/creditClass/normalizeCreditClassItems.types.ts
web-marketplace/src/lib/normalizers/creditClass/normalizeCreditClassOption.ts
web-marketplace/src/lib/normalizers/creditClass/normalizeCreditClassOptions.types.ts
web-marketplace/src/lib/queries/react-query/registry-server/graphql/getAllCreditClassesQuery/getAllCreditClassesQuery.constants.ts
web-marketplace/src/lib/queries/react-query/registry-server/graphql/getAllCreditClassesQuery/getAllCreditClassesQuery.ts
web-marketplace/src/lib/queries/react-query/registry-server/graphql/getAllCreditClassesQuery/getAllCreditClassesQuery.types.ts
web-marketplace/src/lib/queries/react-query/sanity/getAllCreditClassesQuery/getAllCreditClassesQuery.ts
web-marketplace/src/pages/BasketDetails/hooks/useFetchBasketEcocredits.ts
web-marketplace/src/pages/Buyers/hooks/useFetchProjectsByIds.ts
web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx
web-marketplace/src/pages/ChooseCreditClass/hooks/useGetCreditClassOptions.tsx
web-marketplace/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts
web-marketplace/src/pages/Home/Home.loader.ts
web-marketplace/src/pages/Home/hooks/useCreditClasses.ts
web-marketplace/src/pages/Marketplace/Storefront/Storefront.loader.ts
web-marketplace/src/pages/Marketplace/Storefront/hooks/useNormalizedSellOrders.tsx
web-marketplace/src/pages/Projects/Projects.tsx
web-marketplace/src/pages/Projects/hooks/useFetchCreditClasses.tsx

Closes: regen-network/regen-web#2000
- Improve loading performance for `Choose a credit class`
- rename `getAllCreditClassesQuery` to `getAllSanityCreditClassesQuery` to avoid name conflicts with `getAllCreditClassesQuery` from the graphql server
---
I have...
1. Go to https://deploy-preview-2049--regen-marketplace.netlify.app/ecocredits/projects
2. Click create project
I have...

feat: credit classes issuers perf

---

web-marketplace/src/components/organisms/MediaForm/MediaFormPhotos.tsx
web-marketplace/src/pages/Media/Media.tsx

Closes: regen-network/regen-registry#1775
- Allow to submit form after uploading a preview photo
- Handle old metadata schema for `regen:previewPhoto` (string instead of object)
---
I have...
1.
I have...

fix: trigger form validation on preview photo upload

---

web-components/src/components/section/OnBoardingSection.tsx
web-marketplace/src/components/molecules/Form/Form.tsx
web-marketplace/src/components/organisms/BasicInfoForm/BasicInfoForm.tsx
web-marketplace/src/components/organisms/DescriptionForm/DescriptionForm.tsx
web-marketplace/src/components/organisms/LocationForm/LocationForm.tsx
web-marketplace/src/components/organisms/MediaForm/MediaForm.tsx
web-marketplace/src/components/organisms/MetadataForm/MetadataForm.tsx
web-marketplace/src/components/organisms/RolesForm/RolesForm.tsx
web-marketplace/src/components/templates/ProjectFormTemplate/OnboardingFormTemplate.tsx
web-marketplace/src/hooks/projects/useProjectWithMetadata.ts
web-marketplace/src/pages/BasicInfo/BasicInfo.tsx
web-marketplace/src/pages/Description/Description.tsx
web-marketplace/src/pages/Media/Media.tsx
web-marketplace/src/pages/ProjectCreate/ProjectCreate.tsx
web-marketplace/src/pages/ProjectCreate/hooks/useProjectSaveAndExit.ts
web-marketplace/src/pages/ProjectLocation/ProjectLocation.tsx
web-marketplace/src/pages/ProjectMetadata/ProjectMetadata.tsx
web-marketplace/src/pages/ProjectMetadata/hooks/useProjectMetadataSubmit.tsx
web-marketplace/src/pages/Roles/Roles.tsx
web-marketplace/src/pages/Roles/hooks/useRolesSubmit.tsx

Closes: regen-network/regen-registry#553
- Enable `Save & Exit` in all project forms
---
I have...
1. Go to https://deploy-preview-2078--regen-marketplace.netlify.app/ecocredits/projects
2. Create a project and try the `Save & Exit` feature in the different steps
I have...

fix: handle save and exit in creation form

---

web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormAccessTemplate.tsx
web-marketplace/src/pages/ChooseCreditClass/ChooseCreditClass.tsx

Fixing a bug that got introduced as part of https://github.com/regen-network/regen-web/pull/2060
---
I have...
This bug was causing the choose credit class page to always render 404 because the offchain project wasn't provided. Try to create a new project and everything should work back again normally.
I have...

fix: update offchainProject props in ChooseCreditClass

---

web-marketplace/graphql.schema.json
web-marketplace/src/components/organisms/RolesForm/RolesForm.schema.ts
web-marketplace/src/components/organisms/RolesForm/components/ProfileModal/ProfileModal.schema.ts
web-marketplace/src/components/organisms/RolesForm/components/RoleField/RoleField.styles.ts
web-marketplace/src/components/organisms/RolesForm/components/RoleField/RoleField.tsx
web-marketplace/src/components/organisms/RolesForm/components/RoleField/RoleField.utils.tsx
web-marketplace/src/components/organisms/RolesForm/hooks/useSaveProfile.tsx
web-marketplace/src/generated/graphql.tsx
web-marketplace/src/graphql/AccountById.graphql
web-marketplace/src/graphql/ProjectByHandle.graphql
web-marketplace/src/pages/Roles/Roles.utils.ts
web-marketplace/src/pages/Roles/hooks/useRolesSubmit.tsx

Closes: regen-network/regen-registry#1727
---
I have...
Create a new project or go to an existing project from https://deploy-preview-2100--regen-marketplace.netlify.app/profile/projects
Go to the Roles form and add a new profile for project developer or verifier.
You should then see the "edit profile" below the field, click and try to edit the profile.
Please be aware that "edit profile" won't get displayed for profiles that got added from the Roles form before this PR since we didn't assign a creator_id to those at the time. This has been added as part of this work to ensure that only the creator of a profile can edit it (until it's claimed by …

feat: edit profiles created with the Project Roles Form

---

package.json

Closes: regen-network/regen-web#1803
- rename `bump` command to `bump-and-push`
- add `bump` command using `no-push` option
Release process document has been updated accordingly.
---
I have...
1.
I have...

fix: disable default push with lerna bump

---

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
web-marketplace/src/hooks/projects/UseCreateOrUpdateProject.ts
web-marketplace/src/lib/env.ts
web-marketplace/src/lib/normalizers/retirements/normalizeRetirement.ts
web-marketplace/src/pages/Dashboard/Dashboard.tsx
web-marketplace/src/pages/Dashboard/Dashboard.utils.tsx
web-marketplace/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx
web-marketplace/src/pages/ProfileEdit/ProfileEdit.utils.ts
web-marketplace/src/utils/image/getResizedImageUrl.ts

Closes: regen-network/rnd-dev-team#1713
- use resized images for profile (public and private) and gallery
---
I have...
1. https://deploy-preview-2106--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
In this example, we went from: 
- background image: 1.7 MB -> 30 kB
- profile: 373 kB -> 1.7 kB
I have...

feat: use resized image on profile and gallery

---

web-marketplace/src/hooks/projects/UseCreateOrUpdateProject.ts
web-marketplace/src/pages/Roles/Roles.tsx
web-marketplace/src/pages/Roles/hooks/useRolesSubmit.tsx

Closes: regen-network/regen-registry#1791
---
I have...
Moving forward, this should prevent projects to have a null admin_wallet_id (which causes the 401 when trying to upload an image since we check that this is the project admin that does upload the image using the off-chain admin_wallet_id).
For existing projects without any admin_wallet_id, this should be updated manually in the db (which was the case for projects created on staging when the project creation/edit flows weren't updated to use the keplr login system).
your handle next to the items reviewed if …

fix: make sure project admin wallet id is always set

---

web-marketplace/src/pages/ProjectMetadata/hooks/useProjectMetadataSubmit.tsx
web-marketplace/src/pages/ProjectReview/ProjectReview.tsx

Closes: #2084
The issue described in #2084 can happen as soon as you completely overwrite the metadata as part of the metadata form, meaning that the context was getting overwritten too, which causes the part of the `@context` related to the unanchored metadata to be lost, causing issues with some unanchored metadata fields which require some `@context` (eg for defining a field as a `@list`).
This is because the current metadata form wasn't meant for overwriting the metadata completely, eg providing fields such as `schema:name` that already get filled up as part of other forms, but it was meant primarily for adding custom fields that cannot be provided with other forms. Now it should just supports both use cases.
---
_All items are required. Please add a note to the item if the item is …

fix: update project metadata submit to account for @context overwrite

---

web-marketplace/src/components/organisms/BuyModalOptions/BuyModalOptions.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.ConnectWalletModal.tsx
web-marketplace/src/features/marketplace/BuySellOrderFlow/BuySellOrderFlow.tsx

Closes: regen-network/regen-web#2120
Check that the user as an account id in addition to an address to show the buy-sell orders modal.
---
I have...
1. https://deploy-preview-2128--regen-marketplace.netlify.app/
2. Try to log but to not validate the sign arbitrary transaction
3. Click on the buy button on one of the cards
4. You should see the buy modal options instead of the buy-sell orders modal
I have...

fix: buy modal options trigger

---

web-marketplace/graphql.schema.json
web-marketplace/src/generated/graphql.tsx
web-marketplace/src/graphql/AllProjects.graphql
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/pages/Projects/Projects.OffChainFilter.tsx
web-marketplace/src/pages/Projects/Projects.SideFilter.tsx
web-marketplace/src/pages/Projects/Projects.constants.ts
web-marketplace/src/pages/Projects/Projects.tsx
web-marketplace/src/pages/Projects/hooks/useOffChainProjects.tsx
web-marketplace/src/pages/Projects/hooks/useProjects.tsx

Closes: regen-network/regen-web#2077
- display off-chain projects on `/projects`
- add off-chain projects filter
---
I have...
1. https://deploy-preview-2101--regen-marketplace.netlify.app/projects/1
2. toggle both filters to see off-chains projects
I have...

feat: add off-chain projects to projects page

---

package.json
web-components/src/components/cards/ProjectImpactCard/ProjectImpactCard.tsx
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.Hover.tsx
web-components/src/components/inputs/new/LocationField/LocationField.styles.ts
web-components/src/components/modal/TxModal.CardItemValue.tsx
web-components/src/components/pagination/Pagination.tsx
web-components/src/types/vite.d.ts
web-components/tsconfig.json
yarn.lock

Closes: regen-network/rnd-dev-team#1806
- bump typescript to latest version (`5.2.2`)
- clean some lints
---
I have...
1.
I have...

chore: bump typescript and clean lint

---

web-components/src/components/cards/MediaCard.tsx

Closes: regen-network/rnd-dev-team#1807
---
I have...
Testing on desktop:
https://deploy-preview-2163--regen-marketplace.netlify.app/projects/3 On this particular page, all titles take only one line so the location is moved higher everywhere
On https://deploy-preview-2163--regen-marketplace.netlify.app/projects/2, the first row of projects has at least one project title with 2 lines so the locations in this row are moved down so they all align, while the second row has projects titles with 1 line so the location is just displayed right below the title without any additional space.
This behavior can also be tested from the "More Projects" on …

fix: project card title height

---

web-marketplace/src/components/organisms/EcocreditsTable.tsx
web-marketplace/src/pages/Dashboard/MyEcocredits/hooks/useFetchEcocredits.ts

Closes: regen-network/regen-web#2097
- display ecocredits table when the first page is full of ghost credits.
The problem here was, for this specific account on main net, about ghost credits (empty balances on credits that used to have one returned by the ledger). We took the decision to hide those ghost credits before so we ended up with a first page without credit and the empty state was displayed for that reason.
In this PR we display the table if there are no rows on the first page but the table has more pages.
---
I have...
1.
your handle next to the items …

fix: ecocredit table with ghost credits on first page

---

web-components/src/components/inputs/new/AmountField/AmountField.tsx
web-marketplace/src/components/organisms/CreateSellOrderForm/CreateSellOrderForm.tsx

Closes: regen-network/regen-web#2179
- defined onClick handler for max button in `CretaeSellOrderForm`
- set max value for `<AmountField />`
---
I have...
1. https://deploy-preview-2184--regen-marketplace.netlify.app/profile/portfolio
I have...

fix: max button for create sell order

---

web-marketplace/src/components/organisms/RolesForm/RolesForm.schema.ts
web-marketplace/src/components/organisms/RolesForm/RolesForm.tsx
web-marketplace/src/components/organisms/RolesForm/components/AdminModal/AdminModal.schema.ts
web-marketplace/src/components/organisms/RolesForm/components/ProfileModal/ProfileModal.schema.ts
web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormAccessTemplate.tsx
web-marketplace/src/components/templates/ProjectFormTemplate/ProjectFormTemplate.tsx
web-marketplace/src/hooks/projects/UseCreateOrUpdateProject.ts
web-marketplace/src/hooks/projects/useProjectWithMetadata.ts
web-marketplace/src/lib/queries/react-query/registry-server/graphql/getProjectByIdQuery/getProjectByIdQuery.constants.ts
web-marketplace/src/pages/BasicInfo/BasicInfo.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx
web-marketplace/src/pages/Dashboard/MyProjects/hooks/useFetchProjectsByAdmin.tsx
web-marketplace/src/pages/Media/Media.tsx
web-marketplace/src/pages/ProjectEdit/ProjectEdit.Nav.tsx
web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx
web-marketplace/src/pages/ProjectEdit/hooks/useProjectEditSubmit.tsx
web-marketplace/src/pages/ProjectFinished/ProjectFinished.tsx
web-marketplace/src/pages/ProjectMetadata/ProjectMetadata.tsx
web-marketplace/src/pages/ProjectReview/ProjectReview.tsx
web-marketplace/src/pages/ProjectReview/hooks/useProjectCreateSubmit.tsx
web-marketplace/src/pages/Projects/Projects.types.ts
web-marketplace/src/pages/Roles/Roles.tsx
web-marketplace/src/pages/Roles/hooks/useRolesSubmit.tsx
web-marketplace/src/pages/Settings/Settings.tsx

Closes: #2161
For projects without credit class:
- Removes the metadata form
- At the end of the create flow, do not submit the project on chain but just set it as "published" off-chain
- Do not submit any on-chain data when editing published off chain projects but keep storing everything off-chain
Also fixes: #2177 a bug that I came across while working on this
---
I have...
Go to https://deploy-preview-2178--regen-marketplace.netlify.app/ and login with a class issuer/project admin.
From https://deploy-preview-2178--regen-marketplace.netlify.app/profile/projects:
1. Create a new project with a credit class and make sure the entire flow still works …

feat: update create/edit project forms to handle projects without credit class

---

netlify.toml
web-marketplace/sanity-graphql.schema.json
web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx
web-marketplace/src/generated/sanity-graphql.tsx
web-marketplace/src/graphql/sanity/AllHomePage.graphql
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
web-marketplace/src/pages/Home/Home.FeaturedProjects.tsx
web-marketplace/src/pages/Home/Home.tsx
web-marketplace/src/pages/Home/hooks/useFeaturedProjects.ts
web-marketplace/src/pages/Projects/Projects.types.ts
web-marketplace/src/pages/Projects/utils/sortProjects.ts

Closes: regen-network/rnd-dev-team#1811
Needs: https://github.com/regen-network/regen-sanity/pull/49
Add the possibility to pin projects to the featured projects section on the registry homepage.
`useProjectsWithOrders` now accepts a `pinnedIds` prop to enable this feature.
---
I have...
1. https://deploy-preview-2191--regen-marketplace.netlify.app/
2. For devs: Try to change the featured projects in sanity staging (note that off-chain projects will need to be validated and published).
your handle next to the items reviewed if you only reviewed selected …

feat: add pinnedIds to useProjectsWithOrders

---

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-marketplace/src/pages/Dashboard/Dashboard.tsx
web-marketplace/src/pages/Dashboard/hooks/useProfileItems.tsx

Closes: regen-network/regen-web#2205
Hide credit class entry in the user dropdown menu if the user has no credit class.
The credit class item was displayed in the user menu because if the allowed list param is not activated on the current chain, we display it by default. See [this hook](https://github.com/regen-network/regen-web/blob/dev/web-marketplace/src/hooks/useQueryIfCreditClassCreator.ts#L32) for more info.
The tab was not displayed in the user profile because we also checked the number of credit classes created there. This PR adds the same check for the user menu entry.
---
I have...
1. …

fix: hide credit class entry if no credit class

---

web-marketplace/src/components/organisms/UserAccountSettings/UserAccountSettings.stories.tsx
web-marketplace/src/components/organisms/UserAccountSettings/UserAccountSettings.types.ts
web-marketplace/src/lib/queries/react-query/registry-server/getAccounts/getAccountsQuery.types.ts
web-marketplace/src/pages/ProfileEdit/ProfileEdit.Settings.tsx
web-marketplace/src/pages/ProfileEdit/ProfileEdit.constants.ts
web-marketplace/src/pages/ProfileEdit/hooks/useSocialProviders.tsx
web-marketplace/src/utils/fetch/postData.ts

Closes: #2211
---
I have...
Go to https://deploy-preview-2221--regen-marketplace.netlify.app/ and log in.
Go to the settings page and try connecting/disconnect to/from google.
I have...

feat: connect/disconnect to/from google

---

web-components/src/components/modal/keplr-wallet-connect-modal/KeplrWalletConnectModal.constants.ts
web-components/src/components/modal/keplr-wallet-connect-modal/KeplrWalletConnectModal.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.ConnectWalletModal.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.constants.ts
web-marketplace/src/pages/ProfileEdit/ProfileEdit.Settings.tsx
web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx
web-marketplace/src/pages/ProfileEdit/hooks/useConnectWalletToAccount.tsx

Closes: regen-network/regen-web#2159
Prompt web2 user to connect a wallet for on-chain action
---
I have...
1. https://deploy-preview-2219--regen-marketplace.netlify.app/
I have...

feat: connect wallet to web2 account on action

---

web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.mock.ts
web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.tsx
web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.types.ts
web-marketplace/src/pages/Buyers/normalizers/normalizeEcologicalCreditCards.ts
web-www/generated/sanity-graphql.tsx
web-www/graphql/sanity/fragments/shared/ecologicalCreditCardFragment.graphql
web-www/lib/utils/normalizers/normalizeEcologicalCreditCards.ts
web-www/sanity-graphql.schema.json
web-www/tailwind.config.js

Closes: regen-network/rnd-dev-team#1829
Needs: https://github.com/regen-network/regen-sanity/pull/52
- handle optional offset generation methods for ecological cards
- handle secondary button to ecological cards
---
I have...
1.
I have...

feat: add secondary button to EcologicalCreditCard

---

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx
web-marketplace/src/lib/wallet/wallet.tsx

Closes: regen-network/regen-web#2233
- hide some user menu items (edit profile, settings, add account) for wallet connect users
---
I have...
1.
I have...

fix: hide menu items for wc users

---

web-marketplace/src/components/organisms/LoginButton/hooks/onLoginPostData.ts
web-marketplace/src/components/organisms/LoginFlow/hooks/useEmailConfirmationData.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.RetryFailedFunctions.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.tsx
web-marketplace/src/components/organisms/RegistryLayout/hooks/useOnProfileClick.tsx
web-marketplace/src/lib/atoms/error.atoms.ts
web-marketplace/src/lib/errors/apiErrors.ts
web-marketplace/src/lib/errors/hooks/useRetryCsrfRequest.tsx
web-marketplace/src/lib/wallet/hooks/useLogin.tsx
web-marketplace/src/lib/wallet/hooks/useLogout.tsx
web-marketplace/src/lib/wallet/hooks/useOnAccountChange.tsx
web-marketplace/src/pages/ProfileEdit/hooks/useConnectWalletToAccount.tsx
web-marketplace/src/pages/ProfileEdit/hooks/useSocialProviders.tsx
web-marketplace/src/utils/fetch/postData.ts

Closes: regen-network/regen-web#2235
- add a system to replay failed HTTP requests because of an expired CSRF token
---
I have...
Logout:
1. Go to https://deploy-preview-2245--regen-marketplace.netlify.app/
2. Log in to an account
3. Open a second tab
4. Go back to the first tab and try to log out (it should work as expected)
Account change:
1. Go to https://deploy-preview-2245--regen-marketplace.netlify.app/
2. Log in to an account
3. Log in a second account
4. Open a second tab
5. Go back to the first tab and try to change your account in the user menu dropdown (it should work as expected)
_All items are required. Please add a note if the item is …

fix: replay http requests with expired CSRF token

---

web-marketplace/src/lib/errors/hooks/useRetryCsrfRequest.tsx

Closes: #2258
As part of https://github.com/regen-network/regen-web/pull/2252 which introduced this bug, `retryCsrfRequest` was added to the dependency array of the `login` callback. Because `retryCsrfRequest` wasn't declared with `useCallback` and always changing, this was causing the `useEffect` in `useAutoConnect` (which indirectly depends on `login` that depends on `retryCsrfRequest`) to trigger indefinitely, eventually causing the app to error.
This issue was reproducible when logging in with an account that has a wallet address (which triggers `tryConnectWallet` in `useAutoConnect`) and then going to another page or reloading the app.
---
I …

fix: useCallback to define retryCsrfRequest to avoid infinite loop

---

docker-compose.yml
docker/indexer.Dockerfile
docker/scripts/indexer_init.sh
docker/scripts/indexer_start.sh

See https://github.com/regen-network/indexer/issues/53
Updates to the latest indexer commit and refactors local docker `indexer` image to use the latest `graphile` migrations. 
Follows the existing patterns in the `indexer` Docker `indexer.Dockerfile`, `indexer_start.sh` and `indexer_init.sh`: https://github.com/regen-network/indexer/tree/main/docker
---
I have...
1.
I have...

chore: update indexer in local environment

---

web-marketplace/src/pages/ProfileEdit/ProfileEdit.ViewProfile.tsx

ref: https://github.com/regen-network/regen-web/issues/2248#issuecomment-1931144892
---
I have...
1. Go to https://deploy-preview-2280--regen-marketplace.netlify.app/ and connect with a **web2** account (no wallet address)
2. Go to edit profile and click on "view profile"
3. It should go back to your profile page as expected
I have...

fix: link to view profile

---

web-components/src/components/icons/GreenPinIcon.tsx
web-components/src/components/icons/icons.stories.tsx
web-components/src/components/map/StaticMap.tsx

Since last release, the pin icon on the map on the top of the project pages was black instead of green/white.
---
I have...
https://deploy-preview-2293--regen-marketplace.netlify.app/project/wilmot
I have...

fix: PinIcon on StaticMap (project page)

---

web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.CreditClassCard.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx

Closes: regen-network/rnd-dev-team#1856
As part of this issue, I've also added some temporary off chain credit classes for the 2 prefinance projects on production with the appropriate primary impact/project benefits data. Those will appear correctly only once the code change in this PR is deployed to prod.
---
I have...
https://deploy-preview-2294--regen-marketplace.netlify.app/project/prefinance-project
I have...

feat: use offchain credit class to get primary impact/project benefits

---

web-marketplace/src/components/organisms/BasicInfoForm/BasicInfoForm.tsx
web-marketplace/src/pages/ProjectCreate/hooks/useProjectSaveAndExit.ts

Closes: #2290
---
I have...
1. Go to https://deploy-preview-2298--regen-marketplace.netlify.app
2. Log in and go to https://deploy-preview-2298--regen-marketplace.netlify.app/profile/projects
3. Create a new project
4. Fill in the basic info form, adding some decimal value for the size and hit "save & exit"
5. This should save and go back to /profile/projects page
I have...

fix: save and next button behavior

---

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx

As part of https://github.com/regen-network/regen-web/pull/2291, we forgot to update the "Projects" menu item to have 2 dropdown items for "All projects" and "Prefinance projects": https://www.figma.com/file/EPSVuGURedvRfO6LxUAQZs/Pre-financing?type=design&node-id=8%3A33002&mode=design&t=SxBVSQMQ7JTU72Py-1
---
I have...
https://deploy-preview-2307--regen-marketplace.netlify.app/
I have...

fix: add dropdown items to projects menu item

---

web-marketplace/src/components/organisms/SettingsForm/SettingsForm.schema.ts
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.utils.tsx
web-marketplace/src/hooks/projects/useProjectWithMetadata.ts
web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx

Closes:  regen-network/rnd-dev-team#1896
---
I have...
From https://deploy-preview-2317--regen-marketplace.netlify.app/
1. Log in and edit one of your project slug. If you input some UUID, it will display an error.
2. Go to https://deploy-preview-2317--regen-marketplace.netlify.app/project/a1fbc990-60fd-11ee-b6eb-0267c2be097b, it should redirect to https://deploy-preview-2317--regen-marketplace.netlify.app/project/prefinance-project and display prefinance related info.
I have...

fix: redirect project page from off chain UUID to slug based URL

---

web-components/src/utils/s3.ts

This is a bug that I encountered while working on something else. I haven't created any issue since it was really quick to fix.
From the project media form, when deleting an existing image, then adding another one and saving, there was an error when trying to delete the existing image (removing it from s3) because the cookies were not passed along with the DELETE request, resulting in some unauthorized error on the server side.
---
I have...
1. Go to https://deploy-preview-2318--regen-marketplace.netlify.app/ and login
2. Edit some project and go the the Media form
3. Upload an initial image as main photo for instance then SAVE
4. Delete this initial …

fix: add credentials to DELETE /files request

---

web-marketplace/src/pages/Dashboard/Dashboard.tsx

Closes:  regen-network/rnd-dev-team#1869
---
I have...
From https://deploy-preview-2320--regen-marketplace.netlify.app/
1. Log in with Keplr wallet addr A 
2. Switch to wallet addr B from Keplr, and do not accept the "prove ownership" popup, just close it 
3. Copy link to your profile from your profile page, this should have the right addr in it (addr A)
I have...

fix: use activeAccount addr in profile link

---

netlify.toml
web-components/src/components/atoms/CardRibbon/CardRibbon.tsx
web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.tsx
web-components/src/components/molecules/EcologicalCreditCard/EcologicalCreditCard.types.ts
web-marketplace/sanity-codegen.yml
web-marketplace/sanity-graphql.schema.json
web-marketplace/src/components/organisms/DetailsSection/DetailsSection.Credit.tsx
web-marketplace/src/components/organisms/DetailsSection/DetailsSection.constants.ts
web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx
web-marketplace/src/components/organisms/DetailsSection/DetailsSection.types.ts
web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
web-marketplace/src/generated/sanity-graphql.tsx
web-marketplace/src/graphql/sanity/AllCreditType.graphql
web-marketplace/src/graphql/sanity/EcologicalCreditCardFragment.graphql
web-marketplace/src/pages/Buyers/normalizers/normalizeEcologicalCreditCards.ts
web-marketplace/src/pages/CreditClassDetails/CreditClassDetailsSimple/CreditClassDetailsSimple.tsx
web-www/generated/sanity-graphql.tsx
web-www/graphql/sanity/fragments/shared/ecologicalCreditCardFragment.graphql
web-www/lib/utils/normalizers/normalizeEcologicalCreditCards.ts
web-www/sanity-graphql.schema.json

Closes: regen-network/rnd-dev-team#1907
Depends on: https://github.com/regen-network/regen-sanity/pull/58
---
I have...
**Marketplace**
Credit class page: https://deploy-preview-2324--regen-marketplace.netlify.app/credit-classes/USP01
Project page: https://deploy-preview-2324--regen-marketplace.netlify.app/project/USP01-001
**Website**
Updated the green tag on the featured credits cards to use credit category instead of credit type too (although that doesn't change anything visually):
https://deploy-preview-2324--regen-website.netlify.app
https://deploy-preview-2324--regen-website.netlify.app/buyers
_All items are required. Please add a note if the …

feat: add overrides for credit type and unit information in Sanity for Credit Class pages APP-2

---

web-marketplace/src/features/ecocredit/CreateBatchBySteps/CreateBatchMultiStepForm/CreditBasics.tsx
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/hooks/useQueryProjectsByIssuer.ts
web-marketplace/src/types/ledger/ecocredit.ts

https://regennetwork.atlassian.net/browse/APP-92?atlOrigin=eyJpIjoiMmEyMDFhNzBkN2Q1NDk3YTk2NTRmOWM0OGMwMWY4Y2MiLCJwIjoiaiJ9
---
I have...
**While testing, please be aware that getting the list of projects you can issue credits to is based on an indexer based query for getting classes by issuer address and the staging indexer database is pruned so you might not see all classes you actually an issuer of on dev / deploy previews (this won't be the case on prod since the indexer db is not pruned there of course)**
From https://deploy-preview-2342--regen-marketplace.netlify.app/ecocredits/create-batch
login with an account that is an issuer and check out …

fix: APP-92 create batch form projects dropdown shows projects by admin instead of class issuers

---

web-components/src/components/header/components/UserMenuItems.tsx

https://regennetwork.atlassian.net/browse/APP-102?atlOrigin=eyJpIjoiZTcwMTgxYzNiNTgwNDEyOWIzNmMyNDIxN2JhNDA2NDYiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2368--regen-marketplace.netlify.app/, log in with an account with a long name or a web2 account with no name but somewhat long email. Those should now be truncated in the user menu.
I have...

fix: APP-102 truncate profile name/email in user menu

---

patches/@ledgerhq+live-network+1.1.7.patch
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx

https://regennetwork.atlassian.net/browse/APP-95?atlOrigin=eyJpIjoiMTNlOTgxY2YwOWIyNDZhMThmNDgzNGNhZDY2Njc2YjAiLCJwIjoiaiJ9
---
I have...
https://deploy-preview-2345--regen-marketplace.netlify.app/
This can be tested if you login with a web3 account, then wait enough for the login session to expire (24 hours) or for testing purposes in order to mimic that, you can just open the dev tool, go to "Application" tab, then cookies and delete the two cookies with name session and session.sig and reload. You'll get logged out.
Finally, log back in with another web2 account. You should only see the projects from this web2 account, while if you do the same on …

fix: APP-95 projects from a Keplr wallet login show up when logged in via a new account

---

web-marketplace/src/components/organisms/EcocreditsTable.tsx

https://regennetwork.atlassian.net/browse/APP-178?atlOrigin=eyJpIjoiM2Q3M2QyMmZjMTYwNGYyZjliZjhjNTlkYWNlMWNlOTQiLCJwIjoiaiJ9
closes: #2353
We were displaying the batch start/end dates on the portfolio page in local time, instead of UTC, which might result in Jan 1 being displayed as Dec 31 for people in the US.
---
I have...
https://deploy-preview-2391--regen-marketplace.netlify.app/profiles/regen1cg9l00yfr8ckxc0wnxag6ss96grdzsdmtl97w5/portfolio
I have...

fix: APP-178 display UTC batch start/end dates

---

web-marketplace/src/components/organisms/BasicInfoForm/BasicInfoForm.tsx

https://regennetwork.atlassian.net/browse/APP-147?atlOrigin=eyJpIjoiNmM4NzUwMzQzODVhNDM5MWI4NjAwNDY5MWU4N2I3Y2EiLCJwIjoiaiJ9
---
I have...
From https://deploy-preview-2386--regen-marketplace.netlify.app/, create or edit a new project.
Update the project size to use "acres" and save.
Going back to the basic info form, it should show the right size unit.
I have...

fix: APP-147 project size always displayed as hectares in BasicInfoForm

---

web-components/src/components/read-more/index.tsx
web-marketplace/src/components/organisms/ProjectStorySection/ProjectStorySection.tsx

I've added:
- A missing key prop in ReadMore component.
- Updated the hasMedia prop in StoryText to check for a media url 
---
I have...
Create a new project with a Long-form project story and no media, then visit the project page and open the Read More
- Marketplace: https://deploy-preview-2392--regen-marketplace.netlify.app/
I have...

fix: APP-138 long story text width

---

web-marketplace/src/pages/BasicInfo/BasicInfo.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx
web-marketplace/src/pages/ProjectCreate/ProjectCreate.store.tsx
web-marketplace/src/pages/ProjectCreate/ProjectCreate.tsx

I have added props to the ProjectCreate context to track modal state and then hide the modal when already viewed.
The modal will also be hidden for projects that are in Draft status.
Issue: https://regennetwork.atlassian.net/browse/APP-193
---
I have...
1. Go to the Marketplace>Projects>Create New Project. Click Continue in the modal window and fill up the form then click "Save and Next". On the Location page click the back button in the footer. 
2. The modal window shouldn't show up again. 
Marketplace:  https://deploy-preview-2399--regen-marketplace.netlify.app/
I have...

fix APP-193 hide project create modal

---

web-components/src/utils/locationStandard.ts
web-marketplace/src/pages/ProjectReview/ProjectReview.util.tsx
web-marketplace/src/pages/ProjectReview/hooks/useGetJurisdiction.tsx

https://regennetwork.atlassian.net/browse/APP-192
Changes:
- Refactor getJurisdiction to make sure that at least a country code is returned if not subdivision code is found and to improve readability.
---
I have...
1. In the Marketplace create a new project and verify that after selecting a location the jurisdiction information in the Review page is showing a country code, a subdivision code or a subdivision code with postcode included.
Marketplace: https://deploy-preview-2402--regen-marketplace.netlify.app/
I have...

fix APP-192 iso codes issue on project create

---

web-components/src/components/modal/SaveChangesWarningModal/SaveChangesWarningModal.tsx
web-components/src/components/modal/modal.stories.tsx
web-marketplace/src/components/organisms/PostFlow/PostFlow.tsx
web-marketplace/src/components/organisms/PostForm/PostForm.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx
web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx
web-marketplace/src/pages/ProjectEdit/ProjectEdit.tsx

https://regennetwork.atlassian.net/browse/APP-200
- Added a confirmation modal to prevent accidental post deletion when creating a new post.
- Refactored the confirmation modal used in Edit Profile and Edit Project into a new component to improve reusability.
---
I have...
1. On the `Dashboard>Projects` create a new post. If any information is added to the new post form and then click on Close X button or Cancel button a confirmation modal should popup .
2. Please also verify that confirmation modals are still working as expected in the Edit Profile and Edit Project forms.
Marketplace: https://deploy-preview-2405--regen-marketplace.netlify.app/
_All …

feat: APP-200 create post close confirmation modal

---

web-marketplace/src/pages/ProjectMetadata/ProjectMetadata.config.ts

ref: https://regennetwork.atlassian.net/browse/APP-207
---
I have...
From https://deploy-preview-2400--regen-marketplace.netlify.app/, create or edit an on chain project and go to the Metadata form, add some value for `regen:projectDeveloper`. This should be saved in the on chain metadata.
I have...

fix: temporarily remove `regen:projectDeveloper` from Project Metadata form omitted keys

---

web-marketplace/src/components/organisms/ListProject/ListProject.constants.ts
web-marketplace/src/components/organisms/ListProject/ListProject.tsx

https://regennetwork.atlassian.net/browse/APP-157?atlOrigin=eyJpIjoiYzU3MTNmMDlhN2Y0NDM4NDg3NTEyYzg3ZjFjY2FhMDIiLCJwIjoiaiJ9
---
I have...
Check that "create project" is used instead of "list a project" on https://deploy-preview-2421--regen-marketplace.netlify.app/
I have...

chore: APP-157 use 'create project' instead of 'list a project'

---

web-components/src/components/organisms/PostFiles/PostFiles.tsx
web-marketplace/src/lib/queries/react-query/registry-server/getPostQuery/getPostQuery.types.ts
web-marketplace/src/pages/Post/Post.Footer.tsx
web-marketplace/src/pages/Post/Post.tsx

https://regennetwork.atlassian.net/browse/APP-194?atlOrigin=eyJpIjoiNzM5NzkzNmI1M2VkNDI2Zjg0ZjFmZDA1YjE1MWIxNmUiLCJwIjoiaiJ9
---
I have...
https://deploy-preview-2398--regen-marketplace.netlify.app
1. Navigate through posts for a project using prev/next buttons, from https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVgkbviJfqjXYKLoqWt4WAigAYXLLjvYBB1wxB4uoukNM9LVVXT3.rdf. You shouldn't see any private posts.
2. Log in and access one of your post page, you should be able to navigate to a private post using prev or next button.
your handle …

feat: APP-194 add prev/next post functionality

---

web-components/src/components/organisms/PostFiles/PostFiles.Cards.Mobile.tsx
web-components/src/components/organisms/PostFiles/PostFiles.Public.tsx
web-components/src/components/organisms/PostFiles/components/Buttons.tsx
web-components/src/components/organisms/PostFiles/components/TextOrIconFilePreview.tsx

https://regennetwork.atlassian.net/browse/APP-294
Also adds file previews to mobile map view, which were missing.
---
I have...
From https://deploy-preview-2455--regen-marketplace.netlify.app/post/regen:13toVg51tcwo2J82Jc5JUmjLbKahxVdDgLcmwvTwFMgU2h5L7gc4Ptt.rdf, test the "open file" and "close" icon on mobile (or using desktop, toggling mobile view from the dev tools)
I have...

fix: APP-294 mobile post map icons

---

web-marketplace/src/pages/ProjectReview/ProjectReview.tsx

https://regennetwork.atlassian.net/browse/APP-296
---
I have...
Log in using a wallet address that is a class issuer and create an on-chain project.
After publishing it, check in the query result or the db that project.published is set to true.
I have...

fix: APP-296 set published to true after on chain project created

---

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx

https://regennetwork.atlassian.net/browse/APP-310
Also showing 404 page when accessing a draft project by **slug** (it was showing the full project page instead)
---
I have...
https://deploy-preview-2457--regen-marketplace.netlify.app/profile/projects
Log in and on your projects page, check out that "create post" is disabled for any draft projects, even if they have a location.
I have...

fix: APP-310 create post draft disabled

---

web-marketplace/src/components/organisms/EditProfileForm/EditProfileForm.tsx
web-marketplace/src/components/organisms/RolesForm/components/ProfileModal/ProfileModal.tsx

https://regennetwork.atlassian.net/browse/APP-295
---
I have...
https://deploy-preview-2459--regen-marketplace.netlify.app/
Log in and go to edit your profile.
Update your profile image or background image (without updating anything else). After successful image upload, the save button should be enabled and you can save the changes.
I have...

fix: APP-295 set Edit Profile form as dirty on image change

---

web-components/src/components/organisms/PostFiles/components/FilePreview.tsx
web-marketplace/src/components/organisms/EditFileForm/EditFileForm.tsx
web-marketplace/src/components/organisms/PostForm/PostForm.tsx

Since I've merged https://github.com/regen-network/regen-server/pull/483, there was an issue when uploading data post file and previewing them on the form because we were not using the decoded URL.
---
I have...
Create a post and upload a file, if that's an image you should see the preview in the "edit file" form, then after submitting you should see the file preview in the list of files on the create post form.
I have...

fix: APP-316 decoding file URLs

---

web-components/src/components/cards/ProjectCard/ProjectCard.tsx
web-components/src/components/tooltip/index.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.constants.ts
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.utils.tsx

https://regennetwork.atlassian.net/browse/APP-243
---
1. Check on a mobile phone that when logged in with Keplr, the `Create Post` buttons in the admin's projects page are not visible.
I have...

feat: APP-243 disable create post button in keplr mobile

---

web-marketplace/src/components/organisms/PostForm/PostForm.tsx
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po

https://regennetwork.atlassian.net/browse/APP-255
Also fixes some small translation issue
---
I have...
From https://deploy-preview-2466--regen-marketplace.netlify.app/, log in and create a post. From the post form, check that clicking "View all supported file types»" opens the right link in a new tab.
I have...

chore: APP-255 add supported file types link

---

web-marketplace/src/pages/Post/Post.Header.tsx
web-marketplace/src/pages/Post/hooks/useDelete.ts

Last minute bug fix: https://github.com/regen-network/regen-web/pull/2469#issuecomment-2343712072
---
I have...
From https://deploy-preview-2471--regen-marketplace.netlify.app/, try to delete a post from the data stream section and the post page itself. It should show a success banner. From the post page, it should redirect to the updated data stream on the project page.
I have...

fix: delete post success banner and redirect

---

web-marketplace/src/ledger.tsx

Fixing issue when trying to sign transactions
ref: https://github.com/regen-network/regen-web/pull/2489#issuecomment-2385770696
---
I have...
Try to sign any type of transaction (from profile portfolio or projects, from project cards "buy", create post attest, etc.)
I have...

fix: prevent rendering LedgerProvider until wallet is loaded

---

web-components/src/components/table/ActionsTable.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx
web-marketplace/src/components/organisms/SellOrdersTable/SellOrdersTable.tsx
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/pages/Marketplace/Storefront/Storefront.constants.ts
web-marketplace/src/pages/Marketplace/Storefront/Storefront.tsx

https://regennetwork.atlassian.net/browse/APP-347
---
I have...
https://deploy-preview-2488--regen-marketplace.netlify.app/storefront
1. Verify that the Trade item in the main navigation is not present.
2. When _logged in_ go to `/storefront` and check that the Buy button is no present in the Actions column but the Cancel option is still available.
3. When _not logged in_ go to `/storefront` and check that the Actions column is not visible.
I have...

feat: APP-347 get rid of buy buttons and sell orders page in main nav

---

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/components/templates/ProjectDetails/hooks/useGetProject.ts
web-marketplace/src/components/templates/ProjectDetails/hooks/useNavigateToSlug.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.tsx

Redirect to slug based project url if project has a slug.
Doing the same as on the project page so that it retrieves slug-based project on sanity.
---
I have...
https://deploy-preview-2507--regen-marketplace.netlify.app/project/C01-001/buy should redirect to https://deploy-preview-2507--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
I have...

fix: navigate to slug based project url on buy page

---

web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx

https://regennetwork.atlassian.net/browse/APP-393
I have...
1. Go to the Buy Credits form (https://deploy-preview-2509--regen-marketplace.netlify.app/project/C01-001/buy) and with USD selected verify that the dollar sign is properly aligned on both mobile and desktop screens.
I have...

style: APP-393 align dollar sign in small screens

---

web-marketplace/src/clients/terrasos/Terrasos.base.css
web-marketplace/src/clients/terrasos/Terrasos.muiTheme.ts

Closes: APP-419
Change the default font to Montserrat in the base CSS and MUI theme.
---
I have...
1.
I have...

feat: APP-419 use Montserrat font by default

---

web-marketplace/graphql.schema.json
web-marketplace/src/generated/graphql.tsx
web-marketplace/src/graphql/AllProjects.graphql
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
web-marketplace/src/pages/Projects/hooks/useOffChainProjects.tsx

Closes: APP-376
Filter Terrasos projects by type.
---
I have...
1.
I have...

feat: filter projects by type

---

web-components/src/components/SupCurrencyAndAmount/SupCurrencyAndAmount.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.utils.tsx
web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx
web-marketplace/src/components/molecules/OrderSummaryCard/OrderSummaryCard.Content.tsx
web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx

https://regennetwork.atlassian.net/browse/APP-404
I have...
1. Go to the Choose Credits step in the Buy Credits flow and verify that the currency input field doesn't throw an error when changing the value
2. https://deploy-preview-2514--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
I have...

fix: APP-404 update field and trigger validation instead of using onChange

---

package.json
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx
web-www/components/templates/Layout/Layout.config.ts

Part of https://regennetwork.atlassian.net/browse/APP-424
**DO NOT MERGE MANUALLY** (https://www.notion.so/regennetwork/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62?pvs=4#8acaa2cb42e740868083ab24df616be1)
**DO NOT MERGE BEFORE domains are updated.**
---
I have...
1.
I have...

chore: APP-424 update registry/handbook links

---

web-components/src/components/cards/ProjectCard/ProjectCard.CreditPrice.tsx
web-components/src/components/cards/ProjectCard/ProjectCard.tsx
web-marketplace/src/components/molecules/ProjectBatchTotals/ProjectBatchTotals.tsx
web-marketplace/src/components/organisms/ProjectCardsSection/ProjectCardsSection.tsx
web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.MoreProjects.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/components/templates/ProjectDetails/hooks/useMoreProjects.ts
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
web-marketplace/src/pages/Projects/AllProjects/utils/getCreditsTooltip.ts

https://regennetwork.atlassian.net/browse/APP-434
---
I have...
From any project page, eg https://deploy-preview-2526--regen-marketplace.netlify.app/project/ee345f38-918b-11ef-8f65-022e215a294f, check out "More Projects" section at the bottom, it should show 3 random projects from https://deploy-preview-2526--regen-marketplace.netlify.app/projects/1 (on staging these are not necessarily all real terrasos projects)
I have...

fix: APP-434 include offchain projects to more projects section for terrasos

---

web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/components/templates/ProjectDetails/hooks/useGetProject.ts
web-marketplace/src/components/templates/ProjectDetails/hooks/useMoreProjects.ts

This is a small fix of https://github.com/regen-network/regen-web/pull/2521
On project/id/buy, we were seeing 404 page for a few ms before the actual buy page even if the project existed.
---
I have...
While being logged in with keplr, check out loading of https://deploy-preview-2534--regen-marketplace.netlify.app/project/C01-010/buy vs https://dev.app.regen.network/project/C01-010/buy
I have...

fix: adjust projectNotFound

---

web-marketplace/src/pages/Projects/AllProjects/AllProjects.config.ts
web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx

Closes: APP-461
Remove filters for Terrasos and change pagination to 9 projects per page.
---
I have...
1.
I have...

feat: APP-461 remove filters for Terrasos and change pagination to 9

---

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.TerrasosFooter.tsx
web-marketplace/src/components/organisms/TerrasosFooter/TerrasosFooter.constants.ts
web-marketplace/src/components/organisms/TerrasosHeader/TerrasosHeader.constants.ts
web-marketplace/src/components/organisms/TerrasosHeader/TerrasosHeader.tsx

Closes: APP-481
Keep origin language for external links.
---
I have...
1.
I have...

fix: APP-481 keep origin language for external links

---

web-components/src/components/cards/CredibilityCard/CredibilityCard.tsx
web-marketplace/src/components/organisms/DetailsSection/DetailsSection.tsx

Closes: APP-478
Remove color override on Terrasos credibility card icon.
---
I have...
1.
I have...

fix: APP-478 remove color override for credibility cards on terrasos

---

web-components/src/components/organisms/ProjectFilters/ProjectFilters.tsx
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterBody.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterBody.utils.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterMobile.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.normalizers.ts
web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx
web-marketplace/src/pages/Projects/Projects.context.tsx
web-marketplace/src/pages/Projects/Projects.tsx
web-marketplace/src/pages/Projects/hooks/useProjects.tsx
web-marketplace/src/pages/Projects/hooks/useProjectsSellOrders.types.ts

https://regennetwork.atlassian.net/browse/APP-482
---
I have...
1.
I have...

fix: APP-482 hide filters with no projects at all

---

web-marketplace/src/pages/BuyCredits/BuyCredits.tsx

https://regennetwork.atlassian.net/browse/APP-409
I have...
1. https://deploy-preview-2545--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
2. Select crypto and then Buy tradable ecocredits
3. Swap back to card and back again to crypto - verify that the Crypto purchase options is set to Retire credits now
I have...

fix: APP-409 set retiring to true when payment is card

---

web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.CreditClassCard.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx

Closes: APP-496
Hide program in project card for Terrasos.
---
I have...
1.
I have...

fix: hide program on terrasos in project card

---

web-components/src/components/cards/TebuCard/TebuCard.CommonBody.tsx
web-components/src/components/cards/TebuCard/TebuCard.tsx
web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.TebuInfo.tsx

https://regennetwork.atlassian.net/browse/APP-494
---
I have...
1.
I have...

fix: APP-494 tebu factors card grid display

---

web-components/src/components/SupCurrencyAndAmount/SupCurrencyAndAmount.tsx
web-marketplace/src/components/molecules/AmountWithCurrency/AmountWithCurrency.tsx
web-marketplace/src/components/molecules/DenomIconWithCurrency/DenomIconWithCurrency.tsx
web-marketplace/src/components/molecules/OrderSummaryCard/OrderSummaryCard.Content.tsx

https://regennetwork.atlassian.net/browse/APP-450
I have...
1. Login with the testing user 
2. Navigate to a project buy page while being logged in with the credits seller account. i.e https://deploy-preview-2536--regen-marketplace.netlify.app/project/C01-010/buy
3. Verify that the error page does no longer appear before being redirected to the projects page
I have...

fix: APP-450 handle undefined errors in buy page when seller is logged in

---

web-marketplace/sanity-codegen.yml
web-marketplace/sanity-graphql.schema.json
web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx
web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.types.ts
web-marketplace/src/components/organisms/SellOrdersActionsBar/SellOrdersActionsBar.tsx
web-marketplace/src/components/templates/ProjectDetails/ProjectDetails.tsx
web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCredits.utils.tsx
web-marketplace/src/components/templates/ProjectDetails/TerrasosCreditsInfo/TerrasosCreditsInfo.tsx
web-marketplace/src/generated/sanity-graphql.tsx
web-marketplace/src/graphql/sanity/ComplianceInfo.graphql
web-marketplace/src/graphql/sanity/TerrasosBookCall.graphql
web-marketplace/src/lib/queries/react-query/sanity/getTerrasosBookCallQuery/getTerrasosBookCallQuery.ts
web-marketplace/src/lib/queries/react-query/sanity/getTerrasosBookCallQuery/getTerrasosBookCallQuery.types.ts

https://regennetwork.atlassian.net/browse/APP-508
---
I have...
1. From Terrasos app https://deploy-preview-2565--terrasos.netlify.app/project/biocultural-jaguar-credits-ancestral-stewardship-in-the-sharamentsa-community-2, "Book a call" button for terrasos projects going to terrasos website contact page
2. "Book a call" button from compliance info tabs is the same https://deploy-preview-2565--terrasos.netlify.app/project/C02-009
3. From Regen app https://deploy-preview-2565--regen-marketplace.netlify.app/project/354637ec-a687-11ef-b1b2-022e215a294f, "Book a call" button for terrasos projects going to internal calendy
4. From Regen app, other off …

feat: APP-508 show book call button on terrasos project bottom banner

---

web-components/src/components/stepper/index.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.utils.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsInput.tsx
web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx
web-marketplace/src/components/molecules/OrderSummaryCard/OrderSummaryCard.Content.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.constants.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.schema.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx

https://regennetwork.atlassian.net/browse/APP-396
I have...
1. https://deploy-preview-2544--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
2. Verify that the currency input when set to USD only accepts two decimals.
3. Verify that an error is shown when the amount of USD is less than 0.50
I have...

feat: APP-396 two decimal digits for usd amount

---

web-marketplace/src/components/molecules/ProjectBatchTotals/ProjectBatchTotals.tsx
web-marketplace/src/components/organisms/ProjectTopSection/ProjectTopSection.tsx

https://regennetwork.atlassian.net/browse/APP-528
---
I have...
1.
I have...

fix: APP-528 registered credits in compliance credits tab

---

web-components/src/components/header/Header.styles.ts
web-components/src/components/header/index.tsx
web-components/src/components/mobile-menu/index.tsx
web-marketplace/src/components/organisms/ListProject/ListProject.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx

https://regennetwork.atlassian.net/browse/APP-383
I have...
1. Check '+ Create project' button is aligned as expected both when users are logged in and not logged in.
=> https://deploy-preview-2568--regen-marketplace.netlify.app/
I have...

fix: APP-383 align create project button

---

web-components/src/components/inputs/new/EditableInput/EditableInput.stories.tsx
web-components/src/components/inputs/new/EditableInput/EditableInput.test.tsx
web-components/src/components/inputs/new/EditableInput/EditableInput.tsx
web-components/src/components/inputs/new/EditableInput/EditableInput.utils.test.ts
web-components/src/components/inputs/new/EditableInput/EditableInput.utils.ts
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.test.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.utils.test.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.utils.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsInput.tsx
web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx
web-marketplace/src/components/molecules/OrderSummaryCard/OrderSummaryCard.Content.tsx

https://regennetwork.atlassian.net/browse/APP-407
I have...
https://deploy-preview-2572--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
1. Check the reported bug and the zero leading functionality mentioned in ticket work as expected
I have...

fix APP 407 inputs logic

---

web-marketplace/src/pages/EcocreditsByAccount/EcocreditsByAccount.tsx

https://regennetwork.atlassian.net/browse/APP-536
I have noticed that when clicking on the link to 'mintscan.io' it doesn't work with the [account id](https://www.mintscan.io/regen/address/29533874-7476-11ef-a949-0afffa81c869) but it does with the [regen address](https://www.mintscan.io/regen/address/regen16dk9z6pegzjfmu8v4xam04pfglvd4rwzpjruyj), so I have changed it, review this too please. 
The same thing doesn't work either in dev, is this known? In dev it points to 'https://redwood.regen.aneka.io/accounts/' instead of mintscan.io.
I have...
1. https://deploy-preview-2585--regen-marketplace.netlify.app/
2. Check the profile page of organization accounts show the regen address instead of the account id
3. Check that when clicking on the regen address the link works and mintscan.io loads …

fix: APP-536 show regen address instead of account id in user profile

---

web-marketplace/src/lib/rdf/rdf.compact.ts
web-marketplace/src/lib/rdf/rdf.unknown-fields.ts

Testing to see if this fixes https://github.com/regen-network/regen-web/issues/2495
---
I have...
1.
I have...

Prevent errors when processing additional rdf metadata

---

web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.constants.ts
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsAmount.types.tsx
web-marketplace/src/components/molecules/CreditsAmount/CreditsInput.tsx
web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx
web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.Retirement.tsx
web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.tsx
web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseFormFiat.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.CryptoOptions.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx
web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.CardInfo.tsx
web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.PaymentInfo.tsx
web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.tsx
web-marketplace/src/components/templates/MultiStepTemplate/MultiStep.context.tsx
web-marketplace/src/components/templates/MultiStepTemplate/MultiStepTemplate.tsx
web-marketplace/src/hooks/useStorage.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx
web-marketplace/src/pages/BuyCredits/BuyCredits.atoms.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.tsx
web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx

https://regennetwork.atlassian.net/browse/APP-410
Now when users interact with the forms the information should be stored in the localstorage automatically even when the next button hasn't been clicked yet, and therefore, on navigating away and back to the same page, users should be in the same step and see the same form data as before navigating away.  
---
I have...
1. https://deploy-preview-2574--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
2. Edit the form and navigate away then come back to the same page and verify the step and the form data is the same as before navigating away. 
_All items are required. Please add a note if the item …

fix: APP-410 save buy flow on last user interaction

---

web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.schema.tsx
web-marketplace/src/lib/normalizers/projects/normalizeProjectsWithMetadata.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx

Closes: https://regennetwork.atlassian.net/browse/APP-571
---
I have...
This can be tested on https://deploy-preview-2592--regen-marketplace.netlify.app/project/C01-010
As you can on Sanity, this project has some fiat sell orders set up: https://regen.sanity.studio/staging/structure/shared;projects;english;c9ae90a7-d3d4-4ffa-b1da-baf573b783f6 
with corresponding quantities: http://redwood.regen.network:1317/regen/ecocredit/marketplace/v1/sell-orders/413 has 1 and http://redwood.regen.network:1317/regen/ecocredit/marketplace/v1/sell-orders/414 has 2 credits
but if buying all fiat credits, it would result in 0.1*1 + 0.1*2 = 0.3 which is lower than $0.5 …

fix: APP-571 disable credit card option when available fiat credits are below $0.5

---

web-marketplace/src/components/molecules/CreditsAmount/CurrencyInput.tsx

https://regennetwork.atlassian.net/browse/APP-447
I have...
1. Verify that projects with a single crypto currency available should not have a dropdown in the currency field while projects with multiple options should have a dropdown:
- Project with a single crypto currency: https://deploy-preview-2593--regen-marketplace.netlify.app/project/C01-010/buy
- Project with multiple crypto currencies: https://deploy-preview-2593--regen-marketplace.netlify.app/project/C01-001/buy
I have...

fix: APP-447 remove dropdown when only one crypto currency available

---

tailwind.common.js
web-components/src/components/header/Header.styles.ts
web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.Item.tsx
web-components/src/components/header/components/HeaderDropdown/HeaderDropdown.tsx
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.Content.tsx
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.Hover.styles.ts
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.Hover.tsx
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.styles.ts
web-components/src/components/header/components/HeaderMenuItem/HeaderMenuItem.tsx
web-components/src/components/header/components/HeaderMenuItem/hooks/useMenuState.tsx
web-components/src/components/header/components/UserMenuItem.Profile.tsx
web-components/src/components/header/components/UserMenuItem.styles.ts
web-components/src/components/header/components/UserMenuItem.tsx
web-components/src/components/header/components/UserMenuItems.tsx
web-components/src/components/header/index.tsx
web-components/src/components/mobile-menu/MobileMenu.styles.ts
web-components/src/components/mobile-menu/index.tsx

https://regennetwork.atlassian.net/browse/APP-374
I have...
1. https://deploy-preview-2581--regen-marketplace.netlify.app/
2. check the navigation dropdown and the hamburger icon work on small screens as well as in desktop screens.
3. Both the hamburger icon navigation and the dropdown navigation should now:
- Close when the other one is opened.
- Toggle when clicked again.
- Close when open and a click occurs outside of them.
- Close when a nav item is clicked.
I have...

feat: APP-374 header navigation toggle

---

web-components/src/components/organisms/ProjectFilters/ProjectFilters.utils.ts
web-marketplace/src/lib/atoms/projects.atoms.ts
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/pages/Projects/AllProjects/AllProjects.CommunityFilter.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.CreditClassFilters.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterBody.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterMobile.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.constants.ts
web-marketplace/src/pages/Projects/AllProjects/AllProjects.normalizers.ts
web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.utils.tsx
web-marketplace/src/pages/Projects/PrefinanceProjects/PrefinanceProjects.tsx
web-marketplace/src/pages/Projects/Projects.context.tsx
web-marketplace/src/pages/Projects/Projects.normalizers.tsx
web-marketplace/src/pages/Projects/Projects.tsx
web-marketplace/src/pages/Projects/Projects.utils.ts
web-marketplace/src/pages/Projects/hooks/useClientFilters.tsx
web-marketplace/src/pages/Projects/hooks/useResetFilters.tsx

Closes: https://regennetwork.atlassian.net/browse/APP-545
---
I have...
From https://deploy-preview-2595--regen-marketplace.netlify.app/projects/1
- check the filters on desktop are still working as before
- check the filters on mobile are only applied after clicking "apply filters" and the number of selected filters that is displayed corresponds to the number of types of filters that are different from their initial values (ie for credit classes, even if you select/unselect multiple credit classes, that will only correspond to 1)
your handle next to the items …

feat: APP-545 mobile projects filters

---

web-marketplace/src/clients/regen/Regen.Routes.tsx
web-marketplace/src/lib/queries/react-query/registry-server/getAccounts/getAccountsQuery.types.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.loader.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.tsx

https://regennetwork.atlassian.net/browse/APP-491
I have...
1. Login with a user. i.e our testing account (Sarah McFee)
2. Go to a project where the user is not allowed to buy credits. i.e: https://deploy-preview-2591--regen-marketplace.netlify.app/project/C01-010
3. Manually update the URL to go to the buy page by adding `/buy` at the end. i.e https://deploy-preview-2591--regen-marketplace.netlify.app/project/C01-010/buy
4. The user should be redirected to the project details page without seeing the BuyCredits page first.
your handle next to the items reviewed …

fix: APP-491 empty choose credits form appears for ms

---

web-components/src/theme/muiTheme.ts
web-marketplace/src/components/organisms/Order/Order.Summary.tsx
web-marketplace/src/components/organisms/Order/Order.SummaryRow.tsx
web-marketplace/src/components/organisms/Order/Order.tsx

Closes: https://regennetwork.atlassian.net/browse/APP-556
---
I have...
https://deploy-preview-2597--regen-marketplace.netlify.app/dashboard/admin/my-orders
Log in with an account that has made some crypto and/or fiat orders and check out your orders.
I have...

fix: APP-556 orders UI 

---

web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Footer.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx

https://regennetwork.atlassian.net/browse/APP-575
Only moved NCT header nav item to footer, the other items mentioned in the task description had already been done.
---
I have...
https://deploy-preview-2601--regen-marketplace.netlify.app/
Check NCT header nav item has been moved to the footer under "Trade"
I have...

chore: APP-575 move NCT to footer

---

web-marketplace/src/pages/BuyCredits/BuyCredits.Form.tsx

https://regennetwork.atlassian.net/browse/APP-441
I have...
1. Create a new user without adding a name.
2. Go to the buy credits flow and buy credits adding a name.
3. Verify in the user's profile edit page that the name has been updated with the name given during credits purchase.
I have...

feat: APP-441 update account name during buy credits flow

---

web-marketplace/src/components/templates/ProjectDetails/hooks/useGetProject.ts
web-marketplace/src/hooks/projects/useProjectsWithOrders.ts
web-marketplace/src/hooks/useBuySellOrderData.tsx

Did not create a task but small fix to get into the release
---
I have...
When accessing a project buy page that has a slug, check that the fiat credits should be based on the sanity project data identified with this slug, ie for the C01-001 on chain project that has a slug mai-ndombe-4 on staging, it should fetch data from https://regen.sanity.studio/staging/structure/shared;projects;english;63de6010-79cd-4bf3-a89c-916d8337e1ba, not https://regen.sanity.studio/staging/structure/shared;projects;english;c57f9531-2711-44ca-90b3-2f5931579690 
your handle next to …

fix: get sanity project using slug if any in useGetProject

---

web-components/src/components/SupCurrencyAndAmount/SupCurrencyAndAmount.tsx
web-components/src/components/inputs/new/EditableInput/EditableInput.tsx
web-components/src/components/inputs/new/EditableInput/EditableInput.utils.ts
web-components/src/utils/format.ts
web-marketplace/src/components/molecules/OrderSummaryCard/OrderSummaryCard.test.tsx
web-marketplace/src/components/organisms/Order/Order.test.tsx

https://regennetwork.atlassian.net/browse/APP-540
I have...
1. Verify that the decimal and thousands separators reflect the user's location in:
- Order summary card in the editable input and the prices => buy Credits flow step 2
- In the credits and currency inputs => buy Credits flow step 1
- Buy Credits flow  success modal
- My Orders page
- ... maybe we should standardise this and use the right numbers format based on location all across the marketplace, wdyt?
While working on this I've been changing the browser's language (in Chrome in Settings > Language > Preferred languages) and putting different languages on top makes the numbers format …

fix: APP-540 add support for commas in editable input

---

tailwind.common.js
web-marketplace/src/clients/regen/Regen.Routes.tsx
web-marketplace/src/components/organisms/AdminNavigation/AdminNavigation.ListItem.tsx
web-marketplace/src/components/organisms/AdminNavigation/AdminNavigation.tsx
web-marketplace/src/components/organisms/AdminNavigation/AdminNavigation.types.ts
web-marketplace/src/components/organisms/AdminNavigation/AdminNavigation.utils.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.config.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.utils.ts
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po
web-marketplace/src/lib/wallet/hooks/useDisconnect.tsx
web-marketplace/src/lib/wallet/wallet.tsx
web-marketplace/src/pages/Dashboard/MyProjects/MyProjects.constants.ts
web-marketplace/src/pages/Orders/Orders.CreditCardHidden.tsx
web-marketplace/src/pages/Orders/Orders.tsx
web-marketplace/src/pages/ProfileEdit/ProfileEdit.tsx

https://regennetwork.atlassian.net/browse/APP-582
---
I have...
1. Connect with Wallet Connect from desktop or mobile
2. Once connected, check out you can see your user profile image and name in the user dropdown
3. Check out the tooltip text for "Edit profile" and "Settings" being disabled
4. Go to "My orders" to see your crypto orders
I have...

fix: APP-582 User dropdown and "my orders" using Wallet Connect

---

web-components/src/components/organisms/ProjectFilters/ProjectFilters.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterBody.tsx
web-marketplace/src/pages/Projects/AllProjects/AllProjects.ProjectFilterMobile.tsx

https://regennetwork.atlassian.net/browse/APP-598
I have...
1. Go to the projects page and resize the screen to between 640px and 1024px wide: https://deploy-preview-2622--regen-marketplace.netlify.app/projects/1
2. Open the filters and click on 'see more' under Credit class filters so the scrollbar appears.
3. Scroll to the bottom of the filter and verify that the button to apply the filters stays at the bottom of the modal and the X close button stays at the top and always visible.
4. Verify that this is the case for screens below 640px as well.
your handle …

fix: APP-598 filters 'apply' and 'close' buttons position on mobile

---

web-marketplace/src/components/organisms/ConfirmationModal.tsx
web-marketplace/src/components/organisms/Order/Order.Summary.tsx

https://regennetwork.atlassian.net/browse/APP-624
---
I have...
This is hardly testable on staging since we do not have a working block explorer for redwood.
But now using `getHashUrl` allows to adjust the tx URL based on the environment and explorer since different block explorers may use different paths. In particular, on mintscan, we were missing some `regen/` in the URL 
I have...

fix: APP-624 use getHashUrl for blockchain record link

---

web-marketplace/src/components/organisms/AgreePurchaseForm/AgreePurchaseForm.tsx
web-marketplace/src/components/organisms/ChooseCreditsForm/ChooseCreditsForm.tsx
web-marketplace/src/components/organisms/PaymentInfoForm/PaymentInfoForm.tsx
web-marketplace/src/components/organisms/RegistryLayout/RegistryLayout.Header.tsx
web-marketplace/src/components/templates/MultiStepTemplate/MultiStep.context.tsx
web-marketplace/src/lib/wallet/hooks/useDisconnect.tsx
web-marketplace/src/lib/wallet/wallet.tsx
web-marketplace/src/pages/BuyCredits/BuyCredits.atoms.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.constants.ts
web-marketplace/src/pages/BuyCredits/BuyCredits.utils.tsx

https://regennetwork.atlassian.net/browse/APP-594
I have...
1. Navigate to the buy credits flow step 1 of a project: https://deploy-preview-2615--regen-marketplace.netlify.app/project/C01-007/buy
2. Log in
3. Open developer tools (right click > inspect)
4. Go to the tab `Application` and on the left sidebar go to `Storage` and open `Local Storage`
5. Find the item starting with `https://deploy-preview-2615--regen-marketplace.netlify.app/` and click on it
6. On the right panel you'll see a table with a heading called `key` and inside items with different names.
7. Find the ones starting with `buy-credits-`
8. Log out
9. All the items stariting with …

fix: APP-594 clear localStorage items related to buy credits on logout

---

web-marketplace/package.json
web-marketplace/src/clients/Clients.constants.tsx
web-marketplace/src/clients/regen/Regen.Routes.tsx
web-marketplace/src/clients/terrasos/Terrasos.Routes.tsx
web-marketplace/src/pages/ErrorPage/ErrorPage.tsx
web-marketplace/src/pages/ErrorPage/ErrorPage.utils.ts
web-marketplace/src/utils/safeLazy.tsx

https://regennetwork.atlassian.net/browse/APP-617
This PR implements an error catching mechanism for when dynamic imports fail:
- Replace `lazy()` with the new `safeLazy()` utility in all routes.
- Improve the `ErrorPage` to normalise errors, handle network errors and display assets.
- Adds a small (4.54 kB) dependency to help identify network errors in the `ErrorPage` (see package.json).
- By default, safeLazy() uses `ErrorPage`, but it accepts a fallback `ReactNode`. We might consider using this in the future for lazy loaded components too not just routes.
1. One way of testing this is to go to the deploy previw https://deploy-preview-2630--regen-marketplace.netlify.app/
2. Open the dev tools
3.  Go to the Network tab select **Offline** mode in the select drop down that says: No …

fix: AP-617 network errors handling

---

web-components/src/components/organisms/PostFiles/components/FilePreview.tsx
web-components/src/components/organisms/PostFiles/components/PdfPreview.tsx

https://regennetwork.atlassian.net/browse/APP-620
I was able to reproduce this bug by uploading PDF documents of different dimensions to the data posts. This fix focus on how the PDF layout is implemented.
1. Create a post in a project and upload a PDF file. 
2. The data posts stream layout should look as expected.
3. PDF preview should look as expected.
4. Repeat using PDFs with different dimensions.
I have...

fix APP-620 data posts layout isues

---

web-marketplace/src/clients/regen/Regen.Routes.tsx

https://regennetwork.atlassian.net/browse/APP-641
---
I have...
From https://deploy-preview-2648--regen-marketplace.netlify.app/dashboard/admin/my-orders, check this page is only accessible if logged in or connected with wallet connect.
I have...

fix: APP-641 make orders page only accessible when logged in or connected to keplr

---

web-marketplace/src/components/organisms/UserSellOrders/UserSellOrders.CreateButton.tsx
web-marketplace/src/components/organisms/UserSellOrders/UserSellOrders.Toolbar.tsx
web-marketplace/src/ledger.tsx
web-marketplace/src/lib/i18n/locales/en.po
web-marketplace/src/lib/i18n/locales/es.po

https://regennetwork.atlassian.net/browse/APP-721
---
I have...
https://deploy-preview-2677--regen-marketplace.netlify.app/dashboard/admin/sell
1. check that create sell order button is disabled when logged in with an account that doesn't have any tradable credits
2. check that it's enabled when logged in with an account that does have tradable credits
I have...

fix: APP-721 disable create sell order button if no tradable credits available
